// Archwires — NiTi, Stainless Steel, Beta Titanium, TMA, Copper NiTi
export const archwires = [
  {
    maId: 'PRD-032',
    maName: 'Nitinol Classic Archwires',
    maDescription: 'Superelastic nickel titanium archwires for initial leveling and alignment. Deliver light, continuous forces with excellent springback and shape memory. Available in round and rectangular cross-sections for upper and lower arches.',
    division: 'Archwires',
    category: 'Nickel Titanium',
    subcategory: 'Superelastic',
    sku: 'SOL-AWR-032',
    price: 28.00,
    listPrice: 34.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Nitinol-classic',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Nickel titanium (55% Ni, 45% Ti)', type: 'Superelastic', sizes: '.012, .014, .016, .018 round; .016x.022, .017x.025, .019x.025 rectangular', archForms: 'Natural, Ovoid, Tapered', packQuantity: '10 wires per pack', length: 'Standard (upper and lower available)', forceLevel: 'Light continuous', shelfLife: 'Indefinite (metallic)' },
    regulatory: { fdaClearance: 'K160345', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700132', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['archwire', 'NiTi', 'nitinol', 'superelastic', 'alignment'],
    volumeBreaks: [
      { minQty: 1, price: 28.00 },
      { minQty: 25, price: 26.00, label: 'Volume' },
      { minQty: 100, price: 24.00, label: 'Bulk' },
      { minQty: 500, price: 22.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-033',
    maName: 'Nitinol Super Elastic Archwires',
    maDescription: 'Enhanced superelastic NiTi archwires with an expanded stress plateau for consistent force delivery over larger deflections. Ideal for moderate to severe crowding cases where sustained light forces are required for efficient initial alignment.',
    division: 'Archwires',
    category: 'Nickel Titanium',
    subcategory: 'Super Elastic',
    sku: 'SOL-AWR-033',
    price: 32.00,
    listPrice: 39.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Nitinol-Super-Elastic',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Nickel titanium — enhanced superelastic', type: 'Super Elastic (SE)', sizes: '.012, .014, .016, .018 round; .016x.022, .017x.025, .019x.025 rectangular', archForms: 'Natural, Ovoid, Tapered', packQuantity: '10 wires per pack', deflectionRange: 'Up to 4 mm with consistent force', forceLevel: 'Light to medium' },
    regulatory: { fdaClearance: 'K160346', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700133', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['archwire', 'NiTi', 'super-elastic', 'alignment', 'crowding'],
    volumeBreaks: [
      { minQty: 1, price: 32.00 },
      { minQty: 25, price: 30.00, label: 'Volume' },
      { minQty: 100, price: 28.00, label: 'Bulk' },
      { minQty: 500, price: 26.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-034',
    maName: 'Nitinol Heat-Activated Archwires',
    maDescription: 'Thermoresponsive nickel titanium archwires that become fully active at mouth temperature. Deliver extremely light, continuous forces in the austenitic phase while remaining highly flexible during insertion in the martensitic phase at room temperature.',
    division: 'Archwires',
    category: 'Nickel Titanium',
    subcategory: 'Heat-Activated',
    sku: 'SOL-AWR-034',
    price: 38.00,
    listPrice: 46.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Nitinol-Heat-Activated',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Nickel titanium — thermoelastic', type: 'Heat-Activated (HA)', transitionTemp: '27°C (martensitic) to 37°C (austenitic)', sizes: '.014, .016, .018 round; .016x.022, .018x.025, .019x.025 rectangular', archForms: 'Natural, Ovoid, Tapered', packQuantity: '10 wires per pack', forceLevel: 'Ultra-light at body temperature' },
    regulatory: { fdaClearance: 'K170456', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700134', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['archwire', 'NiTi', 'heat-activated', 'thermoelastic', 'ultra-light'],
    volumeBreaks: [
      { minQty: 1, price: 38.00 },
      { minQty: 25, price: 35.00, label: 'Volume' },
      { minQty: 100, price: 33.00, label: 'Bulk' },
      { minQty: 500, price: 30.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-035',
    maName: 'Beta III Titanium Archwires',
    maDescription: 'Beta-titanium alloy archwires providing an optimal balance between stiffness and springback for intermediate and finishing stages. Delivers approximately 40% of the stiffness of stainless steel with excellent formability for custom bends.',
    division: 'Archwires',
    category: 'Titanium Alloy',
    subcategory: 'Beta Titanium',
    sku: 'SOL-AWR-035',
    price: 45.00,
    listPrice: 55.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Beta-III-Ttitanium-pack',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Beta III titanium alloy (Ti-11.5Mo-6Zr-4.5Sn)', type: 'Beta titanium', stiffness: '~40% of SS, ~2x NiTi', sizes: '.017x.025, .019x.025, .021x.025 rectangular', archForms: 'Natural, Ovoid, Tapered', packQuantity: '10 wires per pack', formability: 'Excellent — accepts 1st, 2nd, 3rd order bends', weldability: 'Can be spot-welded' },
    regulatory: { fdaClearance: 'K180456', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700135', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['archwire', 'beta-titanium', 'finishing', 'formable', 'intermediate'],
    volumeBreaks: [
      { minQty: 1, price: 45.00 },
      { minQty: 25, price: 42.00, label: 'Volume' },
      { minQty: 100, price: 39.00, label: 'Bulk' },
      { minQty: 500, price: 36.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-036',
    maName: 'Stainless Steel Archwires',
    maDescription: 'High-quality stainless steel archwires for working and finishing stages of orthodontic treatment. Provides maximum stiffness and torque expression with precise dimension control. Available in a wide range of sizes and preformed arch shapes.',
    division: 'Archwires',
    category: 'Stainless Steel',
    subcategory: 'Working/Finishing',
    sku: 'SOL-AWR-036',
    price: 18.00,
    listPrice: 22.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/round-wire',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'AISI 304 stainless steel', type: 'Full stiffness', sizes: '.016, .018, .020 round; .016x.022, .017x.025, .019x.025, .021x.025 rectangular', archForms: 'Natural, Ovoid, Tapered, Square', packQuantity: '10 wires per pack', torqueExpression: 'Maximum', formability: 'Good — accepts all bend types' },
    regulatory: { fdaClearance: 'K150234', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700136', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['archwire', 'stainless-steel', 'working', 'finishing', 'full-stiffness'],
    volumeBreaks: [
      { minQty: 1, price: 18.00 },
      { minQty: 25, price: 17.00, label: 'Volume' },
      { minQty: 100, price: 15.00, label: 'Bulk' },
      { minQty: 500, price: 14.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-037',
    maName: 'Lingual Retainer Wire – Dead Soft',
    maDescription: 'Dead soft stainless steel or braided wire for fabricating fixed lingual retainers. Highly adaptable to lingual tooth surfaces for passive retention. Available in round and braided configurations for upper and lower anterior retention.',
    division: 'Archwires',
    category: 'Retainer Wire',
    subcategory: 'Lingual Retention',
    sku: 'SOL-AWR-037',
    price: 22.00,
    listPrice: 27.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Lingual-retaining-filament',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Dead soft stainless steel or 3-strand braided SS', type: 'Retention wire', sizes: '.0175 3-strand braided, .028, .030, .032 round', spoolLength: '25 feet per spool', temper: 'Dead soft — fully annealed', application: 'Fixed lingual retainers (3-3 or 2-2)', formability: 'Excellent — conforms to any lingual contour' },
    regulatory: { fdaClearance: 'K150235', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700137', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['retainer-wire', 'lingual', 'dead-soft', 'braided', 'retention'],
    volumeBreaks: [
      { minQty: 1, price: 22.00 },
      { minQty: 25, price: 20.00, label: 'Volume' },
      { minQty: 100, price: 19.00, label: 'Bulk' },
      { minQty: 500, price: 18.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-038',
    maName: 'TMA (Beta Titanium) Archwires',
    maDescription: 'Titanium molybdenum alloy (TMA) archwires offering the ideal combination of low stiffness, high springback, and excellent formability for detailing and finishing. Widely used for intrusion arches, T-loops, and segmental mechanics.',
    division: 'Archwires',
    category: 'Titanium Alloy',
    subcategory: 'TMA',
    sku: 'SOL-AWR-038',
    price: 42.00,
    listPrice: 52.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Beta-III-Ttitanium-box',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Titanium molybdenum alloy (TMA)', type: 'Low-stiffness finishing wire', stiffness: '~42% of SS', springback: '~2x stainless steel', sizes: '.016x.022, .017x.025, .019x.025, .021x.025 rectangular', archForms: 'Natural, Ovoid, Tapered', packQuantity: '10 wires per pack', applications: 'Intrusion arches, T-loops, finishing, segmental' },
    regulatory: { fdaClearance: 'K180457', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700138', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['archwire', 'TMA', 'beta-titanium', 'finishing', 'segmental-mechanics'],
    volumeBreaks: [
      { minQty: 1, price: 42.00 },
      { minQty: 25, price: 39.00, label: 'Volume' },
      { minQty: 100, price: 36.00, label: 'Bulk' },
      { minQty: 500, price: 34.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-039',
    maName: 'Copper Ni-Ti Heat-Activated Archwires',
    maDescription: 'Copper-infused nickel titanium archwires with a precisely controlled transition temperature for consistent force delivery at body temperature. The copper addition narrows the hysteresis loop, providing more predictable and uniform tooth movement.',
    division: 'Archwires',
    category: 'Nickel Titanium',
    subcategory: 'Copper NiTi',
    sku: 'SOL-AWR-039',
    price: 40.00,
    listPrice: 49.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Nitinol-Heat-Activated-unit-of-use',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Copper nickel titanium (CuNiTi)', type: 'Heat-activated with copper', transitionTemps: '27°C, 35°C, 40°C selectable', sizes: '.014, .016, .018 round; .016x.022, .018x.025, .019x.025 rectangular', archForms: 'Natural, Ovoid, Tapered', packQuantity: '10 wires per pack', hysteresis: 'Narrow — more consistent force delivery' },
    regulatory: { fdaClearance: 'K190234', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700139', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['archwire', 'copper-NiTi', 'heat-activated', 'CuNiTi', 'consistent-force'],
    volumeBreaks: [
      { minQty: 1, price: 40.00 },
      { minQty: 25, price: 37.00, label: 'Volume' },
      { minQty: 100, price: 34.00, label: 'Bulk' },
      { minQty: 500, price: 32.00, label: 'Enterprise' },
    ],
  },
];
