// Auxiliaries — Elastics, Ligatures, Coil Springs, Chains, Hooks, and Accessories
export const auxiliaries = [
  {
    maId: 'PRD-040',
    maName: 'AlastiK C Modules – Ligature Ties',
    maDescription: 'Color-coded elastomeric ligature modules for securing archwires into bracket slots. Made from medical-grade polyurethane with consistent force decay characteristics. Available in a wide range of colors for patient engagement and compliance.',
    division: 'Auxiliaries',
    category: 'Elastomeric Ligatures',
    subcategory: 'Modules',
    sku: 'SOL-AUX-040',
    price: 18.00,
    listPrice: 22.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/C-Modules',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Medical-grade polyurethane elastomer', type: 'C-shaped ligature module', colors: '24 colors including clear and pearl', packQuantity: '1,000 modules per pack (approx. 40 sticks)', innerDiameter: '1.3 mm standard', forceDecay: '~50% over 21 days', latexFree: true },
    regulatory: { fdaClearance: 'K160567', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700140', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['elastomeric', 'ligature', 'AlastiK', 'color', 'modules'],
    volumeBreaks: [
      { minQty: 1, price: 18.00 },
      { minQty: 25, price: 17.00, label: 'Volume' },
      { minQty: 100, price: 15.00, label: 'Bulk' },
      { minQty: 500, price: 14.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-041',
    maName: 'AlastiK Easy-to-Tie Separators',
    maDescription: 'Elastomeric separators for creating interproximal space before molar band placement. The easy-to-tie design allows efficient placement with a separator placer or two lengths of dental floss. Delivers consistent separating force over 7–10 days.',
    division: 'Auxiliaries',
    category: 'Separators',
    subcategory: 'Elastomeric',
    sku: 'SOL-AUX-041',
    price: 15.00,
    listPrice: 19.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/loose-s-modules',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Medical-grade polyurethane', type: 'Elastomeric separator', colors: 'Gray, clear', packQuantity: '1,000 per pack', separatingForce: '~150 g initial', duration: '7–10 days effective separation', placement: 'Separator placer or floss technique', latexFree: true },
    regulatory: { fdaClearance: 'K160568', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700141', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['separator', 'AlastiK', 'elastomeric', 'molar-band', 'interproximal'],
    volumeBreaks: [
      { minQty: 1, price: 15.00 },
      { minQty: 25, price: 14.00, label: 'Volume' },
      { minQty: 100, price: 13.00, label: 'Bulk' },
      { minQty: 500, price: 12.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-042',
    maName: 'Ligature Wire – Stainless Steel',
    maDescription: 'Pre-cut stainless steel ligature wire for securing archwires into bracket slots in cases requiring metal ligatures. Provides maximum wire engagement and is essential for torque expression in finishing stages. Available in various gauges.',
    division: 'Auxiliaries',
    category: 'Ligatures',
    subcategory: 'Metal Wire',
    sku: 'SOL-AUX-042',
    price: 12.00,
    listPrice: 15.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/ligature-wire',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Stainless steel (soft temper)', gauges: '.010, .012 (most common)', precut: 'Yes — individual pre-cut lengths', spoolLength: '100 pre-cut lengths per spool', application: 'Full wire engagement, figure-8 ligation', temper: 'Soft — easy to twist and tie' },
    regulatory: { fdaClearance: 'K150345', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700142', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['ligature', 'stainless-steel', 'wire', 'metal', 'full-engagement'],
    volumeBreaks: [
      { minQty: 1, price: 12.00 },
      { minQty: 25, price: 11.00, label: 'Volume' },
      { minQty: 100, price: 10.00, label: 'Bulk' },
      { minQty: 500, price: 10.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-043',
    maName: 'NiTi Coil Springs – Open and Closed',
    maDescription: 'Nickel titanium coil springs delivering continuous light forces for space opening (open coil) or space closing (closed coil). Superelastic properties maintain consistent force delivery regardless of activation distance.',
    division: 'Auxiliaries',
    category: 'Coil Springs',
    subcategory: 'NiTi Springs',
    sku: 'SOL-AUX-043',
    price: 35.00,
    listPrice: 43.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Nitinol-Closed-Coil-Springs',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Superelastic nickel titanium', types: 'Open coil (space opening), Closed coil (space closing)', force: '100 g, 150 g, 200 g options', innerDiameter: '.010 x .030, .010 x .036 wire', packQuantity: '10 springs per pack', length: '12 mm relaxed (trimmable)', forceConsistency: 'Constant over 2–4 mm activation' },
    regulatory: { fdaClearance: 'K170567', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700143', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['coil-spring', 'NiTi', 'space-opening', 'space-closing', 'superelastic'],
    volumeBreaks: [
      { minQty: 1, price: 35.00 },
      { minQty: 25, price: 33.00, label: 'Volume' },
      { minQty: 100, price: 30.00, label: 'Bulk' },
      { minQty: 500, price: 28.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-044',
    maName: 'Elastic Chain – Continuous, Short, and Long',
    maDescription: 'Elastomeric power chain for space closure and tooth consolidation. Available in continuous (no gaps), short (small gaps), and long (large gaps) configurations. Color-coded for easy identification and patient customization.',
    division: 'Auxiliaries',
    category: 'Elastic Chain',
    subcategory: 'Power Chain',
    sku: 'SOL-AUX-044',
    price: 14.00,
    listPrice: 18.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/C-Modules-CK',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Medical-grade polyurethane', types: 'Continuous, Short (3.5 mm), Long (4.0 mm)', spoolLength: '15 feet per spool', colors: 'Clear, silver, gray, assorted colors', forcePerLink: '~50–100 g (depending on stretch)', forceDecay: '~40% over 21 days', latexFree: true },
    regulatory: { fdaClearance: 'K160569', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700144', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['elastic-chain', 'power-chain', 'space-closure', 'elastomeric', 'continuous'],
    volumeBreaks: [
      { minQty: 1, price: 14.00 },
      { minQty: 25, price: 13.00, label: 'Volume' },
      { minQty: 100, price: 12.00, label: 'Bulk' },
      { minQty: 500, price: 11.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-045',
    maName: 'Kobayashi Hooks',
    maDescription: 'Crimpable or ligature-tie hooks for attaching interarch elastics to orthodontic archwires. Available in various heights and configurations for Class II, Class III, and vertical elastic applications.',
    division: 'Auxiliaries',
    category: 'Hooks',
    subcategory: 'Archwire Hooks',
    sku: 'SOL-AUX-045',
    price: 22.00,
    listPrice: 27.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/390-145_OP_Leftside',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Stainless steel', type: 'Ball-hook design', heights: 'Short (3 mm), Medium (4 mm), Long (5 mm)', attachment: 'Ligature tie-on to archwire', packQuantity: '100 per pack', application: 'Interarch elastic attachment, Class II/III mechanics', compatibility: 'All rectangular and round archwires' },
    regulatory: { fdaClearance: 'K150456', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700145', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['hooks', 'kobayashi', 'elastic-attachment', 'interarch', 'ball-hook'],
    volumeBreaks: [
      { minQty: 1, price: 22.00 },
      { minQty: 25, price: 20.00, label: 'Volume' },
      { minQty: 100, price: 19.00, label: 'Bulk' },
      { minQty: 500, price: 18.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-046',
    maName: 'Power Thread',
    maDescription: 'Elastomeric thread for precise individual tooth movement and diastema closure. The continuous thread design allows custom-length cutting for any clinical situation. Delivers consistent, light forces for controlled tooth movement.',
    division: 'Auxiliaries',
    category: 'Elastic Thread',
    subcategory: 'Power Thread',
    sku: 'SOL-AUX-046',
    price: 16.00,
    listPrice: 20.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/C-Modules-C-1',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Medical-grade polyurethane thread', diameter: '0.25 mm, 0.50 mm', spoolLength: '200 yards per spool', colors: 'Clear, gray', force: '~25–75 g (depending on stretch)', application: 'Diastema closure, individual tooth movement, rotation correction', latexFree: true },
    regulatory: { fdaClearance: 'K160570', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700146', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['power-thread', 'elastomeric', 'diastema', 'tooth-movement', 'thread'],
    volumeBreaks: [
      { minQty: 1, price: 16.00 },
      { minQty: 25, price: 15.00, label: 'Volume' },
      { minQty: 100, price: 14.00, label: 'Bulk' },
      { minQty: 500, price: 13.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-047',
    maName: 'Crimpable Hooks',
    maDescription: 'Stainless steel hooks that crimp directly onto rectangular archwires for elastic attachment at any position along the arch. Provides flexible elastic anchor points without requiring hooks on brackets or soldering to archwires.',
    division: 'Auxiliaries',
    category: 'Hooks',
    subcategory: 'Crimpable',
    sku: 'SOL-AUX-047',
    price: 28.00,
    listPrice: 34.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/390-145_OP_Leftside',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Stainless steel', type: 'Crimpable (crimp-on to archwire)', hookHeight: '3 mm, 4 mm', compatibility: '.017x.025 and .019x.025 rectangular archwires', packQuantity: '50 per pack', crimpMethod: 'Weingart or bird-beak plier', application: 'Flexible elastic attachment points' },
    regulatory: { fdaClearance: 'K160571', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700147', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['crimpable', 'hooks', 'elastic-attachment', 'archwire', 'stainless-steel'],
    volumeBreaks: [
      { minQty: 1, price: 28.00 },
      { minQty: 25, price: 26.00, label: 'Volume' },
      { minQty: 100, price: 24.00, label: 'Bulk' },
      { minQty: 500, price: 22.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-048',
    maName: 'Rotation Wedges',
    maDescription: 'Small elastomeric wedges placed between the archwire and bracket slot to generate rotational force on individual teeth. Effective for correcting rotations during the leveling and alignment phase of treatment.',
    division: 'Auxiliaries',
    category: 'Rotation Correction',
    subcategory: 'Wedges',
    sku: 'SOL-AUX-048',
    price: 19.00,
    listPrice: 24.00,
    imageUrl: 'https://s7d9.scene7.com/is/image/mmmspinco/A-Modules',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Medical-grade elastomer', type: 'Triangular wedge', sizes: 'Small, Medium, Large', packQuantity: '100 per pack', application: 'Rotation correction, in-slot wedging', forceType: 'Couple force for derotation', compatibility: '.022 slot brackets with round archwires' },
    regulatory: { fdaClearance: 'K170568', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700148', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['rotation', 'wedge', 'elastomeric', 'derotation', 'alignment'],
    volumeBreaks: [
      { minQty: 1, price: 19.00 },
      { minQty: 25, price: 18.00, label: 'Volume' },
      { minQty: 100, price: 16.00, label: 'Bulk' },
      { minQty: 500, price: 15.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-049',
    maName: 'AlastiK Power Sticks',
    maDescription: 'Pre-loaded elastomeric module dispensing sticks for efficient chairside ligature placement. Each stick holds approximately 24 modules in a ready-to-place configuration, reducing fumbling and improving ergonomics during ligation.',
    division: 'Auxiliaries',
    category: 'Elastomeric Ligatures',
    subcategory: 'Dispensing',
    sku: 'SOL-AUX-049',
    price: 20.00,
    listPrice: 25.00,
    imageUrl: 'https://s7d9.scene7.com/is/image/mmmspinco/A-Modules',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Medical-grade polyurethane modules on plastic stick', modulesPerStick: '~24', sticksPerPack: '40 sticks (approx. 960 modules)', colors: '24 colors including clear and pearl', innerDiameter: '1.3 mm standard', placement: 'Direct from stick with scaler or module placer', latexFree: true },
    regulatory: { fdaClearance: 'K160572', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700149', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['AlastiK', 'power-sticks', 'ligature', 'dispensing', 'elastomeric'],
    volumeBreaks: [
      { minQty: 1, price: 20.00 },
      { minQty: 25, price: 19.00, label: 'Volume' },
      { minQty: 100, price: 17.00, label: 'Bulk' },
      { minQty: 500, price: 16.00, label: 'Enterprise' },
    ],
  },
];
