export const bands = [
  {
    maId: 'PRD-BAND-001',
    sku: 'SOL-BND-001',
    maName: 'Orthodontic Bands — First Molars',
    maDescription: 'Standard first molar bands for primary orthodontic treatment. Available in multiple sizes with configurable temper and width options.',
    division: 'Brackets & Tubes',
    category: 'Molar Bands',
    subcategory: 'First Molars',
    price: 0,
    listPrice: 0,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-molar-bands',
    isConfigurable: true,
    isBandProduct: true,
    bandTypeId: 'FirstMolars',
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    sampleEligible: false,
    specifications: {
      bandType: 'First Molars',
      positions: 'Upper Right, Upper Left, Lower Right, Lower Left',
      temperOptions: 'Regular, Hard',
      widthOptions: 'Wide, Narrow',
      sizeRange: '22 – 42 (including half sizes)',
    },
    regulatory: {
      fdaClearance: 'K210098',
      deviceClass: 'Class I',
      productCode: 'EIY',
    },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['bands', 'molar', 'first molar', 'orthodontic bands'],
  },
  {
    maId: 'PRD-BAND-002',
    sku: 'SOL-BND-002',
    maName: 'Orthodontic Bands — Second Molars',
    maDescription: 'Second molar bands for extended anchorage and molar control. Available in multiple sizes with configurable temper and width options.',
    division: 'Brackets & Tubes',
    category: 'Molar Bands',
    subcategory: 'Second Molars',
    price: 0,
    listPrice: 0,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-molar-bands',
    isConfigurable: true,
    isBandProduct: true,
    bandTypeId: 'SecondMolars',
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    sampleEligible: false,
    specifications: {
      bandType: 'Second Molars',
      positions: 'Upper Right, Upper Left, Lower Right, Lower Left',
      temperOptions: 'Regular, Hard',
      widthOptions: 'Wide, Narrow',
      sizeRange: '22 – 42 (including half sizes)',
    },
    regulatory: {
      fdaClearance: 'K210098',
      deviceClass: 'Class I',
      productCode: 'EIY',
    },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['bands', 'molar', 'second molar', 'orthodontic bands'],
  },
  {
    maId: 'PRD-BAND-003',
    sku: 'SOL-BND-003',
    maName: 'Orthodontic Bands — 1st & 2nd GP Molars (Hard)',
    maDescription: 'Hard temper molar bands for general-purpose use. Default hard temper and wide width for consistent, reliable fit.',
    division: 'Brackets & Tubes',
    category: 'Molar Bands',
    subcategory: 'General Purpose Molars',
    price: 0,
    listPrice: 0,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-molar-bands',
    isConfigurable: true,
    isBandProduct: true,
    bandTypeId: 'FirstSecondMolarsHard',
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    sampleEligible: false,
    specifications: {
      bandType: '1st & 2nd GP Molars — Hard Temper',
      positions: 'Upper, Lower',
      temper: 'Hard (default)',
      width: 'Wide (default)',
      sizeRange: '22 – 42 (including half sizes)',
    },
    regulatory: {
      fdaClearance: 'K210098',
      deviceClass: 'Class I',
      productCode: 'EIY',
    },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['bands', 'molar', 'general purpose', 'hard temper', 'orthodontic bands'],
  },
  {
    maId: 'PRD-BAND-004',
    sku: 'SOL-BND-004',
    maName: 'Orthodontic Bands — 1st & 2nd GP Molars (Regular)',
    maDescription: 'Regular temper molar bands for general-purpose orthodontic use. Configurable temper and width options.',
    division: 'Brackets & Tubes',
    category: 'Molar Bands',
    subcategory: 'General Purpose Molars',
    price: 0,
    listPrice: 0,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-molar-bands',
    isConfigurable: true,
    isBandProduct: true,
    bandTypeId: 'FirstSecondMolarsRegular',
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    sampleEligible: false,
    specifications: {
      bandType: '1st & 2nd GP Molars — Regular',
      positions: 'Upper, Lower',
      temperOptions: 'Regular, Hard',
      widthOptions: 'Wide, Narrow',
      sizeRange: '22 – 42 (including half sizes)',
    },
    regulatory: {
      fdaClearance: 'K210098',
      deviceClass: 'Class I',
      productCode: 'EIY',
    },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['bands', 'molar', 'general purpose', 'regular temper', 'orthodontic bands'],
  },
  {
    maId: 'PRD-BAND-005',
    sku: 'SOL-BND-005',
    maName: 'Orthodontic Bands — 1st & 2nd GP Molars (Pedodontic)',
    maDescription: 'Smaller pedodontic bands designed for pediatric patients. Default regular temper and narrow width.',
    division: 'Brackets & Tubes',
    category: 'Molar Bands',
    subcategory: 'General Purpose Molars',
    price: 0,
    listPrice: 0,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-pedodontic-molar-bands',
    isConfigurable: true,
    isBandProduct: true,
    bandTypeId: 'FirstSecondMolarsPedo',
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    sampleEligible: false,
    specifications: {
      bandType: '1st & 2nd GP Molars — Pedodontic',
      positions: 'Upper, Lower',
      temper: 'Regular (default)',
      width: 'Narrow (default)',
      sizeRange: '22 – 42 (including half sizes)',
    },
    regulatory: {
      fdaClearance: 'K210098',
      deviceClass: 'Class I',
      productCode: 'EIY',
    },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['bands', 'molar', 'pedodontic', 'pediatric', 'orthodontic bands'],
  },
  {
    maId: 'PRD-BAND-006',
    sku: 'SOL-BND-006',
    maName: 'Orthodontic Bands — Proportional Bicuspids',
    maDescription: 'Proportionally sized bicuspid bands for accurate anatomical fit across upper and lower arches.',
    division: 'Brackets & Tubes',
    category: 'Bicuspid Bands',
    subcategory: 'Proportional',
    price: 0,
    listPrice: 0,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-bicuspid-bands-narrow',
    isConfigurable: true,
    isBandProduct: true,
    bandTypeId: 'ProportionalBicuspids',
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    sampleEligible: false,
    specifications: {
      bandType: 'Proportional Bicuspids',
      positions: 'Upper, Lower',
      sizeRange: '22 – 42 (including half sizes)',
    },
    regulatory: {
      fdaClearance: 'K210098',
      deviceClass: 'Class I',
      productCode: 'EIY',
    },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['bands', 'bicuspid', 'proportional', 'orthodontic bands'],
  },
  {
    maId: 'PRD-BAND-007',
    sku: 'SOL-BND-007',
    maName: 'Orthodontic Bands — General Purpose Bicuspids',
    maDescription: 'Versatile bicuspid bands with right/left positioning and configurable width options.',
    division: 'Brackets & Tubes',
    category: 'Bicuspid Bands',
    subcategory: 'General Purpose',
    price: 0,
    listPrice: 0,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-bicuspid-bands-narrow',
    isConfigurable: true,
    isBandProduct: true,
    bandTypeId: 'GeneralPurposeBicuspids',
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    sampleEligible: false,
    specifications: {
      bandType: 'General Purpose Bicuspids',
      positions: 'Upper Right, Upper Left, Lower Right, Lower Left',
      widthOptions: 'Wide, Narrow',
      sizeRange: '22 – 42 (including half sizes)',
    },
    regulatory: {
      fdaClearance: 'K210098',
      deviceClass: 'Class I',
      productCode: 'EIY',
    },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['bands', 'bicuspid', 'general purpose', 'orthodontic bands'],
  },
  {
    maId: 'PRD-BAND-008',
    sku: 'SOL-BND-008',
    maName: 'Orthodontic Bands — Contoured Bicuspids',
    maDescription: 'Anatomically contoured bicuspid bands for enhanced fit and patient comfort.',
    division: 'Brackets & Tubes',
    category: 'Bicuspid Bands',
    subcategory: 'Contoured',
    price: 0,
    listPrice: 0,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-bicuspid-bands-narrow',
    isConfigurable: true,
    isBandProduct: true,
    bandTypeId: 'ContouredBicuspids',
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    sampleEligible: false,
    specifications: {
      bandType: 'Contoured Bicuspids',
      positions: 'Upper, Lower',
      sizeRange: '22 – 42 (including half sizes)',
    },
    regulatory: {
      fdaClearance: 'K210098',
      deviceClass: 'Class I',
      productCode: 'EIY',
    },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    tags: ['bands', 'bicuspid', 'contoured', 'orthodontic bands'],
  },
];
