// Bonding — Adhesives, Primers, Cements for Orthodontic Bonding
export const bonding = [
  {
    maId: 'PRD-016',
    maName: 'Transbond XT Light Cure Adhesive',
    maDescription: 'The industry-standard light-curable orthodontic adhesive paste for direct bracket bonding. Provides high bond strength with minimal bracket drift during placement. Optimized viscosity allows easy dispensing while maintaining bracket position prior to curing.',
    division: 'Bonding',
    category: 'Adhesives',
    subcategory: 'Light Cure',
    sku: 'SOL-BND-016',
    price: 95.00,
    listPrice: 115.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/712_035',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { type: 'Light-curable paste', cureTime: '10 seconds per bracket (high-intensity LED)', bondStrength: '18–24 MPa (enamel)', viscosity: 'Medium paste', packaging: '4 g syringe', shelfLife: '24 months', lightWavelength: '400–515 nm' },
    regulatory: { fdaClearance: 'K170234', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700116', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['adhesive', 'transbond', 'light-cure', 'bonding', 'bracket-bonding'],
  },
  {
    maId: 'PRD-017',
    maName: 'Transbond XT Adhesive Primer',
    maDescription: 'Light-curable primer designed for use with Transbond XT adhesive. Provides a thin, uniform coating that enhances bond strength between etched enamel and the adhesive paste. Compatible with phosphoric acid and self-etching primer workflows.',
    division: 'Bonding',
    category: 'Primers',
    subcategory: 'Light Cure Primer',
    sku: 'SOL-BND-017',
    price: 42.00,
    listPrice: 52.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/712-034_02_ip_center',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { type: 'Light-curable unfilled resin primer', volume: '6 mL bottle', application: 'Thin coat with micro-brush', cureTime: '10 seconds', compatibility: 'Transbond XT, Transbond Plus, phosphoric acid etch', shelfLife: '18 months' },
    regulatory: { fdaClearance: 'K170235', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700117', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['primer', 'transbond', 'light-cure', 'bonding', 'enamel'],
  },
  {
    maId: 'PRD-018',
    maName: 'Transbond Plus Self-Etching Primer',
    maDescription: 'Combined self-etching and priming system that eliminates the separate acid etch step in bracket bonding. Reduces bonding steps from four to two, decreasing chair time and moisture sensitivity while maintaining clinically proven bond strength.',
    division: 'Bonding',
    category: 'Primers',
    subcategory: 'Self-Etching',
    sku: 'SOL-BND-018',
    price: 185.00,
    listPrice: 220.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/TransbondSelfEtchingPrimer_OP',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { type: 'Self-etching primer (SEP)', packQuantity: '50 unit-dose applicators per kit', steps: '2-step bonding (apply SEP, place bracket)', bondStrength: '14–20 MPa', moistureTolerance: 'Moderate', shelfLife: '18 months', activation: 'Squeeze to mix internal compartments' },
    regulatory: { fdaClearance: 'K190567', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700118', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['primer', 'self-etching', 'transbond-plus', 'bonding', 'simplified'],
  },
  {
    maId: 'PRD-019',
    maName: 'Transbond MIP Moisture-Insensitive Primer',
    maDescription: 'Hydrophilic primer formulated for reliable bonding in moisture-contaminated environments. Ideal for bonding second molars, impacted teeth, and cases where isolation is difficult. Provides consistent bond strength even in the presence of saliva.',
    division: 'Bonding',
    category: 'Primers',
    subcategory: 'Moisture-Insensitive',
    sku: 'SOL-BND-019',
    price: 52.00,
    listPrice: 64.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/712-025_02_ip_rightside',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { type: 'Hydrophilic light-cure primer', volume: '5 mL bottle', application: 'Thin coat on etched and contaminated enamel', moistureTolerance: 'High — bonds through saliva contamination', cureTime: '10 seconds', shelfLife: '18 months' },
    regulatory: { fdaClearance: 'K200123', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700119', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['primer', 'moisture-insensitive', 'transbond-MIP', 'saliva-tolerant', 'bonding'],
  },
  {
    maId: 'PRD-020',
    maName: 'APC Flash-Free Adhesive Coated Appliance System',
    maDescription: 'Pre-coated adhesive system applied to brackets at the factory, eliminating chairside adhesive dispensing. The proprietary adhesive flows from the center of the bracket pad outward upon placement, creating virtually zero flash for reduced cleanup time.',
    division: 'Bonding',
    category: 'Adhesives',
    subcategory: 'Pre-Coated System',
    sku: 'SOL-BND-020',
    price: 280.00,
    listPrice: 335.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity_Advanced_Bracket_APC_Blister_Tweezers',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { type: 'Factory-applied light-cure adhesive', cureTime: '6 seconds (high-intensity LED)', bondStrength: '16–22 MPa', flashCleanup: 'Virtually none', compatibility: 'Victory Series, Clarity Advanced, Clarity Ultra brackets', packaging: 'Individually packaged brackets with adhesive', cureWavelength: '400–515 nm' },
    regulatory: { fdaClearance: 'K210345', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700120', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['APC', 'flash-free', 'pre-coated', 'adhesive', 'bonding-system'],
  },
  {
    maId: 'PRD-021',
    maName: 'Sondhi Rapid-Set Indirect Bonding Adhesive',
    maDescription: 'Dual-cure adhesive specifically formulated for indirect bonding technique. The rapid-set chemistry allows for tray removal in under two minutes while providing bond strengths comparable to direct bonding with Transbond XT.',
    division: 'Bonding',
    category: 'Adhesives',
    subcategory: 'Indirect Bonding',
    sku: 'SOL-BND-021',
    price: 165.00,
    listPrice: 198.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Sondhi-Kit',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { type: 'Dual-cure (light + chemical) adhesive', setTime: '<2 minutes for tray removal', bondStrength: '15–20 MPa', components: 'Base paste + catalyst paste', packaging: '2 x 3 g syringes per kit', technique: 'Indirect bonding with custom tray', shelfLife: '18 months' },
    regulatory: { fdaClearance: 'K190678', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700121', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['adhesive', 'indirect-bonding', 'sondhi', 'rapid-set', 'dual-cure'],
  },
  {
    maId: 'PRD-022',
    maName: 'Concise Light Cured Adhesive',
    maDescription: 'Versatile light-curable adhesive for bonding orthodontic attachments, buttons, and lingual retainers. Higher viscosity formula prevents flow-off during placement on lingual surfaces and provides strong bond to both enamel and metal.',
    division: 'Bonding',
    category: 'Adhesives',
    subcategory: 'Multi-Purpose',
    sku: 'SOL-BND-022',
    price: 78.00,
    listPrice: 95.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/712_035',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { type: 'Light-curable filled adhesive', cureTime: '20 seconds', viscosity: 'High — non-slump', bondStrength: '12–18 MPa', packaging: '5 g syringe', applications: 'Buttons, lingual retainers, attachments', shelfLife: '24 months' },
    regulatory: { fdaClearance: 'K180345', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700122', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['adhesive', 'concise', 'light-cure', 'multi-purpose', 'retainer-bonding'],
  },
  {
    maId: 'PRD-023',
    maName: 'RelyX Unicem 2 – Ortho Applications',
    maDescription: 'Self-adhesive resin cement adapted for orthodontic band cementation and indirect bonding applications. Provides strong adhesion to enamel and metal without separate etching or priming steps, simplifying the cementation workflow.',
    division: 'Bonding',
    category: 'Cements',
    subcategory: 'Resin Cement',
    sku: 'SOL-BND-023',
    price: 195.00,
    listPrice: 235.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/rxu2-family-whi-clip',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { type: 'Self-adhesive dual-cure resin cement', cureTime: '20 seconds light cure or 6 minutes self-cure', bondStrength: '20–25 MPa (enamel)', packaging: '8.5 g automix syringe', application: 'Band cementation, indirect bonding', fluorideRelease: 'Yes', shelfLife: '24 months' },
    regulatory: { fdaClearance: 'K200567', deviceClass: 'Class II', productCode: 'LSE', gudid: '00707387700123', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['cement', 'relyX', 'self-adhesive', 'band-cementation', 'resin'],
  },
  {
    maId: 'PRD-024',
    maName: 'Clarity Attachment Material',
    maDescription: 'Light-curable composite material specifically designed for fabricating Clarity Aligner attachments. Tooth-colored formulation blends with enamel for aesthetic aligner treatment. Optimized for attachment templates with clean removal at debond.',
    division: 'Bonding',
    category: 'Adhesives',
    subcategory: 'Aligner Attachments',
    sku: 'SOL-BND-024',
    price: 125.00,
    listPrice: 150.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/ocsd-clarity-attachment-material-01-ds-os-en',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { type: 'Light-curable composite attachment material', cureTime: '10 seconds per attachment', shades: 'A1, A2, A3', packaging: '3 g syringe', application: 'Clarity Aligner precision attachments', removal: 'Clean debond with carbide bur', shelfLife: '18 months' },
    regulatory: { fdaClearance: 'K210678', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700124', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['attachment', 'clarity', 'aligner', 'composite', 'aesthetic'],
  },
  {
    maId: 'PRD-025',
    maName: 'Transbond IDB Pre-Mix Chemical Cure',
    maDescription: 'Chemically cured adhesive for indirect bonding technique, eliminating the need for a curing light during tray seating. Provides extended working time for full-arch tray placement with reliable bond strength after chemical set.',
    division: 'Bonding',
    category: 'Adhesives',
    subcategory: 'Chemical Cure',
    sku: 'SOL-BND-025',
    price: 88.00,
    listPrice: 108.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/hcbgeqb000017_01Center',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { type: 'Chemical-cure pre-mixed adhesive', workingTime: '3–4 minutes', setTime: '5–6 minutes from placement', bondStrength: '14–18 MPa', packaging: '5 g syringe', technique: 'Indirect bonding (no light required)', shelfLife: '12 months (refrigerated)' },
    regulatory: { fdaClearance: 'K190789', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700125', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['adhesive', 'chemical-cure', 'indirect-bonding', 'transbond-IDB', 'no-light'],
  },
];
