// Brackets & Tubes — Ceramic, Metal, Self-Ligating, Buccal Tubes, Molar Bands
export const brackets = [
  {
    maId: 'PRD-001',
    maName: 'Clarity Advanced Ceramic Brackets – Upper Kit',
    maDescription: 'Translucent ceramic brackets designed for the upper arch with a low profile and smooth contours. Features a precision slot for accurate tooth movement and an APC Flash-Free adhesive option. The advanced alumina construction resists staining throughout treatment.',
    division: 'Brackets & Tubes',
    category: 'Ceramic Brackets',
    subcategory: 'Upper Arch',
    sku: 'SOL-CBR-001',
    price: 385.00,
    listPrice: 450.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity_Advanced_Upper_Cuspid_Hook',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Translucent polycrystalline alumina', slotSize: '.022 MBT / Roth', torqueOptions: 'Standard, High, Low', archCoverage: 'Upper 5-5', bracketCount: '10 per kit', profile: 'Low profile', hookOptions: 'With or without hooks on 3s, 4s, 5s' },
    regulatory: { fdaClearance: 'K220145', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700101', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['ceramic', 'brackets', 'clarity', 'aesthetic', 'upper-arch', 'MBT'],
  },
  {
    maId: 'PRD-002',
    maName: 'Clarity Advanced Ceramic Brackets – Lower Kit',
    maDescription: 'Translucent ceramic brackets designed for the lower arch with optimized pad geometry for reliable bond strength on smaller tooth surfaces. Precision-machined slot ensures consistent archwire engagement and efficient force delivery.',
    division: 'Brackets & Tubes',
    category: 'Ceramic Brackets',
    subcategory: 'Lower Arch',
    sku: 'SOL-CBR-002',
    price: 375.00,
    listPrice: 440.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity_Advanced_Upper_Cuspid_Hook',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Translucent polycrystalline alumina', slotSize: '.022 MBT / Roth', torqueOptions: 'Standard, High, Low', archCoverage: 'Lower 5-5', bracketCount: '10 per kit', profile: 'Low profile', hookOptions: 'With or without hooks on 3s, 4s, 5s' },
    regulatory: { fdaClearance: 'K220146', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700102', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['ceramic', 'brackets', 'clarity', 'aesthetic', 'lower-arch', 'MBT'],
  },
  {
    maId: 'PRD-003',
    maName: 'Clarity Ultra Self-Ligating Brackets – Upper Kit',
    maDescription: 'Self-ligating ceramic brackets combining aesthetic translucency with a unique slide mechanism for efficient wire engagement. The nickel-free stainless steel clip provides reliable opening and closing with reduced chair time. Designed for the upper arch.',
    division: 'Brackets & Tubes',
    category: 'Self-Ligating Brackets',
    subcategory: 'Ceramic Self-Ligating',
    sku: 'SOL-CBR-003',
    price: 420.00,
    listPrice: 495.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity-Ultra-Self-ligating-Bracket_Closed_Retouch',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Translucent polycrystalline alumina with SS clip', slotSize: '.022 MBT', mechanism: 'Passive self-ligating slide', archCoverage: 'Upper 5-5', bracketCount: '10 per kit', clipMaterial: 'Nickel-free stainless steel', rotationControl: 'Enhanced pad geometry' },
    regulatory: { fdaClearance: 'K210567', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700103', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['ceramic', 'self-ligating', 'clarity-ultra', 'aesthetic', 'upper-arch'],
  },
  {
    maId: 'PRD-004',
    maName: 'Clarity Ultra Self-Ligating Brackets – Lower Kit',
    maDescription: 'Self-ligating ceramic brackets for the lower arch featuring a smooth, low-profile design. The passive slide mechanism reduces friction during leveling and alignment while providing full archwire control during finishing.',
    division: 'Brackets & Tubes',
    category: 'Self-Ligating Brackets',
    subcategory: 'Ceramic Self-Ligating',
    sku: 'SOL-CBR-004',
    price: 415.00,
    listPrice: 490.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity-Ultra-Self-ligating-Bracket_Closed_Retouch',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Translucent polycrystalline alumina with SS clip', slotSize: '.022 MBT', mechanism: 'Passive self-ligating slide', archCoverage: 'Lower 5-5', bracketCount: '10 per kit', clipMaterial: 'Nickel-free stainless steel', rotationControl: 'Enhanced pad geometry' },
    regulatory: { fdaClearance: 'K210568', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700104', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['ceramic', 'self-ligating', 'clarity-ultra', 'aesthetic', 'lower-arch'],
  },
  {
    maId: 'PRD-005',
    maName: 'Victory Series Metal Brackets – Standard',
    maDescription: 'Time-tested stainless steel twin brackets featuring a smooth, rounded design for patient comfort. Precision-machined slot with micro-etched base provides consistent bond strength and accurate bracket placement across all tooth types.',
    division: 'Brackets & Tubes',
    category: 'Metal Brackets',
    subcategory: 'Twin Brackets',
    sku: 'SOL-MBR-005',
    price: 180.00,
    listPrice: 215.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Victory-Series-Bracket',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: '17-4 PH stainless steel', slotSize: '.022 MBT / Roth', profile: 'Standard', archCoverage: '5-5', bracketCount: '10 per kit', base: 'Micro-etched 80-gauge mesh', wingDesign: 'Rhomboidal twin' },
    regulatory: { fdaClearance: 'K180234', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700105', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['metal', 'brackets', 'victory', 'twin', 'standard', 'MBT'],
  },
  {
    maId: 'PRD-006',
    maName: 'Victory Series Metal Brackets – Small',
    maDescription: 'Smaller-profile version of the Victory Series designed for patients with smaller teeth or mixed dentition cases. Maintains the same precision slot and micro-etched base as the standard size.',
    division: 'Brackets & Tubes',
    category: 'Metal Brackets',
    subcategory: 'Twin Brackets',
    sku: 'SOL-MBR-006',
    price: 182.00,
    listPrice: 218.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Victory-Series-Bracket',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: '17-4 PH stainless steel', slotSize: '.022 MBT / Roth', profile: 'Small', archCoverage: '5-5', bracketCount: '10 per kit', base: 'Micro-etched 80-gauge mesh', wingDesign: 'Rhomboidal twin' },
    regulatory: { fdaClearance: 'K180235', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700106', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['metal', 'brackets', 'victory', 'twin', 'small'],
  },
  {
    maId: 'PRD-007',
    maName: 'Victory Series Low Profile Brackets',
    maDescription: 'Ultra-low-profile version of the Victory Series for reduced interference with occlusion and improved patient comfort. Ideal for lower anteriors and cases requiring minimal bracket prominence.',
    division: 'Brackets & Tubes',
    category: 'Metal Brackets',
    subcategory: 'Low Profile',
    sku: 'SOL-MBR-007',
    price: 192.00,
    listPrice: 228.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/VSLP_Anterior_mandibular',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: '17-4 PH stainless steel', slotSize: '.022 MBT / Roth', profile: 'Ultra-low', archCoverage: '5-5', bracketCount: '10 per kit', base: 'Micro-etched 80-gauge mesh', occlusalClearance: 'Enhanced' },
    regulatory: { fdaClearance: 'K180236', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700107', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['metal', 'brackets', 'victory', 'low-profile', 'anterior'],
  },
  {
    maId: 'PRD-008',
    maName: 'SmartClip SL3 Self-Ligating Brackets',
    maDescription: 'Metal self-ligating bracket system with a passive clip mechanism that allows for low-friction wire sliding during initial alignment and active engagement during finishing. The NiTi clip design provides consistent opening and closing forces.',
    division: 'Brackets & Tubes',
    category: 'Self-Ligating Brackets',
    subcategory: 'Metal Self-Ligating',
    sku: 'SOL-SLB-008',
    price: 350.00,
    listPrice: 415.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/SmartClipBracket',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: '17-4 PH stainless steel', clipMaterial: 'Nickel titanium', slotSize: '.022 MBT', mechanism: 'Passive-to-active NiTi clip', archCoverage: '5-5', bracketCount: '10 per kit', frictionProfile: 'Progressive engagement' },
    regulatory: { fdaClearance: 'K200345', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700108', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['metal', 'self-ligating', 'smartclip', 'NiTi-clip', 'low-friction'],
  },
  {
    maId: 'PRD-009',
    maName: 'Mini Uni-Twin Brackets',
    maDescription: 'Compact single-wing metal brackets providing a minimalist profile for improved patient comfort and oral hygiene access. Ideal for bonding in tight spaces and reducing bracket-to-bracket interference in crowded arches.',
    division: 'Brackets & Tubes',
    category: 'Metal Brackets',
    subcategory: 'Mini Brackets',
    sku: 'SOL-MBR-009',
    price: 148.00,
    listPrice: 178.00,
    imageUrl: 'https://s7d9.scene7.com/is/image/mmmspinco/Mini-Uni-Twin2',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: '17-4 PH stainless steel', slotSize: '.022 MBT / Roth', profile: 'Mini', archCoverage: '5-5', bracketCount: '10 per kit', base: 'Micro-etched contoured', wingDesign: 'Uni-Twin single wing' },
    regulatory: { fdaClearance: 'K190123', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700109', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['metal', 'brackets', 'mini', 'uni-twin', 'compact'],
  },
  {
    maId: 'PRD-010',
    maName: 'APC Flash-Free Pre-Coated Victory Brackets',
    maDescription: 'Victory Series brackets pre-coated with APC Flash-Free adhesive for a streamlined bonding workflow. The adhesive flows toward the center upon bracket placement, virtually eliminating flash cleanup and reducing chair time.',
    division: 'Brackets & Tubes',
    category: 'Metal Brackets',
    subcategory: 'Pre-Coated',
    sku: 'SOL-APC-010',
    price: 212.00,
    listPrice: 252.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/CADV-APC_FFr-on-tweezers-sq',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: '17-4 PH stainless steel', slotSize: '.022 MBT / Roth', adhesive: 'APC Flash-Free pre-coated', archCoverage: '5-5', bracketCount: '10 per kit', cureType: 'Light cure', cleanupTime: 'Virtually zero flash removal' },
    regulatory: { fdaClearance: 'K210234', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700110', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['metal', 'brackets', 'APC', 'flash-free', 'pre-coated', 'victory'],
  },
  {
    maId: 'PRD-011',
    maName: 'Bondable Buccal Tubes – 1st Molar',
    maDescription: 'Direct-bond buccal tubes for first molars featuring a contoured base for optimal adaptation to molar anatomy. Available in convertible and non-convertible options with single or dual tube configurations.',
    division: 'Brackets & Tubes',
    category: 'Buccal Tubes',
    subcategory: '1st Molar',
    sku: 'SOL-BTB-011',
    price: 85.00,
    listPrice: 102.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Victory-Series-Buccal-Tube2',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Stainless steel', slotSize: '.022', tubeType: 'Single or dual', toothPosition: '1st Molar (U6, L6)', packQuantity: '10 per pack (5 pairs)', base: 'Contoured micro-etched mesh', options: 'Convertible, non-convertible' },
    regulatory: { fdaClearance: 'K190456', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700111', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['buccal-tube', 'molar', 'bondable', '1st-molar', 'convertible'],
  },
  {
    maId: 'PRD-012',
    maName: 'Bondable Buccal Tubes – 2nd Molar',
    maDescription: 'Direct-bond buccal tubes specifically designed for second molars with a narrower profile and adapted base contour. Ideal for non-extraction cases requiring second molar control.',
    division: 'Brackets & Tubes',
    category: 'Buccal Tubes',
    subcategory: '2nd Molar',
    sku: 'SOL-BTB-012',
    price: 82.00,
    listPrice: 98.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Victory-Series-Superior-Fit-Buccal-Tubes',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Stainless steel', slotSize: '.022', tubeType: 'Single', toothPosition: '2nd Molar (U7, L7)', packQuantity: '10 per pack (5 pairs)', base: 'Contoured micro-etched mesh', profile: 'Narrow' },
    regulatory: { fdaClearance: 'K190457', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700112', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['buccal-tube', 'molar', 'bondable', '2nd-molar'],
  },
  {
    maId: 'PRD-013',
    maName: 'Molar Bands – 1st Molar Assortment',
    maDescription: 'Pre-welded molar bands for first molars available in a comprehensive size assortment. Features a smooth internal surface for patient comfort and pre-welded buccal tube and lingual cleat attachments.',
    division: 'Brackets & Tubes',
    category: 'Molar Bands',
    subcategory: '1st Molar',
    sku: 'SOL-MBD-013',
    price: 65.00,
    listPrice: 78.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-molar-bands',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Stainless steel', sizeRange: '16.5–40.5 (Roth numbering)', packQuantity: '10 bands per size', toothPosition: '1st Molar (U6, L6)', attachments: 'Pre-welded buccal tube and lingual cleat', finish: 'Smooth internal surface' },
    regulatory: { fdaClearance: 'K180567', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700113', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['molar-band', '1st-molar', 'pre-welded', 'stainless-steel'],
  },
  {
    maId: 'PRD-014',
    maName: 'Molar Bands – 2nd Molar Assortment',
    maDescription: 'Pre-welded molar bands for second molars in a range of sizes. Designed with a narrower occluso-gingival width for adaptation to second molar anatomy and reduced occlusal interference.',
    division: 'Brackets & Tubes',
    category: 'Molar Bands',
    subcategory: '2nd Molar',
    sku: 'SOL-MBD-014',
    price: 62.00,
    listPrice: 74.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/unitek-general-purpose-molar-bands',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Stainless steel', sizeRange: '16.5–38.5 (Roth numbering)', packQuantity: '10 bands per size', toothPosition: '2nd Molar (U7, L7)', attachments: 'Pre-welded single buccal tube and lingual cleat', finish: 'Smooth internal surface', width: 'Narrow profile' },
    regulatory: { fdaClearance: 'K180568', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700114', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['molar-band', '2nd-molar', 'pre-welded', 'narrow'],
  },
  {
    maId: 'PRD-015',
    maName: 'Mini Diamond Twin Brackets',
    maDescription: 'Precision mini twin brackets with a diamond-shaped pad design for enhanced rotational control. The compact profile improves patient comfort while the micro-etched base ensures reliable bond strength on all tooth surfaces.',
    division: 'Brackets & Tubes',
    category: 'Metal Brackets',
    subcategory: 'Mini Brackets',
    sku: 'SOL-MBR-015',
    price: 162.00,
    listPrice: 195.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/017_209',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: '17-4 PH stainless steel', slotSize: '.022 MBT / Roth', profile: 'Mini', archCoverage: '5-5', bracketCount: '10 per kit', base: 'Diamond-shaped micro-etched', wingDesign: 'Mini twin with tie-wing undercuts' },
    regulatory: { fdaClearance: 'K200456', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700115', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['metal', 'brackets', 'mini-diamond', 'twin', 'rotational-control'],
  },
];
