// Clarity Aligners — Clear Aligner Systems, Digital Solutions, and Clarity Bracket Systems
export const clarity = [
  {
    maId: 'PRD-026',
    maName: 'Clarity Aligners Starter Kit',
    maDescription: 'Comprehensive clear aligner treatment system for mild to complex orthodontic cases. Includes initial aligners, mid-course correction capability, and refinement stages. Powered by digital treatment planning with 3M proprietary tooth movement algorithms.',
    division: 'Clarity Aligners',
    category: 'Clear Aligners',
    subcategory: 'Full Treatment',
    sku: 'SOL-CLR-026',
    price: 2400.00,
    listPrice: 2850.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity-Aligners-Product-Photo_Top_White_Top',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { material: 'Multi-layer SmartTrack-equivalent polymer', stages: 'Up to 52 aligners per arch', wearSchedule: '22 hours/day, 1–2 week changes', caseTypes: 'Class I, II, III malocclusions', refinements: 'Up to 3 included refinement rounds', trimLine: 'Scalloped gingival', retention: 'Retainer stage included', digitalPlanning: '3D ClinCheck-style treatment simulation' },
    regulatory: { fdaClearance: 'K210890', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700126', mdsrCompliant: true },
    availability: 'Made to Order',
    leadTimeDays: 14,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['aligner', 'clarity', 'clear-aligner', 'digital', 'full-treatment'],
    volumeBreaks: [
      { minQty: 1, price: 2400.00 },
      { minQty: 5, price: 2270.00, label: 'Volume' },
      { minQty: 20, price: 2140.00, label: 'Bulk' },
      { minQty: 50, price: 1920.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-027',
    maName: 'Clarity Aligners Retainer Kit',
    maDescription: 'Post-treatment retention aligners for maintaining orthodontic results after active Clarity Aligner treatment. Fabricated from durable clear polymer with enhanced stain resistance for long-term wear. Includes multiple sets for replacement scheduling.',
    division: 'Clarity Aligners',
    category: 'Clear Aligners',
    subcategory: 'Retainers',
    sku: 'SOL-CLR-027',
    price: 450.00,
    listPrice: 540.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/3m-clarity-aligners-force-original-di-water-op-rightside-green-ds-os-en',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { material: 'Durable clear retention polymer', setsIncluded: '4 sets (upper and lower)', wearSchedule: 'Full-time for 3 months, then nightly', stainResistance: 'Enhanced anti-discoloration coating', trimLine: 'Scalloped gingival', replacementSchedule: 'Every 6 months recommended' },
    regulatory: { fdaClearance: 'K210891', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700127', mdsrCompliant: true },
    availability: 'Made to Order',
    leadTimeDays: 10,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['retainer', 'clarity', 'clear', 'retention', 'post-treatment'],
    volumeBreaks: [
      { minQty: 1, price: 450.00 },
      { minQty: 10, price: 419.00, label: 'Volume' },
      { minQty: 50, price: 387.00, label: 'Bulk' },
      { minQty: 100, price: 360.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-028',
    maName: 'Clarity Advanced Ceramic Brackets System – Full Arch Kit',
    maDescription: 'Complete upper and lower arch kit of Clarity Advanced translucent ceramic brackets. Provides a full aesthetic bracket setup with optimized torque prescriptions for comprehensive orthodontic treatment. Includes all brackets from cuspid to cuspid plus premolars.',
    division: 'Clarity Aligners',
    category: 'Ceramic Bracket Systems',
    subcategory: 'Full Arch',
    sku: 'SOL-CLR-028',
    price: 520.00,
    listPrice: 620.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity_Advanced_Upper_Cuspid_Hook',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Translucent polycrystalline alumina', slotSize: '.022 MBT', archCoverage: 'Full upper and lower (5-5)', bracketCount: '20 brackets', prescription: 'MBT with optimized torque values', hookOptions: '3s, 4s, 5s hook options included', adhesive: 'Compatible with APC Flash-Free' },
    regulatory: { fdaClearance: 'K220147', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700128', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['ceramic', 'clarity-advanced', 'full-arch', 'aesthetic', 'bracket-system'],
    volumeBreaks: [
      { minQty: 1, price: 520.00 },
      { minQty: 10, price: 484.00, label: 'Volume' },
      { minQty: 50, price: 447.00, label: 'Bulk' },
      { minQty: 100, price: 416.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-029',
    maName: 'Clarity Ultra SL Self-Ligating System – Full Arch Kit',
    maDescription: 'Complete self-ligating ceramic bracket system for upper and lower arches. Combines the aesthetic benefits of Clarity ceramics with the efficiency of passive self-ligation for reduced chair time and improved patient comfort throughout treatment.',
    division: 'Clarity Aligners',
    category: 'Ceramic Bracket Systems',
    subcategory: 'Self-Ligating Full Arch',
    sku: 'SOL-CLR-029',
    price: 580.00,
    listPrice: 690.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity-Ultra-Self-ligating-Bracket_Closed_Retouch',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Translucent polycrystalline alumina with NiTi-free SS clip', slotSize: '.022 MBT', mechanism: 'Passive self-ligating slide', archCoverage: 'Full upper and lower (5-5)', bracketCount: '20 brackets', clipMaterial: 'Nickel-free stainless steel', chairTimeReduction: 'Up to 24% vs ligated systems' },
    regulatory: { fdaClearance: 'K210569', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700129', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['ceramic', 'clarity-ultra', 'self-ligating', 'full-arch', 'aesthetic'],
    volumeBreaks: [
      { minQty: 1, price: 580.00 },
      { minQty: 10, price: 539.00, label: 'Volume' },
      { minQty: 50, price: 499.00, label: 'Bulk' },
      { minQty: 100, price: 464.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-030',
    maName: 'Clarity Precision Grip Attachments Kit',
    maDescription: 'Precision template system for placing optimized attachments during Clarity Aligner treatment. Includes attachment templates, composite material, and placement guides for achieving predictable tooth movements with clear aligners.',
    division: 'Clarity Aligners',
    category: 'Aligner Accessories',
    subcategory: 'Attachments',
    sku: 'SOL-CLR-030',
    price: 320.00,
    listPrice: 385.00,
    imageUrl: 'https://s7d9.scene7.com/is/image/mmmspinco/clarity-precision-grip-attachments-upper-prod-render-3-4-ds-css-charcoal-ds-os-en',
    isConfigurable: true,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { components: 'Attachment templates, composite syringes, placement guides', attachmentTypes: 'Rectangular, beveled, ellipsoid, optimized', compositeMaterial: 'Tooth-colored light-cure composite', templateMaterial: 'Rigid clear thermoformed polymer', kitContents: '10 template sets with 3 g composite', compatibility: 'Clarity Aligners treatment plans' },
    regulatory: { fdaClearance: 'K210892', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700130', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['attachments', 'clarity', 'aligner', 'precision', 'templates'],
    volumeBreaks: [
      { minQty: 1, price: 320.00 },
      { minQty: 10, price: 298.00, label: 'Volume' },
      { minQty: 50, price: 275.00, label: 'Bulk' },
      { minQty: 100, price: 256.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-031',
    maName: 'Clarity Digital Bonding Solution',
    maDescription: 'End-to-end digital workflow for indirect bonding of Clarity brackets. Includes digital bracket placement planning software, custom 3D-printed transfer trays, and all bonding materials for a fully guided bracket placement experience.',
    division: 'Clarity Aligners',
    category: 'Digital Solutions',
    subcategory: 'Indirect Bonding',
    sku: 'SOL-CLR-031',
    price: 1800.00,
    listPrice: 2150.00,
    imageUrl: 'https://s7d9.scene7.com/is/image/mmmspinco/digital-bonding-tray-prod-render-in-action-rgb-ds-css-charcoal-ds-os-en',
    isConfigurable: true,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: true,
    specifications: { components: 'Digital planning software, 3D-printed transfer trays, bonding materials', planning: 'Virtual bracket positioning with torque/angulation preview', trayMaterial: '3D-printed biocompatible resin', accuracy: '±0.1 mm bracket position, ±1° torque', workflow: 'Scan → Plan → Print → Bond', turnaroundTime: '5–7 business days from scan submission', compatibility: 'Clarity Advanced, Clarity Ultra brackets' },
    regulatory: { fdaClearance: 'K220234', deviceClass: 'Class I', productCode: 'EIY', gudid: '00707387700131', mdsrCompliant: true },
    availability: 'Made to Order',
    leadTimeDays: 7,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['digital', 'indirect-bonding', 'clarity', '3D-printed', 'workflow'],
    volumeBreaks: [
      { minQty: 1, price: 1800.00 },
      { minQty: 5, price: 1700.00, label: 'Volume' },
      { minQty: 20, price: 1600.00, label: 'Bulk' },
      { minQty: 50, price: 1440.00, label: 'Enterprise' },
    ],
  },
];
