// Instruments — Orthodontic Pliers, Forceps, Gauges, and Curing Lights
export const orthoInstruments = [
  {
    maId: 'PRD-050',
    maName: 'Bracket Positioning Gauge',
    maDescription: 'Precision stainless steel gauge for accurate bracket height placement on tooth surfaces. Features multiple measurement arms calibrated in 0.5 mm increments from 3.0 to 5.5 mm for consistent bracket positioning across the arch.',
    division: 'Instruments',
    category: 'Gauges',
    subcategory: 'Bracket Placement',
    sku: 'SOL-INS-050',
    price: 85.00,
    listPrice: 102.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/701-725',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { material: 'Surgical-grade stainless steel', measurements: '3.0, 3.5, 4.0, 4.5, 5.0, 5.5 mm', accuracy: '±0.1 mm', type: 'Boone-type bracket positioning gauge', arms: '6 measurement arms', sterilization: 'Autoclavable (134°C)', length: '110 mm' },
    regulatory: { fdaClearance: 'K140234', deviceClass: 'Class I', productCode: 'EIG', gudid: '00707387700150', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['gauge', 'bracket-positioning', 'measurement', 'stainless-steel', 'placement'],
  },
  {
    maId: 'PRD-051',
    maName: 'Adhesive Removing Plier',
    maDescription: 'Specially designed plier for removing residual adhesive from tooth surfaces after bracket debonding. Carbide-tipped jaws provide efficient adhesive removal without damaging enamel. Ergonomic handle design reduces hand fatigue during full-arch debonds.',
    division: 'Instruments',
    category: 'Pliers',
    subcategory: 'Debonding',
    sku: 'SOL-INS-051',
    price: 145.00,
    listPrice: 175.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/900-822',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { material: 'Stainless steel with carbide tips', jawType: 'Carbide-tipped for adhesive removal', length: '140 mm', handle: 'Ergonomic non-slip', sterilization: 'Autoclavable (134°C)', application: 'Post-debond adhesive cleanup', tipReplacement: 'Replaceable carbide inserts' },
    regulatory: { fdaClearance: 'K140235', deviceClass: 'Class I', productCode: 'EIG', gudid: '00707387700151', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['plier', 'adhesive-removing', 'debonding', 'carbide', 'cleanup'],
  },
  {
    maId: 'PRD-052',
    maName: 'Light Bracket Removing Plier',
    maDescription: 'Precision plier designed for safe removal of ceramic and metal brackets at debond. The squeeze-action design applies controlled force to the bracket base, creating a clean separation at the adhesive-bracket interface while minimizing enamel stress.',
    division: 'Instruments',
    category: 'Pliers',
    subcategory: 'Debonding',
    sku: 'SOL-INS-052',
    price: 155.00,
    listPrice: 188.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/900_755',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { material: 'Surgical-grade stainless steel', jawType: 'Angled tips for mesial-distal compression', length: '145 mm', application: 'Ceramic and metal bracket removal', technique: 'Squeeze at bracket base', compatibility: 'Twin, self-ligating, ceramic brackets', sterilization: 'Autoclavable (134°C)' },
    regulatory: { fdaClearance: 'K150567', deviceClass: 'Class I', productCode: 'EIG', gudid: '00707387700152', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['plier', 'bracket-removing', 'debonding', 'ceramic', 'metal'],
  },
  {
    maId: 'PRD-053',
    maName: 'Posterior Band Removing Plier',
    maDescription: 'Heavy-duty plier for removing cemented molar bands. Features a padded occlusal pad and a blade-style tip that engages the gingival margin of the band. Lever-action design provides controlled force for predictable band removal.',
    division: 'Instruments',
    category: 'Pliers',
    subcategory: 'Band Removal',
    sku: 'SOL-INS-053',
    price: 135.00,
    listPrice: 162.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/900-703',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { material: 'Surgical-grade stainless steel', jawType: 'Occlusal pad + gingival blade tip', length: '155 mm', application: 'Cemented molar band removal', mechanism: 'Lever-action', padMaterial: 'Replaceable nylon occlusal pad', sterilization: 'Autoclavable (134°C)' },
    regulatory: { fdaClearance: 'K140236', deviceClass: 'Class I', productCode: 'EIG', gudid: '00707387700153', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['plier', 'band-removing', 'molar-band', 'posterior', 'lever-action'],
  },
  {
    maId: 'PRD-054',
    maName: 'Ortho Bond Kit Organizer',
    maDescription: 'Chairside organizer tray designed to hold all bonding supplies in an ergonomic layout during bracket placement procedures. Accommodates adhesive syringes, primers, micro-brushes, bracket kits, and curing light tip in dedicated compartments.',
    division: 'Instruments',
    category: 'Organizers',
    subcategory: 'Bonding Setup',
    sku: 'SOL-INS-054',
    price: 65.00,
    listPrice: 78.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/900-815-2',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { material: 'Autoclavable polycarbonate', compartments: '8 dedicated wells', dimensions: '250 mm x 180 mm x 40 mm', compatibility: 'Transbond XT, Transbond Plus, micro-brush cups, bracket kits', color: 'Sterilization-indicator blue', sterilization: 'Autoclavable (134°C)', weight: '180 g' },
    regulatory: { fdaClearance: 'Exempt', deviceClass: 'Class I', productCode: 'EIG', gudid: '00707387700154', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['organizer', 'bonding-kit', 'chairside', 'tray', 'setup'],
  },
  {
    maId: 'PRD-055',
    maName: 'Direct Bond Bracket Forceps',
    maDescription: 'Reverse-action forceps for precise bracket placement during direct bonding. The locking mechanism holds the bracket securely at the desired angulation while allowing fine positional adjustments before light curing.',
    division: 'Instruments',
    category: 'Forceps',
    subcategory: 'Bracket Placement',
    sku: 'SOL-INS-055',
    price: 120.00,
    listPrice: 145.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/900-822',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { material: 'Surgical-grade stainless steel', type: 'Reverse-action self-closing', tipProfile: 'Fine-tip for bracket wing engagement', length: '130 mm', lock: 'Adjustable locking mechanism', sterilization: 'Autoclavable (134°C)', application: 'Direct bracket bonding placement' },
    regulatory: { fdaClearance: 'K140237', deviceClass: 'Class I', productCode: 'EIG', gudid: '00707387700155', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['forceps', 'bracket-placement', 'direct-bond', 'reverse-action', 'precision'],
  },
  {
    maId: 'PRD-056',
    maName: 'Mathieu Needle Holder',
    maDescription: 'Orthodontic Mathieu-style needle holder for placing and tying elastomeric and wire ligatures. The spring-action handle with locking ratchet provides secure grip on ligature ties and modules during bracket ligation.',
    division: 'Instruments',
    category: 'Needle Holders',
    subcategory: 'Ligation',
    sku: 'SOL-INS-056',
    price: 95.00,
    listPrice: 115.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/500-083',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { material: 'Surgical-grade stainless steel', type: 'Mathieu-style with locking ratchet', length: '140 mm', jawType: 'Serrated for ligature grip', mechanism: 'Spring-action with 3-position lock', sterilization: 'Autoclavable (134°C)', application: 'Ligature tie placement and tying' },
    regulatory: { fdaClearance: 'K140238', deviceClass: 'Class I', productCode: 'EIG', gudid: '00707387700156', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['needle-holder', 'mathieu', 'ligation', 'ligature', 'ratchet'],
  },
  {
    maId: 'PRD-057',
    maName: 'Eliades Ortholux Luminous Curing Light',
    maDescription: 'High-intensity LED curing light optimized for orthodontic bonding. Delivers consistent light output across the 385–515 nm wavelength range for rapid, reliable bracket bonding in as little as 6 seconds. Features a cordless, lightweight design for chairside efficiency.',
    division: 'Instruments',
    category: 'Curing Lights',
    subcategory: 'LED Curing',
    sku: 'SOL-INS-057',
    price: 1250.00,
    listPrice: 1495.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/LightCuringKit',
    isConfigurable: false,
    isSerialManaged: true,
    isBatchManaged: false,
    isSubscriptionEligible: false,
    specifications: { type: 'Cordless LED curing light', intensity: '1,600 mW/cm² (high mode)', wavelength: '385–515 nm (broad spectrum)', cureTime: '6 seconds (high mode), 10 seconds (standard mode)', battery: 'Li-ion rechargeable, ~400 cures per charge', tipDiameter: '8 mm ortho-specific tip', weight: '120 g (handpiece only)', modes: 'High, Standard, Pulse' },
    regulatory: { fdaClearance: 'K200678', deviceClass: 'Class II', productCode: 'EKQ', gudid: '00707387700157', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 5,
    minOrderQuantity: 1,
    sampleEligible: false,
    tags: ['curing-light', 'LED', 'ortholux', 'cordless', 'high-intensity'],
  },
];
