// Prevention — Fluoride Products, Sealants, and Varnishes for Orthodontic Patients
export const prevention = [
  {
    maId: 'PRD-058',
    maName: 'Clinpro 5000 Fluoride Toothpaste',
    maDescription: 'Prescription-strength 1.1% sodium fluoride toothpaste with tri-calcium phosphate (TCP) ingredient. Specifically recommended for orthodontic patients at elevated caries risk due to brackets and bands. Provides superior remineralization compared to standard fluoride toothpastes.',
    division: 'Prevention',
    category: 'Fluoride Toothpaste',
    subcategory: 'Prescription Strength',
    sku: 'SOL-PRV-058',
    price: 12.00,
    listPrice: 15.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/Q4_2015_Clinpro_5000',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { activeIngredient: '1.1% sodium fluoride (5,000 ppm)', additiveIngredient: 'Functionalized tri-calcium phosphate (fTCP)', tubeSize: '4 oz (113 g)', flavors: 'Vanilla Mint, Spearmint, Bubble Gum', usage: 'Twice daily in place of regular toothpaste', indication: 'Caries prevention in high-risk patients', rxRequired: 'Yes — prescription only' },
    regulatory: { fdaClearance: 'NDA approved (OTC monograph)', deviceClass: 'Drug — not device', productCode: 'N/A', gudid: '00707387700158', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 2,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['fluoride', 'toothpaste', 'clinpro', '5000ppm', 'caries-prevention', 'prescription'],
    volumeBreaks: [
      { minQty: 1, price: 12.00 },
      { minQty: 25, price: 11.00, label: 'Volume' },
      { minQty: 100, price: 10.00, label: 'Bulk' },
      { minQty: 500, price: 10.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-059',
    maName: 'Clinpro White Varnish – Fluoride Varnish',
    maDescription: 'Professionally applied 5% sodium fluoride varnish with tri-calcium phosphate for in-office caries prevention. The white, virtually invisible appearance is ideal for orthodontic patients. Rapid set in the presence of saliva for easy application around brackets.',
    division: 'Prevention',
    category: 'Fluoride Varnish',
    subcategory: 'In-Office Application',
    sku: 'SOL-PRV-059',
    price: 165.00,
    listPrice: 198.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/ocsd-clinpro-flouride-treatment-mint-front-lpop-50ct',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { activeIngredient: '5% sodium fluoride (22,600 ppm)', additiveIngredient: 'Functionalized tri-calcium phosphate (fTCP)', appearance: 'White — virtually invisible on teeth', packaging: '50 unit-dose trays per kit', applicationTime: '< 2 minutes full mouth', setTime: 'Immediate set on contact with saliva', flavors: 'Mint, Melon, Bubble Gum' },
    regulatory: { fdaClearance: 'K190890', deviceClass: 'Class II', productCode: 'EJF', gudid: '00707387700159', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['varnish', 'fluoride', 'clinpro-white', 'in-office', 'caries-prevention'],
    volumeBreaks: [
      { minQty: 1, price: 165.00 },
      { minQty: 10, price: 153.00, label: 'Volume' },
      { minQty: 50, price: 142.00, label: 'Bulk' },
      { minQty: 100, price: 132.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-060',
    maName: 'Clinpro Sealant',
    maDescription: 'Light-cured fluoride-releasing pit and fissure sealant for protecting occlusal surfaces during orthodontic treatment. The pink-to-white color change confirms complete cure. Low viscosity ensures deep penetration into fissures even around molar bands.',
    division: 'Prevention',
    category: 'Sealants',
    subcategory: 'Pit and Fissure',
    sku: 'SOL-PRV-060',
    price: 85.00,
    listPrice: 105.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/ocsd-varnishes-sealants-clinpro-sealant-refill-12600-series-b10276208-pdp-mainimage-glbl',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: true,
    specifications: { type: 'Light-cured resin-based sealant', fluorideRelease: 'Yes — sustained fluoride release', colorChange: 'Pink (uncured) → White/tooth-colored (cured)', cureTime: '20 seconds', viscosity: 'Low — self-leveling into fissures', packaging: '2 x 1.2 mL syringes per kit with tips', indication: 'Pit and fissure sealing of premolars and molars' },
    regulatory: { fdaClearance: 'K180890', deviceClass: 'Class II', productCode: 'LSE', gudid: '00707387700160', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['sealant', 'clinpro', 'fluoride-releasing', 'pit-fissure', 'preventive'],
    volumeBreaks: [
      { minQty: 1, price: 85.00 },
      { minQty: 10, price: 79.00, label: 'Volume' },
      { minQty: 50, price: 73.00, label: 'Bulk' },
      { minQty: 100, price: 68.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-061',
    maName: 'Vanish XT Extended Contact Varnish',
    maDescription: 'Resin-modified glass ionomer varnish providing extended fluoride release for up to 6 months. Ideal for coating smooth surfaces around orthodontic brackets to prevent white spot lesions. Moisture-tolerant application simplifies use in the orthodontic workflow.',
    division: 'Prevention',
    category: 'Glass Ionomer Varnish',
    subcategory: 'Extended Release',
    sku: 'SOL-PRV-061',
    price: 195.00,
    listPrice: 235.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/vanish_xt_KO_12148',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { type: 'Resin-modified glass ionomer varnish', fluorideRelease: 'Extended — up to 6 months', cureTime: '20 seconds light cure', moistureTolerance: 'Sets in presence of moisture', packaging: '50 unit-dose capsules with applicator tips', application: 'Smooth surface coating around brackets', filmThickness: 'Ultra-thin — does not interfere with occlusion' },
    regulatory: { fdaClearance: 'K200890', deviceClass: 'Class II', productCode: 'LSE', gudid: '00707387700161', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['varnish', 'vanish-XT', 'glass-ionomer', 'extended-release', 'white-spot-prevention'],
    volumeBreaks: [
      { minQty: 1, price: 195.00 },
      { minQty: 10, price: 181.00, label: 'Volume' },
      { minQty: 50, price: 168.00, label: 'Bulk' },
      { minQty: 100, price: 156.00, label: 'Enterprise' },
    ],
  },
  {
    maId: 'PRD-062',
    maName: 'Clinpro XT Varnish',
    maDescription: 'Light-cured resin-modified glass ionomer protective coating that releases fluoride and calcium. Provides a durable physical barrier on smooth enamel surfaces adjacent to orthodontic brackets, preventing demineralization and white spot lesion formation.',
    division: 'Prevention',
    category: 'Glass Ionomer Varnish',
    subcategory: 'Protective Coating',
    sku: 'SOL-PRV-062',
    price: 178.00,
    listPrice: 215.00,
    imageUrl: 'https://assets.solventum.com/is/image/mmmspinco/vanish_xt_KO_12148',
    isConfigurable: false,
    isSerialManaged: false,
    isBatchManaged: true,
    isSubscriptionEligible: false,
    specifications: { type: 'Light-cured resin-modified glass ionomer varnish', fluorideRelease: 'Sustained fluoride and calcium release', cureTime: '20 seconds', packaging: 'Paste-liquid kit (click-mix capsules, 20 per kit)', durability: 'Up to 6 months with proper application', application: 'Enamel surfaces around brackets and bands', bondStrength: 'Chemical bond to enamel — no etching required' },
    regulatory: { fdaClearance: 'K210890', deviceClass: 'Class II', productCode: 'LSE', gudid: '00707387700162', mdsrCompliant: true },
    availability: 'In Stock',
    leadTimeDays: 3,
    minOrderQuantity: 1,
    sampleEligible: true,
    tags: ['varnish', 'clinpro-XT', 'glass-ionomer', 'protective-coating', 'demineralization'],
    volumeBreaks: [
      { minQty: 1, price: 178.00 },
      { minQty: 10, price: 166.00, label: 'Volume' },
      { minQty: 50, price: 153.00, label: 'Bulk' },
      { minQty: 100, price: 142.00, label: 'Enterprise' },
    ],
  },
];
