// Mock contracts for Solventum Ortho Portal
// Types: volume | standard | custom
// Statuses: Active | Pending | Expired | Cancelled

export const contracts = [
  {
    id: 'CTR-001',
    customerId: 'ORG-001',
    customerName: 'Chen Orthodontics',
    type: 'volume',
    status: 'Active',
    startDate: '2025-04-01T00:00:00Z',
    endDate: '2026-03-31T00:00:00Z',
    tierLevel: 'Gold',
    discountPercentage: 15,
    minimumAnnualCommitment: 25000,
    currentAnnualSpend: 42800,
    specialPricing: [
      { productId: 'PRD-001', productName: 'Clarity Advanced Ceramic Brackets', contractPrice: 323.00, listPrice: 380.00 },
      { productId: 'PRD-016', productName: 'Transbond XT Light Cure Adhesive', contractPrice: 80.75, listPrice: 95.00 },
      { productId: 'PRD-032', productName: 'Unitek Stainless Steel Archwires', contractPrice: 42.50, listPrice: 50.00 },
      { productId: 'PRD-029', productName: 'Clarity Precision Grip Attachments', contractPrice: 144.50, listPrice: 170.00 },
    ],
    terms: 'Net 30',
    autoRenew: true,
    notes: 'Gold tier pricing based on annual volume commitment. Dr. Chen has been a loyal customer since 2023. Eligible for upgrade to Platinum at $75K annual spend.',
    createdAt: '2025-03-15T00:00:00Z',
    updatedAt: '2026-01-10T00:00:00Z',
  },
  {
    id: 'CTR-002',
    customerId: 'ORG-002',
    customerName: 'Smile DSO Group',
    type: 'custom',
    status: 'Active',
    startDate: '2025-01-01T00:00:00Z',
    endDate: '2026-12-31T00:00:00Z',
    tierLevel: 'Platinum',
    discountPercentage: 22,
    minimumAnnualCommitment: 150000,
    currentAnnualSpend: 218400,
    specialPricing: [
      { productId: 'PRD-001', productName: 'Clarity Advanced Ceramic Brackets', contractPrice: 296.40, listPrice: 380.00 },
      { productId: 'PRD-002', productName: 'Clarity Ultra Self-Ligating Brackets', contractPrice: 351.00, listPrice: 450.00 },
      { productId: 'PRD-016', productName: 'Transbond XT Light Cure Adhesive', contractPrice: 74.10, listPrice: 95.00 },
      { productId: 'PRD-017', productName: 'Transbond Plus Color Change Adhesive', contractPrice: 85.80, listPrice: 110.00 },
      { productId: 'PRD-026', productName: 'Clarity Aligners Starter Kit', contractPrice: 1170.00, listPrice: 1500.00 },
      { productId: 'PRD-027', productName: 'Clarity Aligners Refinement Kit', contractPrice: 390.00, listPrice: 500.00 },
      { productId: 'PRD-032', productName: 'Unitek Stainless Steel Archwires', contractPrice: 39.00, listPrice: 50.00 },
      { productId: 'PRD-033', productName: 'Nitinol Heat-Activated Archwires', contractPrice: 54.60, listPrice: 70.00 },
      { productId: 'PRD-040', productName: 'APC Flash-Free Adhesive Brackets', contractPrice: 257.40, listPrice: 330.00 },
      { productId: 'PRD-058', productName: 'Incognito Lingual Brackets', contractPrice: 780.00, listPrice: 1000.00 },
    ],
    terms: 'Net 45',
    autoRenew: true,
    notes: 'Custom DSO agreement covering 12 locations. Quarterly volume review with dedicated account manager. Includes complimentary on-site training for new staff. Negotiated extended payment terms due to multi-location scale.',
    createdAt: '2024-11-15T00:00:00Z',
    updatedAt: '2026-02-01T00:00:00Z',
  },
  {
    id: 'CTR-003',
    customerId: 'ORG-003',
    customerName: 'Bright Smiles Orthodontics',
    type: 'standard',
    status: 'Active',
    startDate: '2025-04-15T00:00:00Z',
    endDate: '2026-04-14T00:00:00Z',
    tierLevel: 'Silver',
    discountPercentage: 10,
    minimumAnnualCommitment: 12000,
    currentAnnualSpend: 18900,
    specialPricing: [
      { productId: 'PRD-001', productName: 'Clarity Advanced Ceramic Brackets', contractPrice: 342.00, listPrice: 380.00 },
      { productId: 'PRD-016', productName: 'Transbond XT Light Cure Adhesive', contractPrice: 85.50, listPrice: 95.00 },
      { productId: 'PRD-033', productName: 'Nitinol Heat-Activated Archwires', contractPrice: 63.00, listPrice: 70.00 },
    ],
    terms: 'Net 30',
    autoRenew: false,
    notes: 'Standard Silver tier contract. Expiring within 60 days — renewal discussion scheduled for March. Practice is growing and may qualify for Gold tier on renewal based on projected volume increase.',
    createdAt: '2025-04-01T00:00:00Z',
    updatedAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'CTR-004',
    customerId: 'ORG-004',
    customerName: 'Metro Dental Partners',
    type: 'volume',
    status: 'Active',
    startDate: '2025-07-01T00:00:00Z',
    endDate: '2026-06-30T00:00:00Z',
    tierLevel: 'Gold',
    discountPercentage: 15,
    minimumAnnualCommitment: 30000,
    currentAnnualSpend: 36200,
    specialPricing: [
      { productId: 'PRD-001', productName: 'Clarity Advanced Ceramic Brackets', contractPrice: 323.00, listPrice: 380.00 },
      { productId: 'PRD-002', productName: 'Clarity Ultra Self-Ligating Brackets', contractPrice: 382.50, listPrice: 450.00 },
      { productId: 'PRD-016', productName: 'Transbond XT Light Cure Adhesive', contractPrice: 80.75, listPrice: 95.00 },
      { productId: 'PRD-018', productName: 'Transbond Supreme LV Adhesive', contractPrice: 102.00, listPrice: 120.00 },
      { productId: 'PRD-034', productName: 'Beta-Titanium Archwires', contractPrice: 72.25, listPrice: 85.00 },
      { productId: 'PRD-041', productName: 'APC Plus Adhesive Coated Appliance', contractPrice: 280.50, listPrice: 330.00 },
    ],
    terms: 'Net 30',
    autoRenew: true,
    notes: 'Gold tier volume contract. Metro Dental is expanding their orthodontic services across their general practice network. Tracking well above minimum commitment.',
    createdAt: '2025-06-10T00:00:00Z',
    updatedAt: '2026-02-05T00:00:00Z',
  },
  {
    id: 'CTR-005',
    customerId: 'ORG-005',
    customerName: 'Lakeside Family Orthodontics',
    type: 'standard',
    status: 'Pending',
    startDate: '2026-04-01T00:00:00Z',
    endDate: '2027-03-31T00:00:00Z',
    tierLevel: 'Bronze',
    discountPercentage: 5,
    minimumAnnualCommitment: 5000,
    currentAnnualSpend: 0,
    specialPricing: [
      { productId: 'PRD-001', productName: 'Clarity Advanced Ceramic Brackets', contractPrice: 361.00, listPrice: 380.00 },
      { productId: 'PRD-016', productName: 'Transbond XT Light Cure Adhesive', contractPrice: 90.25, listPrice: 95.00 },
    ],
    terms: 'Net 30',
    autoRenew: false,
    notes: 'Pending renewal for Bronze tier. Lakeside is a smaller family practice exploring expanded Solventum product usage. Previous contract expired 2026-03-31. Sales rep Emily Rodriguez is working with Dr. Nakamura on potential upgrade to Silver tier with increased volume commitment.',
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-02-18T00:00:00Z',
  },
];

export const getContractById = (id) => contracts.find((c) => c.id === id);
export const getContractsByCustomer = (customerId) => contracts.filter((c) => c.customerId === customerId);
export const getActiveContracts = () => contracts.filter((c) => c.status === 'Active');
export const contractStatuses = ['Active', 'Pending', 'Expired', 'Cancelled'];
export default contracts;
