// Mock product documentation for Solventum Ortho Portal
// Types: User Manual, IFU, Quick Reference, Service Manual, Brochure, White Paper, Regulatory, SDS, Technique Guide

export const documentation = [
  {
    id: 'DOC-001',
    title: 'Clarity Advanced Ceramic Brackets — Instructions for Use',
    type: 'IFU',
    productIds: ['PRD-001', 'PRD-002'],
    productNames: ['Clarity Advanced Ceramic Brackets — Upper 5x5 Kit', 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit'],
    division: 'Orthodontics',
    description:
      'Complete instructions for use including indications, contraindications, bracket placement guidelines, debonding techniques, and patient care instructions for Clarity Advanced ceramic brackets.',
    version: '4.1',
    language: 'en-US',
    publishDate: '2024-06-15T00:00:00Z',
    lastUpdated: '2024-06-15T00:00:00Z',
    fileUrl: '/docs/clarity-advanced-ifu-v4.1.pdf',
    fileSize: '3.8 MB',
    pageCount: 48,
    documentNumber: 'IFU-CLR-ADV-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'registered_users',
    tags: ['brackets', 'clarity', 'ceramic', 'IFU', 'bonding', 'debonding', 'safety'],
  },
  {
    id: 'DOC-002',
    title: 'Transbond XT Light Cure Adhesive — Instructions for Use',
    type: 'IFU',
    productIds: ['PRD-010'],
    productNames: ['Transbond XT Light Cure Adhesive Syringe Kit'],
    division: 'Orthodontics',
    description:
      'Instructions for use for Transbond XT orthodontic adhesive including mixing, application, light curing parameters, storage requirements, and safety precautions.',
    version: '6.0',
    language: 'en-US',
    publishDate: '2024-03-01T00:00:00Z',
    lastUpdated: '2024-09-10T00:00:00Z',
    fileUrl: '/docs/transbond-xt-ifu-v6.0.pdf',
    fileSize: '2.4 MB',
    pageCount: 32,
    documentNumber: 'IFU-TBXT-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'registered_users',
    tags: ['transbond', 'adhesive', 'bonding', 'IFU', 'light-cure', 'orthodontic'],
  },
  {
    id: 'DOC-003',
    title: 'Transbond XT — Safety Data Sheet (SDS)',
    type: 'SDS',
    productIds: ['PRD-010'],
    productNames: ['Transbond XT Light Cure Adhesive Syringe Kit'],
    division: 'Orthodontics',
    description:
      'Safety Data Sheet for Transbond XT Light Cure Adhesive. Includes chemical composition, hazard identification, first aid measures, handling and storage, and exposure controls.',
    version: '8.2',
    language: 'en-US',
    publishDate: '2024-01-15T00:00:00Z',
    lastUpdated: '2024-08-20T00:00:00Z',
    fileUrl: '/docs/transbond-xt-sds-v8.2.pdf',
    fileSize: '1.2 MB',
    pageCount: 12,
    documentNumber: 'SDS-TBXT-EN-US',
    regulatoryClassification: 'Regulatory — OSHA/GHS Required',
    accessLevel: 'public',
    tags: ['transbond', 'SDS', 'safety', 'chemical', 'OSHA', 'adhesive'],
  },
  {
    id: 'DOC-004',
    title: 'Clarity Advanced — Bracket Positioning & Bonding Technique Guide',
    type: 'Technique Guide',
    productIds: ['PRD-001', 'PRD-002', 'PRD-010'],
    productNames: ['Clarity Advanced Ceramic Brackets — Upper 5x5 Kit', 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit', 'Transbond XT Light Cure Adhesive Syringe Kit'],
    division: 'Orthodontics',
    description:
      'Step-by-step technique guide for optimal bracket positioning using the Clarity Advanced system. Includes tooth-by-tooth placement heights, angulation guidelines, Transbond XT application technique, and ceramic bracket debonding best practices.',
    version: '3.0',
    language: 'en-US',
    publishDate: '2024-09-01T00:00:00Z',
    lastUpdated: '2024-09-01T00:00:00Z',
    fileUrl: '/docs/clarity-advanced-technique-guide-v3.0.pdf',
    fileSize: '8.5 MB',
    pageCount: 64,
    documentNumber: 'TG-CLR-ADV-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'medical_professionals',
    tags: ['brackets', 'clarity', 'positioning', 'technique', 'bonding', 'ceramic', 'debonding'],
  },
  {
    id: 'DOC-005',
    title: 'Nitinol Super Elastic Archwires — Instructions for Use',
    type: 'IFU',
    productIds: ['PRD-030', 'PRD-032'],
    productNames: ['Nitinol Super Elastic Archwires — Upper Assortment Pack', 'Nitinol Super Elastic Archwires — Lower Assortment Pack'],
    division: 'Orthodontics',
    description:
      'Instructions for use for nickel-titanium super elastic archwires including wire selection, insertion technique, activation guidelines, and patient allergy considerations.',
    version: '3.2',
    language: 'en-US',
    publishDate: '2024-04-01T00:00:00Z',
    lastUpdated: '2024-04-01T00:00:00Z',
    fileUrl: '/docs/niti-archwires-ifu-v3.2.pdf',
    fileSize: '2.1 MB',
    pageCount: 28,
    documentNumber: 'IFU-NITI-SE-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'registered_users',
    tags: ['archwires', 'nitinol', 'NiTi', 'IFU', 'super-elastic', 'orthodontic'],
  },
  {
    id: 'DOC-006',
    title: 'Clarity Aligner System — Prescriber Guide',
    type: 'Quick Reference',
    productIds: ['PRD-020', 'PRD-021'],
    productNames: ['Clarity Aligner System — Practice Starter Kit', 'Clarity Aligner Case Credit Pack (25 cases)'],
    division: 'Orthodontics',
    description:
      'Quick reference guide for orthodontists prescribing Clarity Aligners. Covers case selection, digital scanning requirements, ClinCheck-style treatment planning in the Clarity portal, and aligner delivery protocols.',
    version: '2.5',
    language: 'en-US',
    publishDate: '2024-07-01T00:00:00Z',
    lastUpdated: '2024-07-01T00:00:00Z',
    fileUrl: '/docs/clarity-aligner-prescriber-guide-v2.5.pdf',
    fileSize: '4.2 MB',
    pageCount: 36,
    documentNumber: 'QS-CLR-ALN-EN-US',
    regulatoryClassification: 'Controlled Document',
    accessLevel: 'medical_professionals',
    tags: ['clarity', 'aligner', 'prescriber', 'digital', 'treatment-planning', 'clear-aligner'],
  },
  {
    id: 'DOC-007',
    title: 'Clarity Advanced Ceramic Brackets — Clinical Evidence Summary',
    type: 'White Paper',
    productIds: ['PRD-001', 'PRD-002'],
    productNames: ['Clarity Advanced Ceramic Brackets — Upper 5x5 Kit', 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit'],
    division: 'Orthodontics',
    description:
      'Peer-reviewed clinical evidence summary demonstrating bond strength, esthetics, patient satisfaction, and debonding safety for the Clarity Advanced ceramic bracket system. Includes data from 12 clinical studies.',
    version: '2.0',
    language: 'en-US',
    publishDate: '2024-10-15T00:00:00Z',
    lastUpdated: '2024-10-15T00:00:00Z',
    fileUrl: '/docs/clarity-advanced-clinical-evidence-v2.0.pdf',
    fileSize: '3.4 MB',
    pageCount: 24,
    documentNumber: 'WP-CLR-ADV-CLIN-EN-US',
    regulatoryClassification: 'Marketing Material',
    accessLevel: 'public',
    tags: ['clarity', 'ceramic', 'clinical-evidence', 'white-paper', 'bond-strength', 'esthetics'],
  },
  {
    id: 'DOC-008',
    title: 'Clarity Aligner System — Patient Marketing Brochure',
    type: 'Brochure',
    productIds: ['PRD-020', 'PRD-021'],
    productNames: ['Clarity Aligner System — Practice Starter Kit', 'Clarity Aligner Case Credit Pack (25 cases)'],
    division: 'Orthodontics',
    description:
      'Patient-facing marketing brochure for the Clarity Aligner system. Covers treatment benefits, the aligner process, before/after examples, and practice customization options. Available for co-branding with practice logo.',
    version: '3.1',
    language: 'en-US',
    publishDate: '2024-02-01T00:00:00Z',
    lastUpdated: '2024-08-15T00:00:00Z',
    fileUrl: '/docs/clarity-aligner-patient-brochure-v3.1.pdf',
    fileSize: '6.2 MB',
    pageCount: 8,
    documentNumber: 'BRO-CLR-ALN-EN-US',
    regulatoryClassification: 'Marketing Material',
    accessLevel: 'registered_users',
    tags: ['clarity', 'aligner', 'brochure', 'marketing', 'patient-education', 'esthetics'],
  },
  {
    id: 'DOC-009',
    title: 'Transbond Plus SEP — Safety Data Sheet (SDS)',
    type: 'SDS',
    productIds: ['PRD-012'],
    productNames: ['Transbond Plus SEP Single Dose Packets (100pk)'],
    division: 'Orthodontics',
    description:
      'Safety Data Sheet for Transbond Plus Self-Etching Primer. Chemical composition, hazard identification, handling and storage, toxicological information, and disposal considerations.',
    version: '5.0',
    language: 'en-US',
    publishDate: '2024-05-01T00:00:00Z',
    lastUpdated: '2024-05-01T00:00:00Z',
    fileUrl: '/docs/transbond-plus-sep-sds-v5.0.pdf',
    fileSize: '1.1 MB',
    pageCount: 10,
    documentNumber: 'SDS-TBSEP-EN-US',
    regulatoryClassification: 'Regulatory — OSHA/GHS Required',
    accessLevel: 'public',
    tags: ['transbond', 'SEP', 'primer', 'SDS', 'safety', 'chemical', 'OSHA'],
  },
  {
    id: 'DOC-010',
    title: 'Solventum Ortho Portal — Ordering and Account Management Guide',
    type: 'User Manual',
    productIds: [],
    productNames: [],
    division: 'General',
    description:
      'User guide for the Solventum Ortho customer portal. Covers account setup, product search, ordering, order tracking, invoice management, consignment inventory, subscription management, and Clarity Aligner case submission.',
    version: '1.2',
    language: 'en-US',
    publishDate: '2025-01-01T00:00:00Z',
    lastUpdated: '2025-01-01T00:00:00Z',
    fileUrl: '/docs/ortho-portal-user-guide-v1.2.pdf',
    fileSize: '5.8 MB',
    pageCount: 44,
    documentNumber: 'MAN-ORTHO-PORTAL-EN-US',
    regulatoryClassification: 'Non-Regulated',
    accessLevel: 'registered_users',
    tags: ['portal', 'user-guide', 'ordering', 'account-management', 'help', 'clarity'],
  },
];

export const getDocumentById = (id) => documentation.find((d) => d.id === id);
export const getDocumentsByProduct = (productId) =>
  documentation.filter((d) => d.productIds.includes(productId));
export const getDocumentsByType = (type) => documentation.filter((d) => d.type === type);
export const getDocumentsByDivision = (division) =>
  documentation.filter((d) => d.division === division);

export const documentTypes = [
  'User Manual',
  'IFU',
  'Quick Reference',
  'Service Manual',
  'Brochure',
  'White Paper',
  'Regulatory',
  'SDS',
  'Technique Guide',
];

export default documentation;
