// Mock orders for Solventum Ortho Portal
// Various statuses: Draft, Submitted, Confirmed, Shipped, Delivered, Invoiced, Cancelled

export const orders = [
  {
    biId: 'ORD-2025-0001',
    biName: 'Chen Ortho — Clarity Advanced Bracket Kit',
    biDescription: 'Clarity Advanced Ceramic Brackets bulk order for high-volume practice restocking.',
    status: 'Confirmed',
    priority: 'High',
    biCreatedAt: '2025-01-02T09:15:00Z',
    biUpdatedAt: '2025-01-05T14:30:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        sku: 'SOL-CLR-ADV-U5',
        quantity: 20,
        unitPrice: 189.0,
        discount: 18.90,
        lineTotal: 3402.0,
        configuration: 'Roth .022, Hooks 3-3',
      },
      {
        lineNumber: 2,
        productId: 'PRD-002',
        productName: 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit',
        sku: 'SOL-CLR-ADV-L5',
        quantity: 20,
        unitPrice: 189.0,
        discount: 18.90,
        lineTotal: 3402.0,
        configuration: 'Roth .022, Hooks 3-3',
      },
      {
        lineNumber: 3,
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        sku: 'SOL-TBXT-SYR-KIT',
        quantity: 10,
        unitPrice: 82.50,
        discount: 0,
        lineTotal: 825.0,
      },
    ],
    pricing: {
      subtotal: 7629.0,
      discount: 756.0,
      tax: 583.69,
      freight: 18.95,
      total: 7475.64,
      currency: 'USD',
    },
    shipTo: {
      name: 'Chen Orthodontics',
      street: '1200 Madison Ave',
      building: 'Suite 300, Front Desk',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-01-15T00:00:00Z',
    contractId: 'CTR-001',
    notes: 'Gold tier pricing applied. Reorder of standard bracket inventory.',
  },
  {
    biId: 'ORD-2025-0002',
    biName: 'Smile DSO — Multi-Location Bracket & Bonding Restock',
    biDescription: 'Quarterly restocking of brackets and bonding supplies across 12 Smile DSO locations.',
    status: 'Shipped',
    priority: 'Standard',
    biCreatedAt: '2024-12-18T11:00:00Z',
    biUpdatedAt: '2025-01-08T08:45:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-002',
      name: 'Smile DSO Group',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@smiledsogroup.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-003',
        productName: 'Clarity Ultra Self-Ligating Brackets — Upper Kit',
        sku: 'SOL-CLR-ULT-U',
        quantity: 48,
        unitPrice: 245.0,
        discount: 24.50,
        lineTotal: 10584.0,
        configuration: 'MBT .022, Standard Torque',
      },
      {
        lineNumber: 2,
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        sku: 'SOL-TBXT-SYR-KIT',
        quantity: 36,
        unitPrice: 82.50,
        discount: 8.25,
        lineTotal: 2673.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-012',
        productName: 'Transbond Plus SEP Single Dose Packets (100pk)',
        sku: 'SOL-TBSEP-100',
        quantity: 24,
        unitPrice: 165.0,
        discount: 16.50,
        lineTotal: 3564.0,
      },
    ],
    pricing: {
      subtotal: 16821.0,
      discount: 1782.0,
      tax: 1278.31,
      freight: 45.00,
      total: 16362.31,
      currency: 'USD',
    },
    shipTo: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      building: 'Loading Dock, Suite 100',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
      country: 'US',
    },
    paymentTerms: 'Net 45',
    requestedDeliveryDate: '2025-01-10T00:00:00Z',
    contractId: 'CTR-002',
    notes: 'Platinum tier pricing. Ship to central distribution for internal allocation.',
  },
  {
    biId: 'ORD-2025-0003',
    biName: 'Bright Smiles — Clarity Aligner Starter Kit',
    biDescription: 'Clarity Aligner System starter kit including scanning software license and initial case credits.',
    status: 'Delivered',
    priority: 'Standard',
    biCreatedAt: '2024-11-20T14:30:00Z',
    biUpdatedAt: '2024-12-15T10:00:00Z',
    biCompletedAt: '2024-12-15T10:00:00Z',
    customer: {
      id: 'ORG-003',
      name: 'Bright Smiles Orthodontics',
      contactName: 'Dr. Michael Thompson',
      contactEmail: 'm.thompson@brightsmiles.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-020',
        productName: 'Clarity Aligner System — Practice Starter Kit',
        sku: 'SOL-CLR-ALN-START',
        quantity: 1,
        unitPrice: 4500.0,
        discount: 500.0,
        lineTotal: 4000.0,
        configuration: 'Includes 10 case credits, software license, marketing kit',
      },
      {
        lineNumber: 2,
        productId: 'PRD-021',
        productName: 'Clarity Aligner Case Credit Pack (25 cases)',
        sku: 'SOL-CLR-ALN-25',
        quantity: 2,
        unitPrice: 3750.0,
        discount: 0,
        lineTotal: 7500.0,
      },
    ],
    pricing: {
      subtotal: 11500.0,
      discount: 500.0,
      tax: 935.0,
      freight: 0,
      total: 11935.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Bright Smiles Orthodontics',
      street: '615 Elsinore Pl',
      building: 'Suite 200, Reception',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2024-12-12T00:00:00Z',
    contractId: 'CTR-003',
    notes: 'New Clarity Aligner practice. Include onboarding materials and rep follow-up.',
  },
  {
    biId: 'ORD-2025-0004',
    biName: 'Chen Ortho — Archwire & Auxiliary Supplies',
    biDescription: 'Monthly archwire and auxiliary supply replenishment for busy bracket practice.',
    status: 'Invoiced',
    priority: 'Standard',
    biCreatedAt: '2024-10-15T08:00:00Z',
    biUpdatedAt: '2024-11-30T16:00:00Z',
    biCompletedAt: '2024-11-28T14:30:00Z',
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-030',
        productName: 'Nitinol Super Elastic Archwires — Upper Assortment Pack',
        sku: 'SOL-NITI-SE-U-ASST',
        quantity: 15,
        unitPrice: 42.00,
        discount: 0,
        lineTotal: 630.0,
        configuration: '.014, .016, .018 round — 10 per size',
      },
      {
        lineNumber: 2,
        productId: 'PRD-031',
        productName: 'Stainless Steel Archwires — Upper Assortment Pack',
        sku: 'SOL-SS-U-ASST',
        quantity: 10,
        unitPrice: 28.00,
        discount: 0,
        lineTotal: 280.0,
        configuration: '.016x.022, .017x.025, .019x.025 — 10 per size',
      },
      {
        lineNumber: 3,
        productId: 'PRD-040',
        productName: 'Elastomeric Ligature Ties — Assorted Colors (1000pk)',
        sku: 'SOL-ELAS-LIG-1000',
        quantity: 5,
        unitPrice: 24.50,
        discount: 0,
        lineTotal: 122.50,
      },
      {
        lineNumber: 4,
        productId: 'PRD-041',
        productName: 'NiTi Coil Springs — Open (10pk)',
        sku: 'SOL-NITI-COIL-OPN',
        quantity: 8,
        unitPrice: 38.00,
        discount: 0,
        lineTotal: 304.0,
      },
    ],
    pricing: {
      subtotal: 1336.50,
      discount: 0,
      tax: 113.60,
      freight: 12.95,
      total: 1463.05,
      currency: 'USD',
    },
    shipTo: {
      name: 'Chen Orthodontics',
      street: '1200 Madison Ave',
      building: 'Suite 300, Front Desk',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2024-11-20T00:00:00Z',
    contractId: 'CTR-001',
    notes: 'Monthly archwire replenishment. Auto-subscription setup recommended.',
  },
  {
    biId: 'ORD-2025-0005',
    biName: 'Smile DSO — Clarity Aligner Multi-Location Rollout',
    biDescription: 'Clarity Aligner program expansion across 8 additional Smile DSO locations.',
    status: 'Delivered',
    priority: 'High',
    biCreatedAt: '2024-09-05T10:30:00Z',
    biUpdatedAt: '2024-10-22T09:15:00Z',
    biCompletedAt: '2024-10-22T09:15:00Z',
    customer: {
      id: 'ORG-002',
      name: 'Smile DSO Group',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@smiledsogroup.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-020',
        productName: 'Clarity Aligner System — Practice Starter Kit',
        sku: 'SOL-CLR-ALN-START',
        quantity: 8,
        unitPrice: 4500.0,
        discount: 900.0,
        lineTotal: 28800.0,
        configuration: 'Includes 10 case credits each, software licenses, marketing kits',
      },
    ],
    pricing: {
      subtotal: 28800.0,
      discount: 7200.0,
      tax: 1836.0,
      freight: 0,
      total: 23436.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      building: 'Loading Dock, Suite 100',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
      country: 'US',
    },
    paymentTerms: 'Net 45',
    requestedDeliveryDate: '2024-10-15T00:00:00Z',
    contractId: 'CTR-002',
    notes: 'Platinum volume discount applied. Training coordination with each location required.',
  },
  {
    biId: 'ORD-2025-0006',
    biName: 'Chen Ortho — Ortholux Luminous Curing Light',
    biDescription: 'Ortholux Luminous LED curing light for new operatory expansion.',
    status: 'Submitted',
    priority: 'High',
    biCreatedAt: '2025-01-10T16:00:00Z',
    biUpdatedAt: '2025-01-10T16:00:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-050',
        productName: 'Ortholux Luminous LED Curing Light',
        sku: 'SOL-ORTHLX-LUM',
        quantity: 2,
        unitPrice: 1850.0,
        discount: 185.0,
        lineTotal: 3330.0,
        configuration: 'Standard kit with charging base and 5 light guides',
      },
    ],
    pricing: {
      subtotal: 3330.0,
      discount: 370.0,
      tax: 251.60,
      freight: 15.00,
      total: 3226.60,
      currency: 'USD',
    },
    shipTo: {
      name: 'Chen Orthodontics',
      street: '1200 Madison Ave',
      building: 'Suite 300, Front Desk',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-02-15T00:00:00Z',
    contractId: 'CTR-001',
    notes: 'New operatory expansion. Expedited shipping requested.',
  },
  {
    biId: 'ORD-2025-0007',
    biName: 'Smile DSO — Bonding Supply Bulk Order',
    biDescription: 'Bulk bonding and adhesive supply restock for all 12 locations.',
    status: 'Confirmed',
    priority: 'Standard',
    biCreatedAt: '2025-01-08T13:45:00Z',
    biUpdatedAt: '2025-01-12T09:00:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-002',
      name: 'Smile DSO Group',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@smiledsogroup.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        sku: 'SOL-TBXT-SYR-KIT',
        quantity: 60,
        unitPrice: 82.50,
        discount: 12.38,
        lineTotal: 4207.50,
      },
      {
        lineNumber: 2,
        productId: 'PRD-011',
        productName: 'Transbond MIP Moisture Insensitive Primer (5ml)',
        sku: 'SOL-TBMIP-5ML',
        quantity: 48,
        unitPrice: 45.00,
        discount: 6.75,
        lineTotal: 1836.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-012',
        productName: 'Transbond Plus SEP Single Dose Packets (100pk)',
        sku: 'SOL-TBSEP-100',
        quantity: 36,
        unitPrice: 165.0,
        discount: 24.75,
        lineTotal: 5049.0,
      },
    ],
    pricing: {
      subtotal: 11092.50,
      discount: 1417.50,
      tax: 0.0,
      freight: 35.00,
      total: 9710.00,
      currency: 'USD',
    },
    shipTo: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      building: 'Loading Dock, Suite 100',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
      country: 'US',
    },
    paymentTerms: 'Net 45',
    requestedDeliveryDate: '2025-01-22T00:00:00Z',
    contractId: 'CTR-002',
    notes: 'Platinum tier bulk discount. Tax exempt on file.',
  },
  {
    biId: 'ORD-2025-0008',
    biName: 'Metro Dental — Practice Startup Bracket Kit',
    biDescription: 'New orthodontic practice startup kit with brackets and bonding essentials.',
    status: 'Draft',
    priority: 'Low',
    biCreatedAt: '2025-01-14T10:20:00Z',
    biUpdatedAt: '2025-01-14T10:20:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-004',
      name: 'Metro Dental Partners',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@metrodentalpartners.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        sku: 'SOL-CLR-ADV-U5',
        quantity: 10,
        unitPrice: 189.0,
        discount: 0,
        lineTotal: 1890.0,
        configuration: 'Roth .022, Hooks 3-3',
      },
      {
        lineNumber: 2,
        productId: 'PRD-005',
        productName: 'Victory Series Metal Brackets — Upper 5x5 Kit',
        sku: 'SOL-VIC-MTL-U5',
        quantity: 20,
        unitPrice: 85.0,
        discount: 0,
        lineTotal: 1700.0,
        configuration: 'MBT .022',
      },
      {
        lineNumber: 3,
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        sku: 'SOL-TBXT-SYR-KIT',
        quantity: 5,
        unitPrice: 82.50,
        discount: 0,
        lineTotal: 412.50,
      },
    ],
    pricing: {
      subtotal: 4002.50,
      discount: 0,
      tax: 340.21,
      freight: 18.95,
      total: 4361.66,
      currency: 'USD',
    },
    shipTo: {
      name: 'Metro Dental Partners',
      street: '900 Pacific Ave',
      building: 'Suite 200, Supply Room',
      city: 'Tacoma',
      state: 'WA',
      zip: '98402',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-03-01T00:00:00Z',
    contractId: null,
    notes: 'Draft — awaiting budget approval from DSO management.',
  },
  {
    biId: 'ORD-2025-0009',
    biName: 'Bright Smiles — Archwire Complete Inventory',
    biDescription: 'Full archwire inventory build-out for expanded practice.',
    status: 'Shipped',
    priority: 'Standard',
    biCreatedAt: '2024-12-05T09:00:00Z',
    biUpdatedAt: '2025-01-06T11:30:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-003',
      name: 'Bright Smiles Orthodontics',
      contactName: 'Dr. Michael Thompson',
      contactEmail: 'm.thompson@brightsmiles.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-030',
        productName: 'Nitinol Super Elastic Archwires — Upper Assortment Pack',
        sku: 'SOL-NITI-SE-U-ASST',
        quantity: 25,
        unitPrice: 42.00,
        discount: 4.20,
        lineTotal: 945.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-032',
        productName: 'Nitinol Super Elastic Archwires — Lower Assortment Pack',
        sku: 'SOL-NITI-SE-L-ASST',
        quantity: 25,
        unitPrice: 42.00,
        discount: 4.20,
        lineTotal: 945.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-033',
        productName: 'Beta Titanium (TMA) Archwires — Assorted Pack',
        sku: 'SOL-TMA-ASST',
        quantity: 15,
        unitPrice: 68.00,
        discount: 6.80,
        lineTotal: 918.0,
      },
      {
        lineNumber: 4,
        productId: 'PRD-031',
        productName: 'Stainless Steel Archwires — Upper Assortment Pack',
        sku: 'SOL-SS-U-ASST',
        quantity: 20,
        unitPrice: 28.00,
        discount: 2.80,
        lineTotal: 504.0,
      },
    ],
    pricing: {
      subtotal: 3312.0,
      discount: 360.0,
      tax: 250.62,
      freight: 15.00,
      total: 3217.62,
      currency: 'USD',
    },
    shipTo: {
      name: 'Bright Smiles Orthodontics — Satellite Office',
      street: '3000 Mack Rd',
      building: 'Suite 110',
      city: 'Fairfield',
      state: 'OH',
      zip: '45014',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-01-10T00:00:00Z',
    contractId: 'CTR-003',
    notes: 'Ship to satellite office. Full archwire inventory for new location.',
  },
  {
    biId: 'ORD-2025-0010',
    biName: 'Chen Ortho — Clarity Aligner Case Batch',
    biDescription: 'Clarity Aligner case credits for Q1 2025 patient starts.',
    status: 'Confirmed',
    priority: 'High',
    biCreatedAt: '2024-12-20T15:00:00Z',
    biUpdatedAt: '2025-01-10T08:00:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-021',
        productName: 'Clarity Aligner Case Credit Pack (25 cases)',
        sku: 'SOL-CLR-ALN-25',
        quantity: 4,
        unitPrice: 3750.0,
        discount: 375.0,
        lineTotal: 13500.0,
        configuration: 'Includes unlimited refinements per case',
      },
    ],
    pricing: {
      subtotal: 13500.0,
      discount: 1500.0,
      tax: 1020.0,
      freight: 0,
      total: 13020.0,
      currency: 'USD',
    },
    shipTo: {
      name: 'Chen Orthodontics',
      street: '1200 Madison Ave',
      building: 'Suite 300, Front Desk',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-01-15T00:00:00Z',
    contractId: 'CTR-001',
    notes: 'Digital delivery — case credits applied to Clarity portal account.',
  },
  {
    biId: 'ORD-2024-0011',
    biName: 'Lakeside Ortho — Prevention & Hygiene Supplies',
    biDescription: 'Fluoride varnish and patient hygiene kits for orthodontic patients.',
    status: 'Invoiced',
    priority: 'Standard',
    biCreatedAt: '2024-08-12T11:00:00Z',
    biUpdatedAt: '2024-09-30T14:00:00Z',
    biCompletedAt: '2024-09-25T16:45:00Z',
    customer: {
      id: 'ORG-005',
      name: 'Lakeside Family Orthodontics',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@lakesideortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-060',
        productName: 'Clinpro 5000 Fluoride Toothpaste (4 oz, 24pk)',
        sku: 'SOL-CP5000-24',
        quantity: 4,
        unitPrice: 185.0,
        discount: 0,
        lineTotal: 740.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-061',
        productName: 'Clinpro White Varnish with TCP (50pk)',
        sku: 'SOL-CPWV-50',
        quantity: 3,
        unitPrice: 125.0,
        discount: 0,
        lineTotal: 375.0,
      },
    ],
    pricing: {
      subtotal: 1115.0,
      discount: 0,
      tax: 94.78,
      freight: 9.95,
      total: 1219.73,
      currency: 'USD',
    },
    shipTo: {
      name: 'Lakeside Family Orthodontics',
      street: '2501 Mountain View Dr',
      building: 'Suite 102, Front Office',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2024-09-15T00:00:00Z',
    contractId: 'CTR-005',
    notes: null,
  },
  {
    biId: 'ORD-2024-0012',
    biName: 'Smile DSO — Instrument Kit Bulk Order',
    biDescription: 'Ortho hand instruments and plier sets for new location openings.',
    status: 'Delivered',
    priority: 'Standard',
    biCreatedAt: '2024-10-01T13:30:00Z',
    biUpdatedAt: '2024-10-18T08:00:00Z',
    biCompletedAt: '2024-10-18T08:00:00Z',
    customer: {
      id: 'ORG-002',
      name: 'Smile DSO Group',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@smiledsogroup.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-045',
        productName: 'Ortho Plier Set — Essentials (8-piece)',
        sku: 'SOL-PLIER-ESS-8',
        quantity: 8,
        unitPrice: 485.0,
        discount: 48.50,
        lineTotal: 3492.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-046',
        productName: 'Bracket Placement Instrument Set (5-piece)',
        sku: 'SOL-BRK-INST-5',
        quantity: 8,
        unitPrice: 225.0,
        discount: 22.50,
        lineTotal: 1620.0,
      },
    ],
    pricing: {
      subtotal: 5112.0,
      discount: 568.0,
      tax: 0.0,
      freight: 25.00,
      total: 4569.00,
      currency: 'USD',
    },
    shipTo: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      building: 'Loading Dock, Suite 100',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
      country: 'US',
    },
    paymentTerms: 'Net 45',
    requestedDeliveryDate: '2024-10-15T00:00:00Z',
    contractId: 'CTR-002',
    notes: 'Tax exempt on file. Distribute to new locations per internal allocation.',
  },
  {
    biId: 'ORD-2025-0013',
    biName: 'Bright Smiles — Bracket & Bonding Monthly Restock',
    biDescription: 'Monthly replenishment of ceramic and metal brackets with bonding supplies.',
    status: 'Submitted',
    priority: 'Standard',
    biCreatedAt: '2025-01-13T14:15:00Z',
    biUpdatedAt: '2025-01-13T14:15:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-003',
      name: 'Bright Smiles Orthodontics',
      contactName: 'Dr. Michael Thompson',
      contactEmail: 'm.thompson@brightsmiles.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        sku: 'SOL-CLR-ADV-U5',
        quantity: 10,
        unitPrice: 189.0,
        discount: 0,
        lineTotal: 1890.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-005',
        productName: 'Victory Series Metal Brackets — Upper 5x5 Kit',
        sku: 'SOL-VIC-MTL-U5',
        quantity: 15,
        unitPrice: 85.0,
        discount: 0,
        lineTotal: 1275.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        sku: 'SOL-TBXT-SYR-KIT',
        quantity: 6,
        unitPrice: 82.50,
        discount: 0,
        lineTotal: 495.0,
      },
    ],
    pricing: {
      subtotal: 3660.0,
      discount: 0,
      tax: 311.10,
      freight: 14.95,
      total: 3986.05,
      currency: 'USD',
    },
    shipTo: {
      name: 'Bright Smiles Orthodontics',
      street: '615 Elsinore Pl',
      building: 'Suite 200, Reception',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-02-01T00:00:00Z',
    contractId: 'CTR-003',
    notes: 'Pending inventory count confirmation from office manager.',
  },
  {
    biId: 'ORD-2024-0014',
    biName: 'Metro Dental — Aligner Evaluation',
    biDescription: 'Clarity Aligner trial pack for clinical evaluation.',
    status: 'Cancelled',
    priority: 'Standard',
    biCreatedAt: '2024-11-01T09:00:00Z',
    biUpdatedAt: '2024-11-15T11:30:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-004',
      name: 'Metro Dental Partners',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@metrodentalpartners.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-020',
        productName: 'Clarity Aligner System — Practice Starter Kit',
        sku: 'SOL-CLR-ALN-START',
        quantity: 1,
        unitPrice: 4500.0,
        discount: 0,
        lineTotal: 4500.0,
      },
    ],
    pricing: {
      subtotal: 4500.0,
      discount: 0,
      tax: 382.50,
      freight: 0,
      total: 4882.50,
      currency: 'USD',
    },
    shipTo: {
      name: 'Metro Dental Partners',
      street: '900 Pacific Ave',
      building: 'Suite 200, Supply Room',
      city: 'Tacoma',
      state: 'WA',
      zip: '98402',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2024-11-20T00:00:00Z',
    contractId: null,
    notes: 'Cancelled — customer decided to evaluate competitor aligner system first.',
  },
  {
    biId: 'ORD-2025-0015',
    biName: 'Lakeside Ortho — Full Bracket & Supply Restock',
    biDescription: 'Complete practice supply reorder including brackets, bonding, and archwires.',
    status: 'Draft',
    priority: 'Standard',
    biCreatedAt: '2025-01-15T08:00:00Z',
    biUpdatedAt: '2025-01-15T08:00:00Z',
    biCompletedAt: null,
    customer: {
      id: 'ORG-005',
      name: 'Lakeside Family Orthodontics',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@lakesideortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        sku: 'SOL-CLR-ADV-U5',
        quantity: 8,
        unitPrice: 189.0,
        discount: 0,
        lineTotal: 1512.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-005',
        productName: 'Victory Series Metal Brackets — Upper 5x5 Kit',
        sku: 'SOL-VIC-MTL-U5',
        quantity: 12,
        unitPrice: 85.0,
        discount: 0,
        lineTotal: 1020.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-030',
        productName: 'Nitinol Super Elastic Archwires — Upper Assortment Pack',
        sku: 'SOL-NITI-SE-U-ASST',
        quantity: 10,
        unitPrice: 42.00,
        discount: 0,
        lineTotal: 420.0,
      },
    ],
    pricing: {
      subtotal: 2952.0,
      discount: 0,
      tax: 250.92,
      freight: 14.95,
      total: 3217.87,
      currency: 'USD',
    },
    shipTo: {
      name: 'Lakeside Family Orthodontics',
      street: '2501 Mountain View Dr',
      building: 'Suite 102, Front Office',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
      country: 'US',
    },
    paymentTerms: 'Net 30',
    requestedDeliveryDate: '2025-02-28T00:00:00Z',
    contractId: 'CTR-005',
    notes: 'Draft pending quote conversion. See QT-2025-0008.',
  },
];

export const getOrderById = (biId) => orders.find((o) => o.biId === biId);
export const getOrdersByStatus = (status) => orders.filter((o) => o.status === status);
export const getOrdersByCustomer = (customerId) =>
  orders.filter((o) => o.customer.id === customerId);

export const orderStatuses = [
  'Draft',
  'Submitted',
  'Confirmed',
  'Shipped',
  'Delivered',
  'Invoiced',
  'Cancelled',
];

export default orders;
