// Mock organizations/parties for Solventum Ortho Portal
// Types: orthodontic_practice, dso, manufacturer

export const parties = [
  {
    id: 'ORG-001',
    name: 'Chen Orthodontics',
    type: 'orthodontic_practice',
    taxId: '91-1234567',
    dunsNumber: '012345678',
    website: 'https://www.chenortho.com',
    primaryContact: {
      name: 'Dr. Sarah Chen',
      title: 'Owner / Orthodontist',
      email: 'sarah.chen@chenortho.com',
      phone: '+1 (206) 555-0142',
    },
    billingContact: {
      name: 'Karen Liu',
      title: 'Office Manager',
      email: 'billing@chenortho.com',
      phone: '+1 (206) 555-0155',
    },
    addresses: {
      headquarters: {
        street: '1200 Madison Ave',
        suite: 'Suite 300',
        city: 'Seattle',
        state: 'WA',
        zip: '98104',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-CHN-01',
          label: 'Main Office',
          street: '1200 Madison Ave',
          building: 'Suite 300, Front Desk',
          city: 'Seattle',
          state: 'WA',
          zip: '98104',
          country: 'US',
          isDefault: true,
        },
      ],
    },
    classification: {
      practiceSize: 'Medium',
      operatories: 6,
      orthodontists: 2,
      specialties: ['Orthodontics', 'Pediatric Dentistry'],
      patientVolume: '180 starts/year',
    },
    contractId: 'CTR-001',
    tierLevel: 'Gold',
    tierProgress: 82,
    annualSpend: 124500.0,
    paymentTerms: 'Net 30',
    creditLimit: 75000.0,
    creditStatus: 'Approved',
    accountStatus: 'Active',
    createdAt: '2021-06-15T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-002',
    name: 'Smile DSO Group',
    type: 'dso',
    taxId: '36-9876543',
    dunsNumber: '987654321',
    website: 'https://www.smiledsogroup.com',
    primaryContact: {
      name: 'James Mitchell',
      title: 'VP of Procurement',
      email: 'j.mitchell@smiledsogroup.com',
      phone: '+1 (312) 555-0287',
    },
    billingContact: {
      name: 'Patricia Gomez',
      title: 'Director of Finance',
      email: 'finance@smiledsogroup.com',
      phone: '+1 (312) 555-0290',
    },
    addresses: {
      headquarters: {
        street: '4500 W Diversey Ave',
        suite: 'Suite 800',
        city: 'Chicago',
        state: 'IL',
        zip: '60639',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-SDG-01',
          label: 'Central Distribution',
          street: '4500 W Diversey Ave',
          building: 'Loading Dock, Suite 100',
          city: 'Chicago',
          state: 'IL',
          zip: '60639',
          country: 'US',
          isDefault: true,
        },
        {
          id: 'SHIP-SDG-02',
          label: 'East Region Office',
          street: '200 Industrial Pkwy',
          building: 'Suite 150',
          city: 'Edison',
          state: 'NJ',
          zip: '08817',
          country: 'US',
          isDefault: false,
        },
      ],
    },
    classification: {
      practiceSize: 'Enterprise',
      locations: 12,
      orthodontists: 18,
      specialties: ['Orthodontics', 'General Dentistry', 'Pediatric Dentistry'],
      patientVolume: '2,400 starts/year',
    },
    contractId: 'CTR-002',
    tierLevel: 'Platinum',
    tierProgress: 95,
    annualSpend: 487200.0,
    paymentTerms: 'Net 45',
    creditLimit: 350000.0,
    creditStatus: 'Approved',
    accountStatus: 'Active',
    createdAt: '2019-03-01T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-003',
    name: 'Bright Smiles Orthodontics',
    type: 'orthodontic_practice',
    taxId: '31-5678901',
    dunsNumber: '567890123',
    website: 'https://www.brightsmiles.com',
    primaryContact: {
      name: 'Dr. Michael Thompson',
      title: 'Owner / Orthodontist',
      email: 'm.thompson@brightsmiles.com',
      phone: '+1 (513) 555-0361',
    },
    billingContact: {
      name: 'Robert Daniels',
      title: 'Practice Administrator',
      email: 'admin@brightsmiles.com',
      phone: '+1 (513) 555-0375',
    },
    addresses: {
      headquarters: {
        street: '615 Elsinore Pl',
        suite: 'Suite 200',
        city: 'Cincinnati',
        state: 'OH',
        zip: '45202',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-BSO-01',
          label: 'Main Office',
          street: '615 Elsinore Pl',
          building: 'Suite 200, Reception',
          city: 'Cincinnati',
          state: 'OH',
          zip: '45202',
          country: 'US',
          isDefault: true,
        },
        {
          id: 'SHIP-BSO-02',
          label: 'Satellite Office',
          street: '3000 Mack Rd',
          building: 'Suite 110',
          city: 'Fairfield',
          state: 'OH',
          zip: '45014',
          country: 'US',
          isDefault: false,
        },
      ],
    },
    classification: {
      practiceSize: 'Large',
      operatories: 10,
      orthodontists: 3,
      specialties: ['Orthodontics'],
      patientVolume: '320 starts/year',
    },
    contractId: 'CTR-003',
    tierLevel: 'Silver',
    tierProgress: 64,
    annualSpend: 78300.0,
    paymentTerms: 'Net 30',
    creditLimit: 50000.0,
    creditStatus: 'Approved',
    accountStatus: 'Active',
    createdAt: '2022-01-10T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-004',
    name: 'Metro Dental Partners',
    type: 'dso',
    taxId: '91-2345678',
    dunsNumber: '234567890',
    website: 'https://www.metrodentalpartners.com',
    primaryContact: {
      name: 'Dr. Robert Kim',
      title: 'Chief Clinical Officer',
      email: 'r.kim@metrodentalpartners.com',
      phone: '+1 (253) 555-0198',
    },
    billingContact: {
      name: 'Jennifer Walsh',
      title: 'Controller',
      email: 'billing@metrodentalpartners.com',
      phone: '+1 (253) 555-0200',
    },
    addresses: {
      headquarters: {
        street: '900 Pacific Ave',
        suite: 'Suite 200',
        city: 'Tacoma',
        state: 'WA',
        zip: '98402',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-MDP-01',
          label: 'Main Office',
          street: '900 Pacific Ave',
          building: 'Suite 200, Supply Room',
          city: 'Tacoma',
          state: 'WA',
          zip: '98402',
          country: 'US',
          isDefault: true,
        },
      ],
    },
    classification: {
      practiceSize: 'Mid-Market DSO',
      locations: 5,
      orthodontists: 7,
      specialties: ['Orthodontics', 'General Dentistry'],
      patientVolume: '900 starts/year',
    },
    contractId: 'CTR-004',
    tierLevel: 'Bronze',
    tierProgress: 38,
    annualSpend: 34800.0,
    paymentTerms: 'Net 30',
    creditLimit: 30000.0,
    creditStatus: 'Under Review',
    accountStatus: 'Active',
    createdAt: '2023-09-20T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-005',
    name: 'Lakeside Family Orthodontics',
    type: 'orthodontic_practice',
    taxId: '93-3456789',
    dunsNumber: '345678901',
    website: 'https://www.lakesideortho.com',
    primaryContact: {
      name: 'Dr. Amanda Foster',
      title: 'Owner / Orthodontist',
      email: 'a.foster@lakesideortho.com',
      phone: '+1 (541) 555-0130',
    },
    billingContact: {
      name: 'Steven Moore',
      title: 'Office Manager',
      email: 's.moore@lakesideortho.com',
      phone: '+1 (541) 555-0135',
    },
    addresses: {
      headquarters: {
        street: '2501 Mountain View Dr',
        suite: 'Suite 102',
        city: 'Bend',
        state: 'OR',
        zip: '97701',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-LFO-01',
          label: 'Main Office',
          street: '2501 Mountain View Dr',
          building: 'Suite 102, Front Office',
          city: 'Bend',
          state: 'OR',
          zip: '97701',
          country: 'US',
          isDefault: true,
        },
      ],
    },
    classification: {
      practiceSize: 'Small',
      operatories: 4,
      orthodontists: 1,
      specialties: ['Orthodontics', 'Dentofacial Orthopedics'],
      patientVolume: '100 starts/year',
    },
    contractId: 'CTR-005',
    tierLevel: 'Silver',
    tierProgress: 45,
    annualSpend: 52100.0,
    paymentTerms: 'Net 30',
    creditLimit: 25000.0,
    creditStatus: 'Approved',
    accountStatus: 'Active',
    createdAt: '2023-04-01T00:00:00Z',
    salesRepId: 'USR-003',
  },
  {
    id: 'ORG-SOL',
    name: 'Solventum Corporation',
    type: 'manufacturer',
    taxId: '41-2816982',
    dunsNumber: '005168640',
    website: 'https://www.solventum.com',
    primaryContact: {
      name: 'Emily Rodriguez',
      title: 'Regional Sales Manager — Pacific Northwest / Midwest',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    billingContact: null,
    addresses: {
      headquarters: {
        street: '3M Center',
        city: 'Maplewood',
        state: 'MN',
        zip: '55144',
        country: 'US',
      },
      shipping: [
        {
          id: 'SHIP-SOL-01',
          label: 'Distribution Center — Central',
          street: '2510 Conway Ave',
          city: 'St. Paul',
          state: 'MN',
          zip: '55114',
          country: 'US',
          isDefault: true,
        },
        {
          id: 'SHIP-SOL-02',
          label: 'Distribution Center — West',
          street: '5900 Optical Ct',
          city: 'San Jose',
          state: 'CA',
          zip: '95138',
          country: 'US',
          isDefault: false,
        },
      ],
    },
    classification: {
      employees: 22000,
      divisions: ['Orthodontics', 'Dental Solutions', 'Health Information Systems', 'Medical Surgical', 'Purification & Filtration'],
      stockTicker: 'SOLV',
      exchange: 'NYSE',
    },
    contractId: null,
    tierLevel: null,
    tierProgress: null,
    annualSpend: null,
    paymentTerms: null,
    creditLimit: null,
    creditStatus: null,
    accountStatus: 'Active',
    createdAt: '2024-04-01T00:00:00Z',
    salesRepId: null,
  },
];

export const getPartyById = (id) => parties.find((p) => p.id === id);
export const getPartiesByType = (type) => parties.filter((p) => p.type === type);

export const partyTypes = [
  'orthodontic_practice',
  'dso',
  'manufacturer',
];

export default parties;
