// Mock promotions for Solventum Ortho Portal
// Types: bundle | volume_discount | seasonal | loyalty
// Discount types: percentage | fixed | free_product

export const promotions = [
  {
    id: 'PROMO-001',
    name: 'Clarity Aligner Launch Bundle',
    description: 'Get 20% off your first 10 Clarity Aligner cases when you sign up for the Clarity Partner Program. Includes complimentary onboarding webinar and dedicated case support for your first five submissions.',
    type: 'bundle',
    status: 'Active',
    discountType: 'percentage',
    discountValue: 20,
    eligibleProducts: ['PRD-026', 'PRD-027'],
    eligibleTiers: ['Gold', 'Platinum'],
    code: 'CLARITY2026',
    validFrom: '2026-01-01T00:00:00Z',
    validUntil: '2026-06-30T00:00:00Z',
    minOrderValue: 5000,
    maxUsesPerCustomer: 1,
    totalUsed: 23,
    maxTotalUses: 100,
    createdAt: '2025-12-15T00:00:00Z',
  },
  {
    id: 'PROMO-002',
    name: 'Volume Bracket Discount',
    description: 'Purchase 20 or more bracket kits in a single order and receive 10% off the entire bracket portion of your order. Applies to all Clarity Advanced, Clarity Ultra, and APC Flash-Free bracket systems. Stackable with existing contract pricing for Platinum tier accounts.',
    type: 'volume_discount',
    status: 'Active',
    discountType: 'percentage',
    discountValue: 10,
    eligibleProducts: ['PRD-001', 'PRD-002', 'PRD-003', 'PRD-004', 'PRD-005', 'PRD-006', 'PRD-007', 'PRD-040', 'PRD-041', 'PRD-042'],
    eligibleTiers: ['Bronze', 'Silver', 'Gold', 'Platinum'],
    code: 'BRACKETS20',
    validFrom: '2026-01-15T00:00:00Z',
    validUntil: '2026-12-31T00:00:00Z',
    minOrderValue: 0,
    minQuantity: 20,
    maxUsesPerCustomer: 4,
    totalUsed: 57,
    maxTotalUses: 500,
    createdAt: '2026-01-05T00:00:00Z',
  },
  {
    id: 'PROMO-003',
    name: 'Spring Practice Startup',
    description: 'Kick off the spring season with 15% off our Bonding Essentials Kit. Includes Transbond XT, Transbond Plus Color Change Adhesive, and Transbond Supreme LV — everything you need to streamline your bonding workflow. Perfect for new practices or offices looking to standardize on Solventum bonding systems.',
    type: 'seasonal',
    status: 'Active',
    discountType: 'percentage',
    discountValue: 15,
    eligibleProducts: ['PRD-016', 'PRD-017', 'PRD-018', 'PRD-019', 'PRD-020'],
    eligibleTiers: ['Bronze', 'Silver', 'Gold', 'Platinum'],
    code: 'SPRING2026',
    validFrom: '2026-02-01T00:00:00Z',
    validUntil: '2026-03-31T00:00:00Z',
    minOrderValue: 250,
    maxUsesPerCustomer: 2,
    totalUsed: 41,
    maxTotalUses: 200,
    createdAt: '2026-01-20T00:00:00Z',
  },
  {
    id: 'PROMO-004',
    name: 'Loyalty Reward — Free Archwire Sample Pack',
    description: 'Receive a complimentary archwire sample pack (includes Nitinol Heat-Activated, Beta-Titanium, and Stainless Steel archwire assortments) with any order of $500 or more. Our way of saying thank you for your continued partnership with Solventum Orthodontics.',
    type: 'loyalty',
    status: 'Active',
    discountType: 'free_product',
    discountValue: 0,
    freeProductDetails: {
      productId: 'PRD-035',
      productName: 'Archwire Sample Assortment Pack',
      estimatedRetailValue: 89.00,
      contents: [
        'Nitinol Heat-Activated Archwires (6-pack assorted)',
        'Beta-Titanium Archwires (4-pack assorted)',
        'Unitek Stainless Steel Archwires (6-pack assorted)',
      ],
    },
    eligibleProducts: [],
    eligibleTiers: ['Silver', 'Gold', 'Platinum'],
    code: 'LOYALWIRE',
    validFrom: '2026-01-01T00:00:00Z',
    validUntil: '2026-04-30T00:00:00Z',
    minOrderValue: 500,
    maxUsesPerCustomer: 1,
    totalUsed: 89,
    maxTotalUses: 250,
    createdAt: '2025-12-20T00:00:00Z',
  },
];

export const getPromotionById = (id) => promotions.find((p) => p.id === id);
export const getActivePromotions = () => promotions.filter((p) => p.status === 'Active');
export const getPromotionsByProduct = (productId) => promotions.filter((p) => p.eligibleProducts.includes(productId));
export default promotions;
