// Mock quotes for Solventum Ortho Portal
// Statuses: Draft, Submitted, Approved, Rejected, Converted

export const quotes = [
  {
    biId: 'QT-2025-0001',
    biName: 'Chen Ortho — Annual Bracket Supply Agreement',
    biDescription: 'Comprehensive annual pricing agreement for Clarity Advanced and Victory brackets with volume discounts.',
    status: 'Converted',
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        quantity: 200,
        unitPrice: 189.0,
        discount: 18.90,
        lineTotal: 34020.0,
        notes: 'Annual estimate: ~200 kits. 10% volume discount.',
      },
      {
        lineNumber: 2,
        productId: 'PRD-002',
        productName: 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit',
        quantity: 200,
        unitPrice: 189.0,
        discount: 18.90,
        lineTotal: 34020.0,
        notes: 'Annual estimate: ~200 kits. 10% volume discount.',
      },
      {
        lineNumber: 3,
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        quantity: 100,
        unitPrice: 82.50,
        discount: 8.25,
        lineTotal: 7425.0,
      },
    ],
    pricing: {
      subtotal: 75465.0,
      discount: 9210.0,
      tax: 5627.17,
      freight: 0,
      total: 71882.17,
      currency: 'USD',
    },
    validFrom: '2024-12-01T00:00:00Z',
    validUntil: '2025-02-28T00:00:00Z',
    createdAt: '2024-12-01T10:00:00Z',
    updatedAt: '2025-01-02T09:15:00Z',
    convertedToOrderId: 'ORD-2025-0001',
    contractId: 'CTR-001',
    termsAndConditions: 'Annual pricing agreement. Orders placed at quoted prices throughout calendar year. Volume discount applies to cumulative purchases.',
    notes: 'Converted to first order ORD-2025-0001 on Jan 2, 2025. Annual agreement pricing locked.',
  },
  {
    biId: 'QT-2025-0002',
    biName: 'Bright Smiles — Clarity Aligner Expansion',
    biDescription: 'Additional Clarity Aligner case credits with volume pricing for growing aligner practice.',
    status: 'Approved',
    customer: {
      id: 'ORG-003',
      name: 'Bright Smiles Orthodontics',
      contactName: 'Dr. Michael Thompson',
      contactEmail: 'm.thompson@brightsmiles.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-021',
        productName: 'Clarity Aligner Case Credit Pack (25 cases)',
        quantity: 4,
        unitPrice: 3750.0,
        discount: 375.0,
        lineTotal: 13500.0,
        notes: '100 cases total. 10% volume discount at 100+ tier.',
      },
      {
        lineNumber: 2,
        productId: 'PRD-022',
        productName: 'Clarity Aligner Retainer Credit Pack (25 sets)',
        sku: 'SOL-CLR-RET-25',
        quantity: 2,
        unitPrice: 1250.0,
        discount: 125.0,
        lineTotal: 2250.0,
        notes: '50 retainer sets for aligner patients.',
      },
    ],
    pricing: {
      subtotal: 15750.0,
      discount: 2000.0,
      tax: 1168.75,
      freight: 0,
      total: 14918.75,
      currency: 'USD',
    },
    validFrom: '2025-01-01T00:00:00Z',
    validUntil: '2025-03-31T00:00:00Z',
    createdAt: '2025-01-03T14:00:00Z',
    updatedAt: '2025-01-10T11:30:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-003',
    termsAndConditions: 'Volume discount pricing. Credits valid for 12 months from activation. Unlimited refinements included.',
    notes: 'Approved by practice administrator. Awaiting PO from Dr. Thompson.',
  },
  {
    biId: 'QT-2025-0003',
    biName: 'Smile DSO — Q1 2025 Enterprise Restock',
    biDescription: 'Quarterly enterprise pricing proposal for brackets, bonding, and archwires across all 12 locations.',
    status: 'Submitted',
    customer: {
      id: 'ORG-002',
      name: 'Smile DSO Group',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@smiledsogroup.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-003',
        productName: 'Clarity Ultra Self-Ligating Brackets — Upper Kit',
        quantity: 120,
        unitPrice: 245.0,
        discount: 36.75,
        lineTotal: 24990.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-004',
        productName: 'Clarity Ultra Self-Ligating Brackets — Lower Kit',
        quantity: 120,
        unitPrice: 245.0,
        discount: 36.75,
        lineTotal: 24990.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        quantity: 144,
        unitPrice: 82.50,
        discount: 16.50,
        lineTotal: 9504.0,
      },
      {
        lineNumber: 4,
        productId: 'PRD-030',
        productName: 'Nitinol Super Elastic Archwires — Upper Assortment Pack',
        quantity: 200,
        unitPrice: 42.00,
        discount: 8.40,
        lineTotal: 6720.0,
      },
    ],
    pricing: {
      subtotal: 66204.0,
      discount: 11844.0,
      tax: 0.0,
      freight: 0,
      total: 54360.0,
      currency: 'USD',
    },
    validFrom: '2025-01-15T00:00:00Z',
    validUntil: '2025-03-15T00:00:00Z',
    createdAt: '2025-01-12T09:00:00Z',
    updatedAt: '2025-01-12T09:00:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-002',
    termsAndConditions: 'Platinum tier enterprise pricing. 15% volume discount applied. Tax exempt — resale certificate on file.',
    notes: 'Submitted to James Mitchell for review. Platinum enterprise discount proposed.',
  },
  {
    biId: 'QT-2025-0004',
    biName: 'Metro Dental — Ortho Practice Startup Kit',
    biDescription: 'Complete orthodontic practice startup package for new Metro Dental ortho locations.',
    status: 'Draft',
    customer: {
      id: 'ORG-004',
      name: 'Metro Dental Partners',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@metrodentalpartners.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        quantity: 30,
        unitPrice: 189.0,
        discount: 0,
        lineTotal: 5670.0,
        notes: 'Startup inventory for 3 locations',
      },
      {
        lineNumber: 2,
        productId: 'PRD-005',
        productName: 'Victory Series Metal Brackets — Upper 5x5 Kit',
        quantity: 50,
        unitPrice: 85.0,
        discount: 0,
        lineTotal: 4250.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-050',
        productName: 'Ortholux Luminous LED Curing Light',
        quantity: 3,
        unitPrice: 1850.0,
        discount: 0,
        lineTotal: 5550.0,
        notes: 'One per new operatory',
      },
    ],
    pricing: {
      subtotal: 15470.0,
      discount: 0,
      tax: 1314.95,
      freight: 45.00,
      total: 16829.95,
      currency: 'USD',
    },
    validFrom: '2025-01-15T00:00:00Z',
    validUntil: '2025-04-15T00:00:00Z',
    createdAt: '2025-01-14T16:30:00Z',
    updatedAt: '2025-01-14T16:30:00Z',
    convertedToOrderId: null,
    contractId: null,
    termsAndConditions: 'Standard terms. New account pricing — volume discounts available upon contract signing.',
    notes: 'Draft — awaiting clinical evaluation feedback from Dr. Kim.',
  },
  {
    biId: 'QT-2025-0005',
    biName: 'Lakeside Ortho — Comprehensive Supply Agreement',
    biDescription: 'Annual supply agreement covering brackets, archwires, bonding, and prevention products.',
    status: 'Approved',
    customer: {
      id: 'ORG-005',
      name: 'Lakeside Family Orthodontics',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@lakesideortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        quantity: 80,
        unitPrice: 189.0,
        discount: 18.90,
        lineTotal: 13608.0,
        notes: 'Annual estimate for ceramic bracket patients',
      },
      {
        lineNumber: 2,
        productId: 'PRD-005',
        productName: 'Victory Series Metal Brackets — Upper 5x5 Kit',
        quantity: 120,
        unitPrice: 85.0,
        discount: 8.50,
        lineTotal: 9180.0,
        notes: 'Annual estimate for metal bracket patients',
      },
      {
        lineNumber: 3,
        productId: 'PRD-030',
        productName: 'Nitinol Super Elastic Archwires — Upper Assortment Pack',
        quantity: 80,
        unitPrice: 42.00,
        discount: 4.20,
        lineTotal: 3024.0,
      },
    ],
    pricing: {
      subtotal: 25812.0,
      discount: 3066.0,
      tax: 1933.36,
      freight: 0,
      total: 24679.36,
      currency: 'USD',
    },
    validFrom: '2025-01-05T00:00:00Z',
    validUntil: '2025-04-05T00:00:00Z',
    createdAt: '2025-01-05T11:00:00Z',
    updatedAt: '2025-01-13T15:45:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-005',
    termsAndConditions: 'Silver tier pricing. 10% discount on brackets. Free shipping on orders over $500.',
    notes: 'Approved. PO expected by end of January.',
  },
  {
    biId: 'QT-2024-0006',
    biName: 'Bright Smiles — Digital Orthodontics Package',
    biDescription: 'Clarity scanner and aligner system bundle for digital workflow upgrade.',
    status: 'Rejected',
    customer: {
      id: 'ORG-003',
      name: 'Bright Smiles Orthodontics',
      contactName: 'Dr. Michael Thompson',
      contactEmail: 'm.thompson@brightsmiles.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-052',
        productName: 'Clarity Intraoral Scanner System',
        quantity: 1,
        unitPrice: 24500.0,
        discount: 0,
        lineTotal: 24500.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-020',
        productName: 'Clarity Aligner System — Practice Starter Kit',
        quantity: 1,
        unitPrice: 4500.0,
        discount: 0,
        lineTotal: 4500.0,
      },
    ],
    pricing: {
      subtotal: 29000.0,
      discount: 0,
      tax: 2465.0,
      freight: 0,
      total: 31465.0,
      currency: 'USD',
    },
    validFrom: '2024-10-01T00:00:00Z',
    validUntil: '2024-12-31T00:00:00Z',
    createdAt: '2024-10-01T09:30:00Z',
    updatedAt: '2024-11-20T14:00:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-003',
    termsAndConditions: 'Standard capital equipment terms. Scanner includes 1-year warranty.',
    notes: 'Rejected — budget constraints. Customer requested phased approach: aligner starter kit first, scanner in Q2 2025.',
  },
  {
    biId: 'QT-2025-0007',
    biName: 'Chen Ortho — Consignment Bracket Inventory',
    biDescription: 'Consignment stock proposal for Clarity Advanced bracket kits at practice.',
    status: 'Submitted',
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        quantity: 30,
        unitPrice: 189.0,
        discount: 18.90,
        lineTotal: 5103.0,
        notes: 'Consignment stock — billed on usage',
      },
      {
        lineNumber: 2,
        productId: 'PRD-002',
        productName: 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit',
        quantity: 30,
        unitPrice: 189.0,
        discount: 18.90,
        lineTotal: 5103.0,
        notes: 'Consignment stock — billed on usage',
      },
    ],
    pricing: {
      subtotal: 10206.0,
      discount: 1134.0,
      tax: 771.12,
      freight: 0.0,
      total: 9843.12,
      currency: 'USD',
    },
    validFrom: '2025-01-10T00:00:00Z',
    validUntil: '2025-04-10T00:00:00Z',
    createdAt: '2025-01-10T13:00:00Z',
    updatedAt: '2025-01-10T13:00:00Z',
    convertedToOrderId: null,
    contractId: 'CTR-001',
    termsAndConditions: 'Consignment agreement terms. Monthly usage audit required. 24-month shelf life minimum on brackets.',
    notes: 'Consignment model — bill on use. Monthly inventory reconciliation via portal.',
  },
  {
    biId: 'QT-2025-0008',
    biName: 'Lakeside Ortho — Full Practice Supply Restock',
    biDescription: 'Complete practice supply reorder including brackets, bonding, and archwires.',
    status: 'Draft',
    customer: {
      id: 'ORG-005',
      name: 'Lakeside Family Orthodontics',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@lakesideortho.com',
    },
    salesRep: {
      id: 'USR-003',
      name: 'Emily Rodriguez',
      email: 'emily.rodriguez@solventum.com',
      phone: '+1 (651) 555-0193',
    },
    items: [
      {
        lineNumber: 1,
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        quantity: 8,
        unitPrice: 189.0,
        discount: 0,
        lineTotal: 1512.0,
      },
      {
        lineNumber: 2,
        productId: 'PRD-005',
        productName: 'Victory Series Metal Brackets — Upper 5x5 Kit',
        quantity: 12,
        unitPrice: 85.0,
        discount: 0,
        lineTotal: 1020.0,
      },
      {
        lineNumber: 3,
        productId: 'PRD-030',
        productName: 'Nitinol Super Elastic Archwires — Upper Assortment Pack',
        quantity: 10,
        unitPrice: 42.00,
        discount: 0,
        lineTotal: 420.0,
      },
    ],
    pricing: {
      subtotal: 2952.0,
      discount: 0,
      tax: 250.92,
      freight: 14.95,
      total: 3217.87,
      currency: 'USD',
    },
    validFrom: '2025-01-15T00:00:00Z',
    validUntil: '2025-04-15T00:00:00Z',
    createdAt: '2025-01-15T08:00:00Z',
    updatedAt: '2025-01-15T08:00:00Z',
    convertedToOrderId: null,
    contractId: null,
    termsAndConditions: 'Standard terms. Volume discount to be negotiated with annual agreement.',
    notes: 'Draft — linked to ORD-2025-0015. Pending pricing review.',
  },
];

export const getQuoteById = (biId) => quotes.find((q) => q.biId === biId);
export const getQuotesByStatus = (status) => quotes.filter((q) => q.status === status);
export const getQuotesByCustomer = (customerId) =>
  quotes.filter((q) => q.customer.id === customerId);

export const quoteStatuses = ['Draft', 'Submitted', 'Approved', 'Rejected', 'Converted'];

export default quotes;
