// Mock RMA (Return Merchandise Authorization) records for Solventum Ortho Portal
// Statuses: Requested, Approved, In Transit, Received, Inspected, Credited, Denied

export const returns = [
  {
    id: 'RMA-2025-0001',
    orderId: 'ORD-2025-0002',
    status: 'Approved',
    type: 'Defective',
    requestDate: '2025-01-05T10:00:00Z',
    approvedDate: '2025-01-07T14:30:00Z',
    receivedDate: null,
    resolvedDate: null,
    customer: {
      id: 'ORG-002',
      name: 'Smile DSO Group',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@smiledsogroup.com',
    },
    items: [
      {
        productId: 'PRD-003',
        productName: 'Clarity Ultra Self-Ligating Brackets — Upper Kit',
        serialNumber: null,
        lotNumber: 'CLR-ULT-LOT-2024-1189',
        quantity: 3,
        reason: 'Bracket clip mechanism not engaging properly. Clips fail to close on wire — 3 kits from same lot affected.',
        unitValue: 245.0,
      },
    ],
    returnShipment: {
      carrier: 'UPS',
      trackingNumber: null,
      labelProvided: true,
      labelUrl: '/labels/rma/RMA-2025-0001.pdf',
    },
    resolution: {
      type: 'Replacement',
      creditAmount: null,
      replacementOrderId: null,
      notes: 'Approved for replacement. Prepaid return label sent. Quality team to inspect lot CLR-ULT-LOT-2024-1189.',
    },
    shipFromAddress: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
    },
    shipToAddress: {
      name: 'Solventum Returns Center',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    photos: [
      { id: 'PHT-001', name: 'broken-bracket-1.jpg', url: '/images/rma/broken-bracket-1.jpg', type: 'image/jpeg' },
      { id: 'PHT-002', name: 'broken-bracket-2.jpg', url: '/images/rma/broken-bracket-2.jpg', type: 'image/jpeg' },
    ],
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Customer reported 3 of 48 bracket kits defective from ORD-2025-0002. Same lot number.',
  },
  {
    id: 'RMA-2024-0002',
    orderId: null,
    status: 'Credited',
    type: 'Wrong Item',
    requestDate: '2024-11-10T09:00:00Z',
    approvedDate: '2024-11-12T11:00:00Z',
    receivedDate: '2024-11-20T14:00:00Z',
    resolvedDate: '2024-12-05T10:30:00Z',
    customer: {
      id: 'ORG-005',
      name: 'Lakeside Family Orthodontics',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@lakesideortho.com',
    },
    items: [
      {
        productId: 'PRD-030',
        productName: 'Nitinol Super Elastic Archwires — Upper Assortment Pack',
        serialNumber: null,
        lotNumber: 'NITI-LOT-2024-1887',
        quantity: 5,
        reason: 'Received .018 round instead of ordered .016 round. Packaging labeled .016 but contents are .018.',
        unitValue: 42.0,
      },
    ],
    returnShipment: {
      carrier: 'UPS',
      trackingNumber: '1Z999AA10923456001',
      labelProvided: true,
      labelUrl: '/labels/rma/RMA-2024-0002.pdf',
    },
    resolution: {
      type: 'Credit',
      creditAmount: 210.0,
      replacementOrderId: null,
      notes: 'Credit issued. Correct .016 archwires shipped separately. Mislabeled lot reported to quality.',
    },
    shipFromAddress: {
      name: 'Lakeside Family Orthodontics',
      street: '2501 Mountain View Dr',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
    },
    shipToAddress: {
      name: 'Solventum Returns Center',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    photos: [],
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Wrong archwire size shipped. Credit applied and correct product expedited.',
  },
  {
    id: 'RMA-2025-0003',
    orderId: null,
    status: 'Requested',
    type: 'Expired Product',
    requestDate: '2025-01-12T16:00:00Z',
    approvedDate: null,
    receivedDate: null,
    resolvedDate: null,
    customer: {
      id: 'ORG-003',
      name: 'Bright Smiles Orthodontics',
      contactName: 'Dr. Michael Thompson',
      contactEmail: 'm.thompson@brightsmiles.com',
    },
    items: [
      {
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        serialNumber: null,
        lotNumber: 'TBXT-LOT-2023-0412',
        quantity: 4,
        reason: 'Adhesive expired — lot date shows expiration Dec 2024. Product was received in August 2024 with only 4 months of shelf life remaining.',
        unitValue: 82.50,
      },
    ],
    returnShipment: {
      carrier: null,
      trackingNumber: null,
      labelProvided: false,
      labelUrl: null,
    },
    resolution: {
      type: null,
      creditAmount: null,
      replacementOrderId: null,
      notes: 'Pending review — checking shipment records for lot TBXT-LOT-2023-0412 to verify remaining shelf life at time of delivery.',
    },
    shipFromAddress: {
      name: 'Bright Smiles Orthodontics',
      street: '615 Elsinore Pl',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
    },
    shipToAddress: null,
    photos: [],
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Customer reports expired bonding adhesive. Minimum 12-month shelf life required at delivery per policy.',
  },
  {
    id: 'RMA-2024-0004',
    orderId: 'ORD-2025-0009',
    status: 'Inspected',
    type: 'Damaged in Transit',
    requestDate: '2024-12-20T08:30:00Z',
    approvedDate: '2024-12-20T15:00:00Z',
    receivedDate: '2025-01-03T10:00:00Z',
    resolvedDate: null,
    customer: {
      id: 'ORG-003',
      name: 'Bright Smiles Orthodontics',
      contactName: 'Dr. Michael Thompson',
      contactEmail: 'm.thompson@brightsmiles.com',
    },
    items: [
      {
        productId: 'PRD-033',
        productName: 'Beta Titanium (TMA) Archwires — Assorted Pack',
        serialNumber: null,
        batchNumber: 'TMA-LOT-2024-0503',
        quantity: 3,
        reason: 'Outer packaging crushed during shipping. Archwire packs deformed — wires kinked and unusable. 3 of 15 packs affected.',
        unitValue: 68.0,
      },
    ],
    returnShipment: {
      carrier: 'FedEx',
      trackingNumber: '7948 4401 2234',
      labelProvided: true,
      labelUrl: '/labels/rma/RMA-2024-0004.pdf',
    },
    resolution: {
      type: 'Replacement',
      creditAmount: null,
      replacementOrderId: null,
      notes: 'Received and inspected. Packaging damage confirmed — archwires bent beyond use. Replacement shipment being prepared. Carrier freight claim filed with FedEx.',
    },
    shipFromAddress: {
      name: 'Bright Smiles Orthodontics — Satellite Office',
      street: '3000 Mack Rd',
      city: 'Fairfield',
      state: 'OH',
      zip: '45014',
    },
    shipToAddress: {
      name: 'Solventum Returns Center',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    photos: [
      { id: 'PHT-003', name: 'crushed-packaging.jpg', url: '/images/rma/crushed-packaging.jpg', type: 'image/jpeg' },
      { id: 'PHT-004', name: 'bent-archwires.jpg', url: '/images/rma/bent-archwires.jpg', type: 'image/jpeg' },
      { id: 'PHT-005', name: 'shipping-label.jpg', url: '/images/rma/shipping-label.jpg', type: 'image/jpeg' },
    ],
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Freight claim filed with FedEx. Photos of damaged packaging and bent archwires on file.',
  },
  {
    id: 'RMA-2024-0005',
    orderId: null,
    status: 'Denied',
    type: 'Overstock Return',
    requestDate: '2024-10-15T11:00:00Z',
    approvedDate: null,
    receivedDate: null,
    resolvedDate: '2024-10-20T09:00:00Z',
    customer: {
      id: 'ORG-004',
      name: 'Metro Dental Partners',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@metrodentalpartners.com',
    },
    items: [
      {
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        serialNumber: null,
        lotNumber: 'CLR-ADV-LOT-2024-0601',
        quantity: 10,
        reason: 'Overstock — purchased in excess of patient demand. Ortho program scaling back at 2 locations. Requesting return for credit.',
        unitValue: 189.0,
      },
    ],
    returnShipment: {
      carrier: null,
      trackingNumber: null,
      labelProvided: false,
      labelUrl: null,
    },
    resolution: {
      type: 'Denied',
      creditAmount: 0,
      replacementOrderId: null,
      notes: 'Return denied — brackets are beyond the 60-day return window (purchased July 2024). Product is still within expiration. Recommend transferring inventory to other DSO locations.',
    },
    shipFromAddress: null,
    shipToAddress: null,
    photos: [],
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'Denied per return policy Section 3.1 — non-defective product returns must be within 60 days of purchase.',
  },
  {
    id: 'RMA-2025-0006',
    orderId: null,
    status: 'In Transit',
    type: 'Defective',
    requestDate: '2025-01-08T09:30:00Z',
    approvedDate: '2025-01-09T11:00:00Z',
    receivedDate: null,
    resolvedDate: null,
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    items: [
      {
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        serialNumber: null,
        lotNumber: 'CLR-ADV-LOT-2024-0889',
        quantity: 2,
        reason: 'Bracket base fracture during bonding — two kits had multiple brackets with pre-cracked ceramic bases. Brackets shattered when placing on tooth.',
        unitValue: 189.0,
      },
    ],
    returnShipment: {
      carrier: 'UPS',
      trackingNumber: '1Z999AA10923456099',
      labelProvided: true,
      labelUrl: '/labels/rma/RMA-2025-0006.pdf',
    },
    resolution: {
      type: 'Replacement',
      creditAmount: null,
      replacementOrderId: null,
      notes: 'Approved for replacement. Return in transit. Quality to inspect for manufacturing defect in ceramic base.',
    },
    shipFromAddress: {
      name: 'Chen Orthodontics',
      street: '1200 Madison Ave',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
    },
    shipToAddress: {
      name: 'Solventum Returns Center',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    photos: [],
    salesRep: { id: 'USR-003', name: 'Emily Rodriguez' },
    notes: 'High-priority customer. Expedite replacement. Dr. Chen reports this is second occurrence with this lot.',
  },
];

export const getReturnById = (id) => returns.find((r) => r.id === id);
export const getReturnsByStatus = (status) => returns.filter((r) => r.status === status);
export const getReturnsByCustomer = (customerId) =>
  returns.filter((r) => r.customer.id === customerId);

export const returnStatuses = [
  'Requested',
  'Approved',
  'In Transit',
  'Received',
  'Inspected',
  'Credited',
  'Denied',
];

export default returns;
