// Mock shipments for Solventum Ortho Portal
// Statuses: Processing, Picked Up, In Transit, Out for Delivery, Delivered, Exception

export const shipments = [
  {
    id: 'SHP-2025-0001',
    orderId: 'ORD-2025-0002',
    status: 'In Transit',
    carrier: 'UPS',
    trackingNumber: '1Z999AA10412345678',
    serviceLevel: 'UPS Ground',
    estimatedDelivery: '2025-01-18T00:00:00Z',
    actualDelivery: null,
    shipDate: '2025-01-08T14:30:00Z',
    shipFrom: {
      name: 'Solventum Distribution Center — Central',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    shipTo: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
    },
    items: [
      {
        productId: 'PRD-003',
        productName: 'Clarity Ultra Self-Ligating Brackets — Upper Kit',
        quantity: 48,
        serialNumbers: null,
        lotNumbers: ['CLR-ULT-LOT-2024-1189', 'CLR-ULT-LOT-2024-1190'],
      },
      {
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        quantity: 36,
        serialNumbers: null,
        lotNumbers: ['TBXT-LOT-2024-0875'],
      },
      {
        productId: 'PRD-012',
        productName: 'Transbond Plus SEP Single Dose Packets (100pk)',
        quantity: 24,
        serialNumbers: null,
        lotNumbers: ['TBSEP-LOT-2024-0341'],
      },
    ],
    packages: [
      { packageNumber: 1, weight: '18 lbs', dimensions: '24 x 18 x 12 in', description: 'Clarity Ultra brackets (24 kits)' },
      { packageNumber: 2, weight: '18 lbs', dimensions: '24 x 18 x 12 in', description: 'Clarity Ultra brackets (24 kits)' },
      { packageNumber: 3, weight: '12 lbs', dimensions: '18 x 12 x 10 in', description: 'Transbond adhesives and primers' },
    ],
    trackingHistory: [
      { timestamp: '2025-01-08T14:30:00Z', location: 'St. Paul, MN', status: 'Picked up' },
      { timestamp: '2025-01-09T06:15:00Z', location: 'Madison, WI', status: 'In transit — hub scan' },
      { timestamp: '2025-01-10T03:45:00Z', location: 'Rockford, IL', status: 'In transit — hub scan' },
    ],
    specialInstructions: 'Temperature sensitive adhesive products. Store between 36-77 degrees F.',
    insuranceValue: 16362.31,
  },
  {
    id: 'SHP-2025-0002',
    orderId: 'ORD-2025-0009',
    status: 'In Transit',
    carrier: 'FedEx',
    trackingNumber: '7948 2301 4567',
    serviceLevel: 'FedEx 2Day',
    estimatedDelivery: '2025-01-16T00:00:00Z',
    actualDelivery: null,
    shipDate: '2025-01-06T09:00:00Z',
    shipFrom: {
      name: 'Solventum Distribution Center — Central',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    shipTo: {
      name: 'Bright Smiles Orthodontics — Satellite Office',
      street: '3000 Mack Rd',
      city: 'Fairfield',
      state: 'OH',
      zip: '45014',
    },
    items: [
      {
        productId: 'PRD-030',
        productName: 'Nitinol Super Elastic Archwires — Upper Assortment Pack',
        quantity: 25,
        serialNumbers: null,
        lotNumbers: ['NITI-LOT-2024-2201'],
      },
      {
        productId: 'PRD-032',
        productName: 'Nitinol Super Elastic Archwires — Lower Assortment Pack',
        quantity: 25,
        serialNumbers: null,
        lotNumbers: ['NITI-LOT-2024-2202'],
      },
      {
        productId: 'PRD-033',
        productName: 'Beta Titanium (TMA) Archwires — Assorted Pack',
        quantity: 15,
        serialNumbers: null,
        lotNumbers: ['TMA-LOT-2024-0503'],
      },
      {
        productId: 'PRD-031',
        productName: 'Stainless Steel Archwires — Upper Assortment Pack',
        quantity: 20,
        serialNumbers: null,
        lotNumbers: ['SS-LOT-2024-1156'],
      },
    ],
    packages: [
      { packageNumber: 1, weight: '8 lbs', dimensions: '18 x 12 x 6 in', description: 'NiTi archwires (50 packs)' },
      { packageNumber: 2, weight: '6 lbs', dimensions: '18 x 12 x 6 in', description: 'TMA and SS archwires (35 packs)' },
    ],
    trackingHistory: [
      { timestamp: '2025-01-06T09:00:00Z', location: 'St. Paul, MN', status: 'Picked up' },
      { timestamp: '2025-01-07T18:30:00Z', location: 'Indianapolis, IN', status: 'In transit' },
      { timestamp: '2025-01-09T08:00:00Z', location: 'Dayton, OH', status: 'In transit — regional hub' },
    ],
    specialInstructions: 'Deliver to reception desk at Suite 110.',
    insuranceValue: 3217.62,
  },
  {
    id: 'SHP-2025-0003',
    orderId: 'ORD-2025-0007',
    status: 'Processing',
    carrier: 'UPS',
    trackingNumber: null,
    serviceLevel: 'UPS Ground',
    estimatedDelivery: '2025-01-22T00:00:00Z',
    actualDelivery: null,
    shipDate: null,
    shipFrom: {
      name: 'Solventum Distribution Center — Central',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    shipTo: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
    },
    items: [
      {
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        quantity: 60,
        serialNumbers: null,
        lotNumbers: null,
      },
      {
        productId: 'PRD-011',
        productName: 'Transbond MIP Moisture Insensitive Primer (5ml)',
        quantity: 48,
        serialNumbers: null,
        lotNumbers: null,
      },
      {
        productId: 'PRD-012',
        productName: 'Transbond Plus SEP Single Dose Packets (100pk)',
        quantity: 36,
        serialNumbers: null,
        lotNumbers: null,
      },
    ],
    packages: [],
    trackingHistory: [],
    specialInstructions: 'Consolidate all items in single shipment. Temperature sensitive.',
    insuranceValue: 9710.0,
  },
  {
    id: 'SHP-2024-0004',
    orderId: 'ORD-2025-0003',
    status: 'Delivered',
    carrier: 'FedEx',
    trackingNumber: '7948 1102 8834',
    serviceLevel: 'FedEx Express Saver',
    estimatedDelivery: '2024-12-13T00:00:00Z',
    actualDelivery: '2024-12-12T11:45:00Z',
    shipDate: '2024-12-06T10:00:00Z',
    shipFrom: {
      name: 'Solventum Distribution Center — Central',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    shipTo: {
      name: 'Bright Smiles Orthodontics',
      street: '615 Elsinore Pl',
      building: 'Suite 200, Reception',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
    },
    items: [
      {
        productId: 'PRD-020',
        productName: 'Clarity Aligner System — Practice Starter Kit',
        quantity: 1,
        serialNumbers: null,
        lotNumbers: ['CLR-ALN-KIT-2024-0445'],
      },
      {
        productId: 'PRD-021',
        productName: 'Clarity Aligner Case Credit Pack (25 cases)',
        quantity: 2,
        serialNumbers: null,
        lotNumbers: null,
      },
    ],
    packages: [
      { packageNumber: 1, weight: '5 lbs', dimensions: '18 x 14 x 8 in', description: 'Clarity Aligner Starter Kit and marketing materials' },
    ],
    trackingHistory: [
      { timestamp: '2024-12-06T10:00:00Z', location: 'St. Paul, MN', status: 'Picked up' },
      { timestamp: '2024-12-07T14:20:00Z', location: 'Indianapolis, IN', status: 'In transit' },
      { timestamp: '2024-12-08T06:30:00Z', location: 'Cincinnati, OH', status: 'At local terminal' },
      { timestamp: '2024-12-12T08:00:00Z', location: 'Cincinnati, OH', status: 'Out for delivery' },
      { timestamp: '2024-12-12T11:45:00Z', location: 'Cincinnati, OH', status: 'Delivered — signed by R. Daniels' },
    ],
    specialInstructions: null,
    insuranceValue: 11935.0,
  },
  {
    id: 'SHP-2024-0005',
    orderId: 'ORD-2025-0005',
    status: 'Delivered',
    carrier: 'UPS',
    trackingNumber: '1Z999AA10512345699',
    serviceLevel: 'UPS Ground',
    estimatedDelivery: '2024-10-18T00:00:00Z',
    actualDelivery: '2024-10-17T14:30:00Z',
    shipDate: '2024-10-08T07:00:00Z',
    shipFrom: {
      name: 'Solventum Distribution Center — Central',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    shipTo: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      building: 'Loading Dock, Suite 100',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
    },
    items: [
      {
        productId: 'PRD-020',
        productName: 'Clarity Aligner System — Practice Starter Kit',
        quantity: 8,
        serialNumbers: null,
        lotNumbers: ['CLR-ALN-KIT-2024-0501', 'CLR-ALN-KIT-2024-0502', 'CLR-ALN-KIT-2024-0503', 'CLR-ALN-KIT-2024-0504', 'CLR-ALN-KIT-2024-0505', 'CLR-ALN-KIT-2024-0506', 'CLR-ALN-KIT-2024-0507', 'CLR-ALN-KIT-2024-0508'],
      },
    ],
    packages: [
      { packageNumber: 1, weight: '22 lbs', dimensions: '24 x 24 x 18 in', description: '8x Clarity Aligner Starter Kits with marketing materials' },
    ],
    trackingHistory: [
      { timestamp: '2024-10-08T07:00:00Z', location: 'St. Paul, MN', status: 'Picked up' },
      { timestamp: '2024-10-10T12:00:00Z', location: 'Madison, WI', status: 'In transit' },
      { timestamp: '2024-10-14T09:00:00Z', location: 'Chicago, IL', status: 'At local hub' },
      { timestamp: '2024-10-17T07:30:00Z', location: 'Chicago, IL', status: 'Out for delivery' },
      { timestamp: '2024-10-17T14:30:00Z', location: 'Chicago, IL', status: 'Delivered — signed by warehouse staff' },
    ],
    specialInstructions: 'Multiple kits — distribute to individual locations per DSO allocation list.',
    insuranceValue: 23436.0,
  },
  {
    id: 'SHP-2024-0006',
    orderId: 'ORD-2024-0012',
    status: 'Delivered',
    carrier: 'UPS',
    trackingNumber: '1Z999AA10612345700',
    serviceLevel: 'UPS 2nd Day Air',
    estimatedDelivery: '2024-10-16T00:00:00Z',
    actualDelivery: '2024-10-15T09:20:00Z',
    shipDate: '2024-10-10T13:00:00Z',
    shipFrom: {
      name: 'Solventum Distribution Center — Central',
      street: '2510 Conway Ave',
      city: 'St. Paul',
      state: 'MN',
      zip: '55114',
    },
    shipTo: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      building: 'Loading Dock, Suite 100',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
    },
    items: [
      {
        productId: 'PRD-045',
        productName: 'Ortho Plier Set — Essentials (8-piece)',
        quantity: 8,
        serialNumbers: null,
        lotNumbers: null,
      },
      {
        productId: 'PRD-046',
        productName: 'Bracket Placement Instrument Set (5-piece)',
        quantity: 8,
        serialNumbers: null,
        lotNumbers: null,
      },
    ],
    packages: [
      { packageNumber: 1, weight: '14 lbs', dimensions: '20 x 16 x 10 in', description: '8x Plier Sets and 8x Instrument Sets' },
    ],
    trackingHistory: [
      { timestamp: '2024-10-10T13:00:00Z', location: 'St. Paul, MN', status: 'Picked up' },
      { timestamp: '2024-10-12T08:00:00Z', location: 'Milwaukee, WI', status: 'In transit' },
      { timestamp: '2024-10-15T06:00:00Z', location: 'Chicago, IL', status: 'Out for delivery' },
      { timestamp: '2024-10-15T09:20:00Z', location: 'Chicago, IL', status: 'Delivered — signed by warehouse staff' },
    ],
    specialInstructions: null,
    insuranceValue: 4569.0,
  },
  {
    id: 'SHP-2024-0007',
    orderId: 'ORD-2024-0011',
    status: 'Delivered',
    carrier: 'FedEx',
    trackingNumber: '7948 0098 5521',
    serviceLevel: 'FedEx Ground',
    estimatedDelivery: '2024-09-22T00:00:00Z',
    actualDelivery: '2024-09-21T15:10:00Z',
    shipDate: '2024-09-19T16:00:00Z',
    shipFrom: {
      name: 'Solventum Distribution Center — West',
      street: '5900 Optical Ct',
      city: 'San Jose',
      state: 'CA',
      zip: '95138',
    },
    shipTo: {
      name: 'Lakeside Family Orthodontics',
      street: '2501 Mountain View Dr',
      building: 'Suite 102, Front Office',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
    },
    items: [
      {
        productId: 'PRD-060',
        productName: 'Clinpro 5000 Fluoride Toothpaste (4 oz, 24pk)',
        quantity: 4,
        serialNumbers: null,
        lotNumbers: ['CP5K-LOT-2024-0445'],
      },
      {
        productId: 'PRD-061',
        productName: 'Clinpro White Varnish with TCP (50pk)',
        quantity: 3,
        serialNumbers: null,
        lotNumbers: ['CPWV-LOT-2024-0333'],
      },
    ],
    packages: [
      { packageNumber: 1, weight: '11 lbs', dimensions: '16 x 12 x 10 in', description: 'Prevention products — fluoride toothpaste and varnish' },
    ],
    trackingHistory: [
      { timestamp: '2024-09-19T16:00:00Z', location: 'San Jose, CA', status: 'Picked up' },
      { timestamp: '2024-09-20T05:30:00Z', location: 'Portland, OR', status: 'In transit — hub scan' },
      { timestamp: '2024-09-21T08:00:00Z', location: 'Bend, OR', status: 'Out for delivery' },
      { timestamp: '2024-09-21T15:10:00Z', location: 'Bend, OR', status: 'Delivered — signed by front desk' },
    ],
    specialInstructions: 'Deliver to front office. Small package — no dock needed.',
    insuranceValue: 1219.73,
  },
  {
    id: 'SHP-2025-0008',
    orderId: 'ORD-2025-0001',
    status: 'Out for Delivery',
    carrier: 'UPS',
    trackingNumber: '1Z999AA10812345712',
    serviceLevel: 'UPS Next Day Air',
    estimatedDelivery: '2025-01-16T00:00:00Z',
    actualDelivery: null,
    shipDate: '2025-01-15T08:00:00Z',
    shipFrom: {
      name: 'Solventum Distribution Center — West',
      street: '5900 Optical Ct',
      city: 'San Jose',
      state: 'CA',
      zip: '95138',
    },
    shipTo: {
      name: 'Chen Orthodontics',
      street: '1200 Madison Ave',
      building: 'Suite 300, Front Desk',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
    },
    items: [
      {
        productId: 'PRD-001',
        productName: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit',
        quantity: 20,
        serialNumbers: null,
        lotNumbers: ['CLR-ADV-LOT-2025-0101'],
      },
      {
        productId: 'PRD-002',
        productName: 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit',
        quantity: 20,
        serialNumbers: null,
        lotNumbers: ['CLR-ADV-LOT-2025-0102'],
      },
      {
        productId: 'PRD-010',
        productName: 'Transbond XT Light Cure Adhesive Syringe Kit',
        quantity: 10,
        serialNumbers: null,
        lotNumbers: ['TBXT-LOT-2025-0033'],
      },
    ],
    packages: [
      { packageNumber: 1, weight: '9 lbs', dimensions: '20 x 14 x 10 in', description: 'Clarity Advanced brackets (40 kits)' },
      { packageNumber: 2, weight: '4 lbs', dimensions: '12 x 10 x 8 in', description: 'Transbond XT adhesive (10 kits)' },
    ],
    trackingHistory: [
      { timestamp: '2025-01-15T08:00:00Z', location: 'San Jose, CA', status: 'Picked up' },
      { timestamp: '2025-01-15T22:00:00Z', location: 'Portland, OR', status: 'In transit — air hub' },
      { timestamp: '2025-01-16T06:30:00Z', location: 'Seattle, WA', status: 'Out for delivery' },
    ],
    specialInstructions: 'Leave at front desk with receptionist. Signature required.',
    insuranceValue: 7475.64,
  },
];

export const getShipmentById = (id) => shipments.find((s) => s.id === id);
export const getShipmentsByOrder = (orderId) => shipments.filter((s) => s.orderId === orderId);
export const getShipmentsByStatus = (status) => shipments.filter((s) => s.status === status);

export const shipmentStatuses = [
  'Processing',
  'Picked Up',
  'In Transit',
  'Out for Delivery',
  'Delivered',
  'Exception',
];

export default shipments;
