// Mock subscriptions for Solventum Ortho Portal
// Statuses: Active, Paused, Cancelled

export const subscriptions = [
  {
    biId: 'SUB-001',
    biName: 'Chen Ortho — Monthly Bracket & Bonding Replenishment',
    biDescription: 'Monthly auto-replenishment of Clarity Advanced brackets and Transbond bonding supplies for high-volume practice.',
    product: {
      id: 'PRD-001',
      name: 'Clarity Advanced Ceramic Brackets — Upper 5x5 Kit + Transbond XT',
      sku: 'SOL-CLR-ADV-U5',
    },
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    frequency: 'Monthly',
    quantity: 15,
    unitPrice: 170.10,
    recurringTotal: 2551.50,
    currency: 'USD',
    nextDelivery: '2025-02-01T00:00:00Z',
    lastDelivery: '2025-01-02T00:00:00Z',
    startDate: '2024-07-01T00:00:00Z',
    endDate: null,
    status: 'Active',
    deliveryAddress: {
      name: 'Chen Orthodontics',
      street: '1200 Madison Ave',
      building: 'Suite 300, Front Desk',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    autoRenew: true,
    contractId: 'CTR-001',
    paymentTerms: 'Net 30',
    deliveriesCompleted: 7,
    notes: 'Includes 15 upper bracket kits and 5 Transbond XT syringes. Review quantity at 12-month mark based on patient starts.',
  },
  {
    biId: 'SUB-002',
    biName: 'Bright Smiles — Quarterly Archwire & Auxiliary Supplies',
    biDescription: 'Quarterly replenishment of NiTi archwires, SS archwires, and auxiliary supplies for two locations.',
    product: {
      id: 'PRD-030',
      name: 'Archwire & Auxiliary Bundle — Practice Pack',
      sku: 'SOL-AW-AUX-BUNDLE',
    },
    customer: {
      id: 'ORG-003',
      name: 'Bright Smiles Orthodontics',
      contactName: 'Dr. Michael Thompson',
      contactEmail: 'm.thompson@brightsmiles.com',
    },
    frequency: 'Quarterly',
    quantity: 1,
    unitPrice: 2450.0,
    recurringTotal: 2450.0,
    currency: 'USD',
    nextDelivery: '2025-04-01T00:00:00Z',
    lastDelivery: '2025-01-03T00:00:00Z',
    startDate: '2024-04-01T00:00:00Z',
    endDate: null,
    status: 'Active',
    deliveryAddress: {
      name: 'Bright Smiles Orthodontics',
      street: '615 Elsinore Pl',
      building: 'Suite 200, Reception',
      city: 'Cincinnati',
      state: 'OH',
      zip: '45202',
      country: 'US',
    },
    autoRenew: true,
    contractId: 'CTR-003',
    paymentTerms: 'Net 30',
    deliveriesCompleted: 4,
    notes: 'Custom bundle: 30 NiTi packs, 20 SS packs, 10 TMA packs, 5 coil spring packs, 3 elastic tie packs. Split delivery across 2 locations.',
  },
  {
    biId: 'SUB-003',
    biName: 'Chen Ortho — Monthly Clarity Aligner Case Shipments',
    biDescription: 'Monthly Clarity Aligner case delivery for active treatment patients. Aligners shipped directly to practice.',
    product: {
      id: 'PRD-023',
      name: 'Clarity Aligner — Monthly Case Delivery',
      sku: 'SOL-CLR-ALN-MONTHLY',
    },
    customer: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      contactName: 'Dr. Sarah Chen',
      contactEmail: 'sarah.chen@chenortho.com',
    },
    frequency: 'Monthly',
    quantity: 8,
    unitPrice: 150.0,
    recurringTotal: 1200.0,
    currency: 'USD',
    nextDelivery: '2025-02-01T00:00:00Z',
    lastDelivery: '2025-01-03T00:00:00Z',
    startDate: '2024-06-01T00:00:00Z',
    endDate: null,
    status: 'Active',
    deliveryAddress: {
      name: 'Chen Orthodontics',
      street: '1200 Madison Ave',
      building: 'Suite 300, Front Desk',
      city: 'Seattle',
      state: 'WA',
      zip: '98104',
      country: 'US',
    },
    autoRenew: true,
    contractId: 'CTR-001',
    paymentTerms: 'Net 30',
    deliveriesCompleted: 8,
    notes: 'Average 8 active aligner cases per month. Quantity auto-adjusts based on active treatment count in Clarity portal.',
  },
  {
    biId: 'SUB-004',
    biName: 'Lakeside Ortho — Bi-Monthly Prevention Products',
    biDescription: 'Bi-monthly replenishment of Clinpro fluoride products and patient hygiene kits.',
    product: {
      id: 'PRD-060',
      name: 'Clinpro Prevention Bundle',
      sku: 'SOL-CPREV-BUNDLE',
    },
    customer: {
      id: 'ORG-005',
      name: 'Lakeside Family Orthodontics',
      contactName: 'Dr. Amanda Foster',
      contactEmail: 'a.foster@lakesideortho.com',
    },
    frequency: 'Bi-Monthly',
    quantity: 1,
    unitPrice: 485.0,
    recurringTotal: 485.0,
    currency: 'USD',
    nextDelivery: '2025-03-01T00:00:00Z',
    lastDelivery: '2025-01-05T00:00:00Z',
    startDate: '2024-05-01T00:00:00Z',
    endDate: null,
    status: 'Active',
    deliveryAddress: {
      name: 'Lakeside Family Orthodontics',
      street: '2501 Mountain View Dr',
      building: 'Suite 102, Front Office',
      city: 'Bend',
      state: 'OR',
      zip: '97701',
      country: 'US',
    },
    autoRenew: true,
    contractId: 'CTR-005',
    paymentTerms: 'Net 30',
    deliveriesCompleted: 5,
    notes: 'Bundle includes: 2x Clinpro 5000 (24pk), 1x Clinpro White Varnish (50pk), patient take-home kits.',
  },
  {
    biId: 'SUB-005',
    biName: 'Smile DSO — Monthly Bonding Supply Auto-Ship',
    biDescription: 'Monthly Transbond bonding supply replenishment for all 12 Smile DSO ortho locations.',
    product: {
      id: 'PRD-010',
      name: 'Transbond XT Light Cure Adhesive Syringe Kit',
      sku: 'SOL-TBXT-SYR-KIT',
    },
    customer: {
      id: 'ORG-002',
      name: 'Smile DSO Group',
      contactName: 'James Mitchell',
      contactEmail: 'j.mitchell@smiledsogroup.com',
    },
    frequency: 'Monthly',
    quantity: 36,
    unitPrice: 74.25,
    recurringTotal: 2673.0,
    currency: 'USD',
    nextDelivery: null,
    lastDelivery: '2024-11-15T00:00:00Z',
    startDate: '2024-06-01T00:00:00Z',
    endDate: '2024-12-01T00:00:00Z',
    status: 'Paused',
    deliveryAddress: {
      name: 'Smile DSO Group — Central Distribution',
      street: '4500 W Diversey Ave',
      building: 'Loading Dock, Suite 100',
      city: 'Chicago',
      state: 'IL',
      zip: '60639',
      country: 'US',
    },
    autoRenew: false,
    contractId: 'CTR-002',
    paymentTerms: 'Net 45',
    deliveriesCompleted: 6,
    notes: 'Paused — reviewing usage rates across locations. Some locations overstocked. Considering consolidation with quarterly bracket order.',
  },
  {
    biId: 'SUB-006',
    biName: 'Metro Dental — Quarterly Bracket Starter Replenishment',
    biDescription: 'Quarterly Victory Series metal bracket replenishment for starter ortho program.',
    product: {
      id: 'PRD-005',
      name: 'Victory Series Metal Brackets — Upper 5x5 Kit',
      sku: 'SOL-VIC-MTL-U5',
    },
    customer: {
      id: 'ORG-004',
      name: 'Metro Dental Partners',
      contactName: 'Dr. Robert Kim',
      contactEmail: 'r.kim@metrodentalpartners.com',
    },
    frequency: 'Quarterly',
    quantity: 25,
    unitPrice: 85.0,
    recurringTotal: 2125.0,
    currency: 'USD',
    nextDelivery: null,
    lastDelivery: '2024-07-01T00:00:00Z',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2024-09-30T00:00:00Z',
    status: 'Cancelled',
    deliveryAddress: {
      name: 'Metro Dental Partners',
      street: '900 Pacific Ave',
      building: 'Suite 200, Supply Room',
      city: 'Tacoma',
      state: 'WA',
      zip: '98402',
      country: 'US',
    },
    autoRenew: false,
    contractId: null,
    paymentTerms: 'Net 30',
    deliveriesCompleted: 3,
    notes: 'Cancelled — account under review due to overdue invoices. Will reinstate upon payment resolution.',
  },
];

export const getSubscriptionById = (biId) => subscriptions.find((s) => s.biId === biId);
export const getSubscriptionsByStatus = (status) =>
  subscriptions.filter((s) => s.status === status);
export const getSubscriptionsByCustomer = (customerId) =>
  subscriptions.filter((s) => s.customer.id === customerId);

export const subscriptionStatuses = ['Active', 'Paused', 'Cancelled'];

export default subscriptions;
