// Mock training resources for Solventum Ortho Portal
// Types: Online Course, Video, Hands-On Workshop, Webinar, Certification, In-Service

export const training = [
  {
    id: 'TRN-001',
    title: 'Clarity Aligner — Orthodontist Certification Program',
    type: 'Certification',
    format: 'Hybrid (Online + Hands-On)',
    division: 'Orthodontics',
    productIds: ['PRD-020', 'PRD-021', 'PRD-052'],
    productNames: ['Clarity Aligner System — Practice Starter Kit', 'Clarity Aligner Case Credit Pack (25 cases)', 'Clarity Intraoral Scanner System'],
    description:
      'Comprehensive certification program for orthodontists prescribing Clarity Aligners. Includes online didactic modules covering case selection, digital treatment planning in the Clarity portal, aligner delivery protocols, and troubleshooting. Culminates in hands-on case submission with mentor review.',
    duration: '2 days',
    durationMinutes: null,
    modules: 8,
    completionPercentage: null,
    prerequisites: ['Licensed orthodontist or dentist with ortho training', 'Clarity Aligner Practice Starter Kit purchased'],
    learningObjectives: [
      'Select appropriate cases for Clarity Aligner treatment',
      'Perform digital treatment planning using the Clarity portal',
      'Master staging, attachments, and IPR prescription',
      'Deliver aligners and manage patient expectations',
      'Troubleshoot common aligner issues and order refinements',
    ],
    instructor: {
      name: 'Dr. James Whitfield',
      title: 'Director of Aligner Education, Solventum Orthodontics',
    },
    nextAvailableDate: '2025-02-15T08:00:00Z',
    location: 'Solventum Education Center, Maplewood, MN',
    maxParticipants: 12,
    currentEnrollment: 8,
    cmeCredits: 16,
    price: 0,
    priceNote: 'Complimentary with Clarity Aligner Starter Kit purchase',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-001',
    thumbnailUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity-Aligners-Product-Photo_Top_White_Top?wid=400&hei=300&fit=crop',
    tags: ['clarity', 'aligner', 'certification', 'digital-ortho', 'treatment-planning'],
  },
  {
    id: 'TRN-002',
    title: 'Transbond Bonding Technique Workshop',
    type: 'Hands-On Workshop',
    format: 'In-Person Lab',
    division: 'Orthodontics',
    productIds: ['PRD-010', 'PRD-011', 'PRD-012'],
    productNames: ['Transbond XT Light Cure Adhesive Syringe Kit', 'Transbond MIP Moisture Insensitive Primer (5ml)', 'Transbond Plus SEP Single Dose Packets (100pk)'],
    description:
      'Hands-on workshop for orthodontic staff covering optimal bonding protocols using the Transbond adhesive system. Includes typodonts for practice of direct and indirect bonding techniques, moisture management, and troubleshooting bond failures.',
    duration: '4 hours',
    durationMinutes: 240,
    modules: 4,
    completionPercentage: null,
    prerequisites: ['Orthodontic assistant or hygienist certification'],
    learningObjectives: [
      'Properly prepare tooth surfaces for bracket bonding',
      'Apply Transbond Plus SEP for self-etching primer workflow',
      'Master direct bonding technique with Transbond XT adhesive',
      'Perform indirect bonding using custom trays',
      'Troubleshoot common bond failures and debonding issues',
    ],
    instructor: {
      name: 'Solventum Clinical Educator — Assigned at scheduling',
      title: null,
    },
    nextAvailableDate: '2025-01-25T08:00:00Z',
    location: 'On-site at customer facility',
    maxParticipants: 15,
    currentEnrollment: null,
    cmeCredits: 4,
    price: 0,
    priceNote: 'Complimentary for Gold and Platinum tier practices',
    certificateIssued: true,
    enrollmentUrl: '/training/request/TRN-002',
    thumbnailUrl: 'https://s7d9.scene7.com/is/image/mmmspinco/712-066_01_op_center?wid=400&hei=300&fit=crop',
    tags: ['transbond', 'bonding', 'workshop', 'hands-on', 'adhesive', 'technique'],
  },
  {
    id: 'TRN-003',
    title: 'Clarity Advanced — Bracket Positioning Masterclass',
    type: 'Hands-On Workshop',
    format: 'In-Person Lab',
    division: 'Orthodontics',
    productIds: ['PRD-001', 'PRD-002'],
    productNames: ['Clarity Advanced Ceramic Brackets — Upper 5x5 Kit', 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit'],
    description:
      'Advanced typodont-based workshop focusing on precision bracket positioning with Clarity Advanced ceramic brackets. Covers optimal heights, angulations, rotational control, and debonding technique to protect enamel. Includes comparison with metal bracket placement.',
    duration: '1 day',
    durationMinutes: null,
    modules: 6,
    completionPercentage: null,
    prerequisites: ['Licensed orthodontist', 'Basic Clarity bracket familiarity recommended'],
    learningObjectives: [
      'Position Clarity Advanced brackets for optimal esthetics and function',
      'Apply tooth-specific height and angulation guidelines',
      'Master ceramic bracket debonding technique to prevent enamel damage',
      'Manage rotational control with ceramic bracket systems',
      'Compare clinical outcomes with metal bracket alternatives',
    ],
    instructor: {
      name: 'Dr. Patricia Nakamura',
      title: 'Clinical Professor of Orthodontics, University of Washington',
    },
    nextAvailableDate: '2025-03-08T08:00:00Z',
    location: 'Solventum Innovation Center, Maplewood, MN',
    maxParticipants: 8,
    currentEnrollment: 4,
    cmeCredits: 8,
    price: 350.0,
    priceNote: 'Lab fee covers typodont materials. Free for Platinum tier.',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-003',
    thumbnailUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity_Advanced_Upper_Cuspid_Hook?wid=400&hei=300&fit=crop',
    tags: ['clarity', 'brackets', 'positioning', 'masterclass', 'ceramic', 'hands-on'],
  },
  {
    id: 'TRN-004',
    title: 'Digital Orthodontics — Clarity Scanner & Aligner Workflow',
    type: 'Online Course',
    format: 'Self-Paced Online',
    division: 'Orthodontics',
    productIds: ['PRD-052', 'PRD-020'],
    productNames: ['Clarity Intraoral Scanner System', 'Clarity Aligner System — Practice Starter Kit'],
    description:
      'Self-paced online course covering the complete digital orthodontics workflow from intraoral scanning with the Clarity scanner through treatment planning and aligner delivery. Includes software tutorials, case studies, and best practices for digital practice integration.',
    duration: '6 hours',
    durationMinutes: 360,
    modules: 10,
    completionPercentage: null,
    prerequisites: ['Clarity Scanner or compatible intraoral scanner', 'Clarity Aligner account'],
    learningObjectives: [
      'Perform accurate intraoral scans for orthodontic treatment planning',
      'Navigate the Clarity Aligner treatment planning portal',
      'Design aligner staging and attachment protocols',
      'Submit cases digitally and manage refinement orders',
      'Integrate digital workflows into daily practice operations',
    ],
    instructor: null,
    nextAvailableDate: null,
    location: 'Online — Solventum Learning Portal',
    maxParticipants: null,
    currentEnrollment: null,
    cmeCredits: 6,
    price: 0,
    priceNote: 'Free for Clarity Aligner certified practices',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-004',
    thumbnailUrl: 'https://s7d9.scene7.com/is/image/mmmspinco/clarity-portal-tx-design-page-roots-single-view-image-css-en-1?wid=400&hei=300&fit=crop',
    tags: ['digital', 'scanner', 'aligner', 'clarity', 'online', 'self-paced', 'workflow'],
  },
  {
    id: 'TRN-005',
    title: 'Ceramic Brackets in Practice — Clinical Case Review Webinar',
    type: 'Webinar',
    format: 'Live Webinar',
    division: 'Orthodontics',
    productIds: ['PRD-001', 'PRD-002', 'PRD-003', 'PRD-004'],
    productNames: ['Clarity Advanced Ceramic Brackets — Upper 5x5 Kit', 'Clarity Advanced Ceramic Brackets — Lower 5x5 Kit', 'Clarity Ultra Self-Ligating Brackets — Upper Kit', 'Clarity Ultra Self-Ligating Brackets — Lower Kit'],
    description:
      'Live webinar featuring case presentations from experienced orthodontists using Clarity ceramic bracket systems. Covers challenging case types, esthetic treatment approaches, patient management, and clinical pearls for maximizing ceramic bracket outcomes.',
    duration: '90 minutes',
    durationMinutes: 90,
    modules: 3,
    completionPercentage: null,
    prerequisites: [],
    learningObjectives: [
      'Review complex cases treated with Clarity ceramic brackets',
      'Apply clinical pearls for esthetic orthodontic treatment',
      'Manage patient expectations with ceramic bracket systems',
      'Compare Clarity Advanced vs Clarity Ultra for different case types',
    ],
    instructor: {
      name: 'Dr. Sarah Chen, Dr. Michael Thompson (Panel)',
      title: 'Solventum Orthodontic Advisory Board',
    },
    nextAvailableDate: '2025-01-28T12:00:00Z',
    location: 'Online — Zoom Webinar',
    maxParticipants: 200,
    currentEnrollment: 87,
    cmeCredits: 1.5,
    price: 0,
    priceNote: 'Free — registration required',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-005',
    thumbnailUrl: 'https://assets.solventum.com/is/image/mmmspinco/SQ_IMG_4076_cropped_whiterteeth?wid=400&hei=300&fit=crop',
    tags: ['clarity', 'ceramic', 'webinar', 'case-review', 'clinical', 'esthetics'],
  },
  {
    id: 'TRN-006',
    title: 'Archwire Selection & Sequencing — Video Series',
    type: 'Video',
    format: 'On-Demand Video Series',
    division: 'Orthodontics',
    productIds: ['PRD-030', 'PRD-031', 'PRD-032', 'PRD-033'],
    productNames: [
      'Nitinol Super Elastic Archwires — Upper Assortment Pack',
      'Stainless Steel Archwires — Upper Assortment Pack',
      'Nitinol Super Elastic Archwires — Lower Assortment Pack',
      'Beta Titanium (TMA) Archwires — Assorted Pack',
    ],
    description:
      'On-demand video series covering orthodontic archwire selection, sequencing strategies, and biomechanical principles. Features demonstrations of NiTi, stainless steel, and TMA wire properties with case-based sequencing examples.',
    duration: '3 hours (6 videos)',
    durationMinutes: 180,
    modules: 6,
    completionPercentage: null,
    prerequisites: [],
    learningObjectives: [
      'Select appropriate archwire material for each treatment phase',
      'Design efficient archwire sequencing protocols',
      'Understand force delivery differences between NiTi, SS, and TMA wires',
      'Apply biomechanical principles to complex tooth movement',
    ],
    instructor: {
      name: 'Multiple Faculty',
      title: 'Solventum Orthodontic Advisory Board',
    },
    nextAvailableDate: null,
    location: 'Online — Solventum Learning Portal',
    maxParticipants: null,
    currentEnrollment: null,
    cmeCredits: 3,
    price: 0,
    priceNote: 'Free for registered Solventum customers',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-006',
    thumbnailUrl: 'https://assets.solventum.com/is/image/mmmspinco/Nitinol-Super-Elastic?wid=400&hei=300&fit=crop',
    tags: ['archwires', 'biomechanics', 'video', 'on-demand', 'sequencing', 'NiTi', 'TMA'],
  },
  {
    id: 'TRN-007',
    title: 'Ortho Portal — Practice Ordering and Account Management',
    type: 'Online Course',
    format: 'Self-Paced Online',
    division: 'General',
    productIds: [],
    productNames: [],
    description:
      'Self-paced tutorial for new Ortho Portal users. Learn to navigate the portal, search products, place orders, track shipments, manage invoices, view consignment inventory, manage subscriptions, and submit Clarity Aligner cases.',
    duration: '30 minutes',
    durationMinutes: 30,
    modules: 5,
    completionPercentage: null,
    prerequisites: [],
    learningObjectives: [
      'Navigate the Ortho Portal dashboard and product catalog',
      'Place and track orders for brackets, bonding, and archwires',
      'Manage invoices and payment information',
      'View and manage consignment bracket inventory',
      'Set up and modify recurring supply subscriptions',
      'Submit Clarity Aligner cases through the portal',
    ],
    instructor: null,
    nextAvailableDate: null,
    location: 'Online — Solventum Learning Portal',
    maxParticipants: null,
    currentEnrollment: null,
    cmeCredits: 0,
    price: 0,
    priceNote: 'Free for all portal users',
    certificateIssued: false,
    enrollmentUrl: '/training/enroll/TRN-007',
    thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop',
    tags: ['portal', 'onboarding', 'ordering', 'self-paced', 'tutorial'],
  },
  {
    id: 'TRN-008',
    title: 'Clarity Ultra Self-Ligating — Clinical Techniques & Case Selection',
    type: 'Certification',
    format: 'Hybrid (Online + Hands-On)',
    division: 'Orthodontics',
    productIds: ['PRD-003', 'PRD-004'],
    productNames: ['Clarity Ultra Self-Ligating Brackets — Upper Kit', 'Clarity Ultra Self-Ligating Brackets — Lower Kit'],
    description:
      'Certification program for orthodontists adopting the Clarity Ultra self-ligating bracket system. Covers clip mechanics, passive-to-active transition, case selection for self-ligating, and hands-on typodont exercises. Includes first 5 cases mentored review.',
    duration: '1.5 days',
    durationMinutes: null,
    modules: 7,
    completionPercentage: null,
    prerequisites: ['Licensed orthodontist', 'Minimum 2 years clinical experience'],
    learningObjectives: [
      'Understand self-ligating clip mechanics and force delivery',
      'Select appropriate cases for self-ligating treatment',
      'Master Clarity Ultra bracket placement and wire engagement',
      'Manage passive-to-active archwire sequencing for self-ligating systems',
      'Compare self-ligating outcomes with conventional bracket treatment',
    ],
    instructor: {
      name: 'Dr. James Whitfield',
      title: 'Director of Orthodontic Education, Solventum',
    },
    nextAvailableDate: '2025-03-22T08:00:00Z',
    location: 'Solventum Education Center, Maplewood, MN',
    maxParticipants: 10,
    currentEnrollment: 3,
    cmeCredits: 12,
    price: 0,
    priceNote: 'Complimentary for practices committing to Clarity Ultra system',
    certificateIssued: true,
    enrollmentUrl: '/training/enroll/TRN-008',
    thumbnailUrl: 'https://assets.solventum.com/is/image/mmmspinco/Clarity-Ultra-Self-ligating-Bracket_Closed_Retouch?wid=400&hei=300&fit=crop',
    tags: ['clarity', 'ultra', 'self-ligating', 'certification', 'hands-on', 'technique'],
  },
];

export const getTrainingById = (id) => training.find((t) => t.id === id);
export const getTrainingByProduct = (productId) =>
  training.filter((t) => t.productIds.includes(productId));
export const getTrainingByType = (type) => training.filter((t) => t.type === type);
export const getTrainingByDivision = (division) =>
  training.filter((t) => t.division === division);

export const trainingTypes = [
  'Online Course',
  'Video',
  'Hands-On Workshop',
  'Webinar',
  'Certification',
  'In-Service',
];

export default training;
