// Mock treatment plans for Solventum Ortho Portal
// Statuses: Submitted | Planning | Approved | In Progress | Completed | On Hold
// Complexity: Simple | Moderate | Complex
// Treatment types: Clarity Aligners | Clarity Brackets | Combination

export const treatmentPlans = [
  {
    id: 'TP-001',
    patientInitials: 'J.M.',
    caseNumber: 'CLR-2026-0142',
    orthodontistId: 'USR-001',
    organizationId: 'ORG-001',
    organizationName: 'Chen Orthodontics',
    clarityUrl: 'https://clarity.solventum.com/cases/CLR-2026-0142',
    locationId: null,
    treatmentType: 'Clarity Aligners',
    status: 'In Progress',
    complexity: 'Moderate',
    totalAligners: 24,
    currentAligner: 16,
    stages: [
      { name: 'Initial Alignment', startAligner: 1, endAligner: 8, status: 'Completed' },
      { name: 'Space Closure', startAligner: 9, endAligner: 16, status: 'In Progress' },
      { name: 'Detailing & Finishing', startAligner: 17, endAligner: 24, status: 'Upcoming' },
    ],
    productsUsed: [
      { productId: 'PRD-026', productName: 'Clarity Aligners Starter Kit', quantity: 1 },
      { productId: 'PRD-029', productName: 'Clarity Precision Grip Attachments', quantity: 1 },
    ],
    startDate: '2025-09-15T00:00:00Z',
    estimatedEndDate: '2026-06-15T00:00:00Z',
    lastVisit: '2026-02-05T00:00:00Z',
    nextVisit: '2026-03-12T00:00:00Z',
    notes: 'Patient progressing well. Minor midcourse correction planned at stage 3. Upper lateral incisors tracking slightly behind — consider adding precision cuts to aligners 17-20.',
    createdAt: '2025-08-20T00:00:00Z',
    updatedAt: '2026-02-05T00:00:00Z',
  },
  {
    id: 'TP-002',
    patientInitials: 'A.R.',
    caseNumber: 'CLR-2026-0198',
    orthodontistId: 'USR-001',
    organizationId: 'ORG-001',
    organizationName: 'Chen Orthodontics',
    clarityUrl: 'https://clarity.solventum.com/cases/CLR-2026-0198',
    locationId: null,
    treatmentType: 'Combination',
    status: 'In Progress',
    complexity: 'Complex',
    totalAligners: 36,
    currentAligner: 10,
    stages: [
      { name: 'Bracket Phase — Molar Uprighting', startAligner: null, endAligner: null, status: 'Completed', note: 'Clarity Advanced brackets on upper 6s and 7s for 4 months' },
      { name: 'Initial Alignment', startAligner: 1, endAligner: 12, status: 'In Progress' },
      { name: 'Arch Coordination', startAligner: 13, endAligner: 22, status: 'Upcoming' },
      { name: 'Space Closure', startAligner: 23, endAligner: 30, status: 'Upcoming' },
      { name: 'Detailing & Finishing', startAligner: 31, endAligner: 36, status: 'Upcoming' },
    ],
    productsUsed: [
      { productId: 'PRD-001', productName: 'Clarity Advanced Ceramic Brackets', quantity: 1 },
      { productId: 'PRD-016', productName: 'Transbond XT Light Cure Adhesive', quantity: 1 },
      { productId: 'PRD-026', productName: 'Clarity Aligners Starter Kit', quantity: 1 },
      { productId: 'PRD-027', productName: 'Clarity Aligners Refinement Kit', quantity: 1 },
      { productId: 'PRD-029', productName: 'Clarity Precision Grip Attachments', quantity: 2 },
    ],
    startDate: '2025-06-01T00:00:00Z',
    estimatedEndDate: '2027-01-15T00:00:00Z',
    lastVisit: '2026-02-12T00:00:00Z',
    nextVisit: '2026-03-19T00:00:00Z',
    notes: 'Complex combination case — Class II correction with bilateral posterior crossbite. Initial bracket phase completed successfully. Transitioned to aligners in November 2025. Patient compliance with aligner wear has been excellent (22+ hours/day reported).',
    createdAt: '2025-05-10T00:00:00Z',
    updatedAt: '2026-02-12T00:00:00Z',
  },
  {
    id: 'TP-003',
    patientInitials: 'K.L.',
    caseNumber: 'CLR-2025-0087',
    orthodontistId: 'USR-006',
    organizationId: 'ORG-003',
    organizationName: 'Bright Smiles Orthodontics',
    clarityUrl: 'https://clarity.solventum.com/cases/CLR-2025-0087',
    locationId: null,
    treatmentType: 'Clarity Aligners',
    status: 'Completed',
    complexity: 'Simple',
    totalAligners: 14,
    currentAligner: 14,
    stages: [
      { name: 'Initial Alignment', startAligner: 1, endAligner: 6, status: 'Completed' },
      { name: 'Space Closure', startAligner: 7, endAligner: 10, status: 'Completed' },
      { name: 'Detailing & Finishing', startAligner: 11, endAligner: 14, status: 'Completed' },
    ],
    productsUsed: [
      { productId: 'PRD-026', productName: 'Clarity Aligners Starter Kit', quantity: 1 },
    ],
    startDate: '2025-05-20T00:00:00Z',
    estimatedEndDate: '2025-12-20T00:00:00Z',
    completedDate: '2025-12-18T00:00:00Z',
    lastVisit: '2025-12-18T00:00:00Z',
    nextVisit: null,
    notes: 'Simple crowding case completed on schedule. Mild lower anterior crowding with minor upper spacing. No refinement aligners needed. Retainers delivered at final visit. Patient very satisfied with results.',
    createdAt: '2025-05-01T00:00:00Z',
    updatedAt: '2025-12-18T00:00:00Z',
  },
  {
    id: 'TP-004',
    patientInitials: 'S.W.',
    caseNumber: 'CLR-2026-0215',
    orthodontistId: 'USR-002',
    organizationId: 'ORG-002',
    organizationName: 'Smile DSO Group',
    clarityUrl: 'https://clarity.solventum.com/cases/CLR-2026-0215',
    locationId: 'LOC-001',
    treatmentType: 'Clarity Aligners',
    status: 'Planning',
    complexity: 'Complex',
    totalAligners: 32,
    currentAligner: 0,
    stages: [
      { name: 'IPR & Attachment Placement', startAligner: 0, endAligner: 0, status: 'Upcoming', note: 'Interproximal reduction 2-2 upper and lower' },
      { name: 'Initial Alignment & Leveling', startAligner: 1, endAligner: 10, status: 'Upcoming' },
      { name: 'Deep Bite Correction', startAligner: 11, endAligner: 18, status: 'Upcoming' },
      { name: 'Space Closure', startAligner: 19, endAligner: 26, status: 'Upcoming' },
      { name: 'Detailing & Finishing', startAligner: 27, endAligner: 32, status: 'Upcoming' },
    ],
    productsUsed: [
      { productId: 'PRD-026', productName: 'Clarity Aligners Starter Kit', quantity: 1 },
      { productId: 'PRD-029', productName: 'Clarity Precision Grip Attachments', quantity: 2 },
    ],
    startDate: null,
    estimatedEndDate: null,
    lastVisit: '2026-02-10T00:00:00Z',
    nextVisit: '2026-03-05T00:00:00Z',
    notes: 'Complex deep bite case with moderate crowding. Digital treatment plan under review — second ClinCheck revision requested to improve upper incisor intrusion staging. Dr. at Location #4 (Naperville) wants to discuss anchorage options before approval.',
    createdAt: '2026-01-28T00:00:00Z',
    updatedAt: '2026-02-10T00:00:00Z',
  },
  {
    id: 'TP-005',
    patientInitials: 'R.T.',
    caseNumber: 'CLR-2026-0233',
    orthodontistId: 'USR-006',
    organizationId: 'ORG-003',
    organizationName: 'Bright Smiles Orthodontics',
    clarityUrl: 'https://clarity.solventum.com/cases/CLR-2026-0233',
    locationId: null,
    treatmentType: 'Clarity Brackets',
    status: 'Submitted',
    complexity: 'Moderate',
    totalAligners: null,
    currentAligner: null,
    stages: [
      { name: 'Bonding & Initial Wires', startAligner: null, endAligner: null, status: 'Upcoming', estimatedDuration: '3 months' },
      { name: 'Working Wires & Space Closure', startAligner: null, endAligner: null, status: 'Upcoming', estimatedDuration: '4 months' },
      { name: 'Finishing & Detailing', startAligner: null, endAligner: null, status: 'Upcoming', estimatedDuration: '2 months' },
    ],
    productsUsed: [
      { productId: 'PRD-001', productName: 'Clarity Advanced Ceramic Brackets', quantity: 1 },
      { productId: 'PRD-016', productName: 'Transbond XT Light Cure Adhesive', quantity: 1 },
      { productId: 'PRD-033', productName: 'Nitinol Heat-Activated Archwires', quantity: 1 },
      { productId: 'PRD-034', productName: 'Beta-Titanium Archwires', quantity: 1 },
      { productId: 'PRD-032', productName: 'Unitek Stainless Steel Archwires', quantity: 1 },
    ],
    startDate: null,
    estimatedEndDate: null,
    lastVisit: null,
    nextVisit: null,
    notes: 'Newly submitted bracket case. Teenage patient (age 15) with Class I malocclusion, moderate crowding upper and lower. Patient requested ceramic brackets for aesthetics. Parents prefer fixed appliances over aligners for compliance reasons. Awaiting treatment plan approval.',
    createdAt: '2026-02-19T00:00:00Z',
    updatedAt: '2026-02-19T00:00:00Z',
  },
  {
    id: 'TP-006',
    patientInitials: 'M.H.',
    caseNumber: 'CLR-2025-0176',
    orthodontistId: 'USR-002',
    organizationId: 'ORG-002',
    organizationName: 'Smile DSO Group',
    clarityUrl: 'https://clarity.solventum.com/cases/CLR-2025-0176',
    locationId: 'LOC-002',
    treatmentType: 'Clarity Aligners',
    status: 'On Hold',
    complexity: 'Moderate',
    totalAligners: 22,
    currentAligner: 8,
    stages: [
      { name: 'Initial Alignment', startAligner: 1, endAligner: 8, status: 'Completed' },
      { name: 'Midcourse Correction', startAligner: 9, endAligner: 14, status: 'On Hold' },
      { name: 'Detailing & Finishing', startAligner: 15, endAligner: 22, status: 'Upcoming' },
    ],
    productsUsed: [
      { productId: 'PRD-026', productName: 'Clarity Aligners Starter Kit', quantity: 1 },
      { productId: 'PRD-027', productName: 'Clarity Aligners Refinement Kit', quantity: 1 },
      { productId: 'PRD-029', productName: 'Clarity Precision Grip Attachments', quantity: 1 },
    ],
    startDate: '2025-08-10T00:00:00Z',
    estimatedEndDate: '2026-05-10T00:00:00Z',
    lastVisit: '2026-01-15T00:00:00Z',
    nextVisit: null,
    notes: 'Treatment on hold — patient relocated temporarily for work (3-month assignment). Initial alignment phase completed successfully. New impressions/scans will be needed when patient returns in April 2026 to verify fit before continuing with midcourse correction trays. Attachments may need to be rebonded.',
    createdAt: '2025-07-20T00:00:00Z',
    updatedAt: '2026-01-15T00:00:00Z',
  },
];

export const getTreatmentPlanById = (id) => treatmentPlans.find((t) => t.id === id);
export const getTreatmentPlansByOrg = (orgId) => treatmentPlans.filter((t) => t.organizationId === orgId);
export const getTreatmentPlansByStatus = (status) => treatmentPlans.filter((t) => t.status === status);
export const treatmentPlanStatuses = ['Submitted', 'Planning', 'Approved', 'In Progress', 'Completed', 'On Hold'];
export default treatmentPlans;
