// Mock users for Solventum Ortho Portal

export const users = [
  {
    id: 'USR-001',
    firstName: 'Sarah',
    lastName: 'Chen',
    fullName: 'Dr. Sarah Chen',
    email: 'orthodontist@chenortho.com',
    phone: '+1 (206) 555-0142',
    role: 'orthodontist',
    title: 'Orthodontist',
    organization: {
      id: 'ORG-001',
      name: 'Chen Orthodontics',
      type: 'orthodontic_practice',
      address: {
        street: '1200 Madison Ave, Suite 300',
        city: 'Seattle',
        state: 'WA',
        zip: '98104',
        country: 'US',
      },
    },
    permissions: [
      'view_products',
      'place_orders',
      'view_orders',
      'view_invoices',
      'request_quotes',
      'request_samples',
      'view_treatment_plans',
      'manage_treatment_plans',
      'submit_service_requests',
      'view_training',
      'view_documentation',
    ],
    preferences: {
      defaultShipTo: 'SHIP-CO-01',
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: false,
        orderUpdates: true,
        promotions: true,
      },
    },
    lastLogin: '2026-02-18T08:32:00Z',
    createdAt: '2023-06-10T14:00:00Z',
    isActive: true,
    avatar: null,
  },
  {
    id: 'USR-002',
    firstName: 'Mark',
    lastName: 'Reynolds',
    fullName: 'Mark Reynolds',
    email: 'admin@smiledso.com',
    phone: '+1 (312) 555-0287',
    role: 'dso',
    title: 'VP of Operations',
    organization: {
      id: 'ORG-002',
      name: 'Smile DSO Group',
      type: 'dso',
      address: {
        street: '4500 W Diversey Ave',
        city: 'Chicago',
        state: 'IL',
        zip: '60639',
        country: 'US',
      },
    },
    permissions: [
      'view_products',
      'place_orders',
      'view_orders',
      'bulk_ordering',
      'view_invoices',
      'manage_invoices',
      'request_quotes',
      'request_samples',
      'view_treatment_plans',
      'view_pricing_tiers',
      'manage_returns',
      'view_training',
      'view_documentation',
    ],
    preferences: {
      defaultShipTo: 'SHIP-SDG-01',
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: true,
        orderUpdates: true,
        promotions: true,
      },
    },
    lastLogin: '2026-02-17T16:45:00Z',
    createdAt: '2022-11-03T09:30:00Z',
    isActive: true,
    avatar: null,
  },
  {
    id: 'USR-003',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    fullName: 'Emily Rodriguez',
    email: 'salesrep@solventum.com',
    phone: '+1 (269) 555-0193',
    role: 'sales_rep',
    title: 'Orthodontic Sales Specialist — Northeast',
    organization: {
      id: 'ORG-SOL',
      name: 'Solventum Corporation',
      type: 'manufacturer',
      address: {
        street: '2510 Conway Ave',
        city: 'St. Paul',
        state: 'MN',
        zip: '55144',
        country: 'US',
      },
    },
    permissions: [
      'view_products',
      'view_all_orders',
      'manage_quotes',
      'view_all_invoices',
      'view_all_customers',
      'manage_pricing',
      'request_samples',
      'view_treatment_plans',
      'manage_service_requests',
      'view_reports',
      'manage_training',
    ],
    territory: {
      region: 'Northeast',
      states: ['NY', 'NJ', 'CT', 'MA', 'PA'],
      accounts: ['ORG-001', 'ORG-002', 'ORG-003', 'ORG-004', 'ORG-005'],
    },
    preferences: {
      defaultShipTo: null,
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: true,
        orderUpdates: true,
        promotions: false,
      },
    },
    lastLogin: '2026-02-19T09:10:00Z',
    createdAt: '2021-03-15T10:00:00Z',
    isActive: true,
    avatar: null,
  },
  {
    id: 'USR-004',
    firstName: 'Lisa',
    lastName: 'Park',
    fullName: 'Lisa Park',
    email: 'ar@solventum.com',
    phone: '+1 (651) 555-0361',
    role: 'ar',
    title: 'Accounts Receivable Specialist',
    organization: {
      id: 'ORG-SOL',
      name: 'Solventum Corporation',
      type: 'manufacturer',
      address: {
        street: '2510 Conway Ave',
        city: 'St. Paul',
        state: 'MN',
        zip: '55144',
        country: 'US',
      },
    },
    permissions: [
      'view_all_invoices',
      'manage_invoices',
      'view_all_orders',
      'view_all_customers',
      'view_reports',
    ],
    preferences: {
      defaultShipTo: null,
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: false,
        orderUpdates: false,
        promotions: false,
      },
    },
    lastLogin: '2026-02-18T11:20:00Z',
    createdAt: '2023-01-20T08:00:00Z',
    isActive: true,
    avatar: null,
  },
  {
    id: 'USR-005',
    firstName: 'David',
    lastName: 'Kim',
    fullName: 'David Kim',
    email: 'csr@solventum.com',
    phone: '+1 (651) 555-0245',
    role: 'csr',
    title: 'Customer Service Representative',
    organization: {
      id: 'ORG-SOL',
      name: 'Solventum Corporation',
      type: 'manufacturer',
      address: {
        street: '2510 Conway Ave',
        city: 'St. Paul',
        state: 'MN',
        zip: '55144',
        country: 'US',
      },
    },
    permissions: [
      'view_all_orders',
      'view_all_customers',
      'manage_service_requests',
      'view_returns',
      'manage_returns',
      'view_shipments',
    ],
    preferences: {
      defaultShipTo: null,
      currency: 'USD',
      language: 'en-US',
      notifications: {
        email: true,
        sms: false,
        orderUpdates: true,
        promotions: false,
      },
    },
    lastLogin: '2026-02-19T07:45:00Z',
    createdAt: '2024-05-10T08:00:00Z',
    isActive: true,
    avatar: null,
  },
];

export const getCurrentUser = (userId = 'USR-001') => {
  return users.find((u) => u.id === userId) || users[0];
};

export default users;
